// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_StatsBuilder",["dojo/_base/declare","../../../../supportClasses/conditionalStyling/ConditionalStyleUtil","../../../../sections/dynamicSettings/supportClasses/FilterUtil","../../ChartTypes","../utils/ChartDataUtil"],function(u,v,w,q,k){return u(null,{_visualProperties:null,_seriesItems:null,_viewModel:null,_currentFeatureIndex:null,_isMultiFeatureChart:null,_excludedSeriesHash:null,_comparisonFeatureAttributes:null,
_chartType:null,_isSecondaryPlot:!1,_oppositeDirections:!1,_totalStats:null,_seriesValues:null,_seriesStats:null,constructor:function(a){this._visualProperties=a.visualProperties;this._seriesItems=a.seriesItems;this._viewModel=a.viewModel;this._currentFeatureIndex=a.currentFeatureIndex;this._isMultiFeatureChart=a.isMultiFeatureChart;this._excludedSeriesHash=a.excludedSeriesHash||{};this._comparisonFeatureAttributes=a.comparisonFeatureAttributes;this._chartType=a.chartType;this._isSecondaryPlot=a.isSecondaryPlot;
this._oppositeDirections=a.oppositeDirections;this._calcValuesForAllSeries();this._calcInSeriesStats();this._visualProperties.isStacked&&this._calcInStackStats();this._calcTotalStats()},gettatisticsForSeriesAt:function(a){return this._seriesStats[a]},getTotalStats:function(){return this._totalStats},_calcValuesForAllSeries:function(){var a=this._visualProperties,b=this._seriesItems,d=this._viewModel,f=this._currentFeatureIndex,e=this._isMultiFeatureChart,c=this._comparisonFeatureAttributes,g=this._chartType,
h=1<b.length&&a.renderColumnBarsInOppositeDirections;this._seriesValues=this._seriesItems.map(function(r,n){var l=2===b.length&&(h||this._oppositeDirections&&this._isSecondaryPlot)?k.CHART_DATA_SMOOTH:null;if(a.filter&&a.filter.ranges)l=k.getChartData({filterRangesStats:w.getRangeStatistics(a.filter.ranges),numPoints:b[0].points.length,chartData:l,visualProperties:a});else if(a.conditionalStyling){var t=v.getStatistics(a.conditionalStyling);t&&b.length&&(l=k.getChartData({conditionalStats:t,numPoints:b[0].points.length,
chartData:l,visualProperties:a}))}return r.points.map(function(b,h){if(b.hidden)return{value:void 0};var p=k.getPointValue({point:b,index:h,seriesIndex:n,maxValue:!1,chartType:g,visualProperties:a,viewModel:d,currentFeatureIndex:e?q.isLineLike(g)?n:h:f,chartData:l,isComparisonSeries:r.isComparisonSeries,comparisonFeatureAttribute:c&&c[0]}),m=d.getBenchmarkController&&d.getBenchmarkController();return q.isBenchmarkSupported(g,e)&&m&&0<=m.getAreaIndex()&&m.getAreaIndex()!==f?(b=k.getPointValue({point:b,
index:h,seriesIndex:n,maxValue:!1,chartType:g,visualProperties:a,viewModel:d,currentFeatureIndex:m.getAreaIndex(),chartData:l,isComparisonSeries:!1}),{value:p-b,isBenchmarked:!0,ownValue:p}):{value:p}})},this)},_calcInSeriesStats:function(){this._seriesStats=this._seriesItems.map(function(a,b){var d=0,f=0,e=1E6,c=-1E6,g=0;this._excludedSeriesHash[a.label]||a.points.forEach(function(a,k){a.hidden||(g++,a=this._getValueAt(b,k),d+=a,f+=Math.abs(a),e=Math.min(e,a),c=Math.max(c,a))},this);return{values:this._seriesValues[b],
sumInSeries:d,absSumInSeries:f,minInSeries:e,maxInSeries:c,avgInSeries:d/g}},this)},_calcInStackStats:function(){this._seriesItems[0].points.forEach(function(a,b){var d=0,f=[],e=[];this._seriesItems.forEach(function(c,e){this._excludedSeriesHash[c.label]||a.hidden||(c=this._getValueAt(e,b),f[e]=c,d+=Math.abs(c))},this);this._seriesItems.forEach(function(c,g){if(!this._excludedSeriesHash[c.label]&&!a.hidden){c=this._seriesStats[g];c.stackValues=c.stackValues||[];c.stackValues[b]=f;c.weightsInStack=
c.weightsInStack||[];var h=this._getValueAt(g,b),h=c.weightsInStack[b]=h/d;c.stackValuesAsWeighedPercents=c.stackValuesAsWeighedPercents||[];c.stackValuesAsWeighedPercents[b]=e;e[g]=100*h}},this)},this)},_calcTotalStats:function(){var a=this._totalStats={minYValue:Infinity,maxYValue:-Infinity,stackedValues:this._visualProperties.isStacked?[]:null,crossSeriesStats:null};this._seriesItems.forEach(function(b,d){if(!this._excludedSeriesHash[b.label]){var f=this._seriesStats[d];b.points.forEach(function(b,
c){b.hidden||(b=this._getValueAt(d,c),b=this._visualProperties.showValuesAsWeightInStack?100*f.weightsInStack[c]:this._visualProperties.yAxis.showValuesAsWeightsInSeries?b/f.absSumInSeries*100:b,a.stackedValues?(a.stackedValues[c]=a.stackedValues[c]||0,c=a.stackedValues[c]+=b,a.minYValue=Math.min(c,a.minYValue),a.maxYValue=this._visualProperties.showValuesAsWeightInStack?100:Math.max(c,a.maxYValue)):(a.minYValue=Math.min(b,a.minYValue),a.maxYValue=Math.max(b,a.maxYValue)))},this)}},this);a.crossSeriesStats=
this._isMultiFeatureChart&&this._collectCrossSeriesStats()},_collectCrossSeriesStats:function(){return this._seriesStats[0].values.map(function(a,b){var d=0,f=0,e=1E6,c=-1E6;this._seriesStats.forEach(function(a){a=a.values[b].value||0;d+=a;f+=Math.abs(a);e=Math.min(e,a);c=Math.max(c,a)});return{sum:d,absSum:f,min:e,max:c,avg:d/this._seriesStats.length}},this)},_getValueAt:function(a,b){return(b=(a=this._seriesValues[a])&&a[b])&&b.value||0}})});