// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/utils/ChartDataUtil",["../../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer","esri/dijit/geoenrichment/utils/ObjectUtil","../../ChartTypes","esri/dijit/geoenrichment/ReportPlayer/countryConfig"],function(l,m,n,u){function p(a){return k||(a&&a.yAxis&&a.yAxis.nonZeroInclusive?v:w)}var g={formatNumber:function(a,b,c,f){a=a||0;b={places:b.dataLabelsDecimals||0,preserveTrailingZeroes:!0};if(f)return m.formatNumberAsCurrency(a,
u.getCurrencyFormat(),b);a=m.formatNumber(a,b);c&&(a+="%");return a},undefinedToDefault:function(a,b){return void 0===a?b:a}},k,w=[1E3,1100,1200,150,70,900,110,300,80,200,1700],v=[1E3,1100,1250,1200,1050,990],q=[1,.7,1.2,.5,1.1,1.3,.3,2,.4],r=[.91,.92,.9,1.2,1.2,1.3];g.CHART_DATA_SMOOTH=[1145,1134,1159,1275,1404,1408,1337,1149,1074,1040,1065,1078,964,798,531,360,254,258];g.getPointValue=function(a){var b=a.point,c=a.index,f=a.seriesIndex,g=a.chartType,d=a.visualProperties,h=a.viewModel,x=a.currentFeatureIndex,
e=a.chartData,k=a.isComparisonSeries,t=a.comparisonFeatureAttribute;a=a.numPoints;if(b.value&&(b.value.value||h.dynamicReportInfo))return b.value.value;if(h.dynamicReportInfo)e=k?t&&t[b.fieldInfo.name]||0:l.getFieldDataValue(b.fieldInfo,h.dynamicReportInfo.fieldData,x),e=m.parseNumber(e),isNaN(e)&&console.log("Can't render chart value for field \x3d\x3e "+(b.fieldInfo?b.fieldInfo.name:"missing field"));else if(b=b.fieldInfo&&b.fieldInfo.statefulName&&b.fieldInfo.statefulName.charAt(0),e=e||p(d),e=
e[c%e.length],g===n.GAUGE&&"p"!==b&&d.gaugeRangeMax)a=d.gaugeRangeMin||0,e=.425123*(d.gaugeRangeMax-a)+a;else if(g===n.WAFFLE)"p"===b||"number"!==typeof d.waffleRangeMin&&"number"!==typeof d.waffleRangeMax||(c=d.waffleRangeMin,d=d.waffleRangeMax,"number"===typeof c&&"number"!==typeof d?d=0===c?1E3:c*((1<a?a:2)+1):"number"!==typeof c&&"number"===typeof d&&(c=0),e=.9085*(d-c)+c),a&&(e="p"===b?90.85/a:e/a);else if(e*=q[f%q.length]*(0===f?1:r[c%r.length]),!d.conditionalStyling){a=e;if("p"===b||d.dataLabelsShowValuePercentSymbol||
d.yAxis&&d.yAxis.showPercentSymbol||d.yAxis&&d.yAxis.showValuesAsWeightsInSeries)a=Number((a/24.5123).toFixed(d.dataLabelsDecimals||1));"i"===b&&(a=Number((a/7).toFixed(d.dataLabelsDecimals||1)));e=a}return e};g.getCaptionValue=function(a,b){return a.captionFieldInfo?b.dynamicReportInfo?l.getFieldDataValue(a.captionFieldInfo,b.dynamicReportInfo.fieldData):l.renderFieldInfoInTableCell(a.captionFieldInfo).formattedValue:""};g.allowNegativeValuesInPreview=function(a,b){return n.supportsNegativeValues(a)&&
!b.isStacked&&!b.renderColumnBarsInOppositeDirections};g.getChartData=function(a){var b=a.chartData,b=(b||p(a.visualProperties)).slice();b.length=Math.min(b.length,a.numPoints);var c=Infinity,f=-Infinity;b.forEach(function(a){c=Math.min(c,a);f=Math.max(f,a)});if(a.conditionalStats){var g=1.1*a.conditionalStats.max/f;return b.map(function(a){return a*g})}if(a.filterRangesStats){var d=f-c,h=c,c=isFinite(a.filterRangesStats.min)?a.filterRangesStats.min:Math.min(0,c),f=isFinite(a.filterRangesStats.max)?
a.filterRangesStats.max:f>=c?f:2*c;a=.1*(f-c);c+=a;f-=a;g=(f-c)/d;return b.map(function(a){return(a-h)*g+c})}return b};g.setPreviewChartData_dev=function(a){k=a};return g});