// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/DataProviderGE","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/when esri/kernel ./dataProvider/_CommandSupport ./dataProvider/_SerializationSupport ./dataProvider/_ServerSerializationSupport ./dataProvider/supportClasses/areas/AnalysisAreaUtil ./dataProvider/supportClasses/areas/AnalysisAreaJsonUtil ./dataProvider/supportClasses/areas/AreasPreprocessor ./dataProvider/supportClasses/CustomReportsManager ./dataProvider/supportClasses/TemplateJsonLoader ./dataProvider/supportClasses/ReportDataProcessor ./dataProvider/supportClasses/InfographicOptionsProvider ./dataProvider/supportClasses/GEUtil ./dataProvider/supportClasses/attachments/DefaultAttachmentsStore ./dataProvider/supportClasses/attachments/CustomAttachmentsStore ./dataProvider/supportClasses/PortalManager ./dataProvider/supportClasses/data/VariablesUtil ./dataProvider/commands/mapToImage/MapToURLUtil ./core/themes/ThemeLibrary ./core/themes/ReportThemes esri/dijit/geoenrichment/ReportPlayer/countryConfig esri/dijit/geoenrichment/utils/ProjectionUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),
function(v,h,l,m,w,x,y,z,A,q,r,d,t,k,B,n,C,D,E,F,G,H,u,p,I,J){return v([x,y,z],{analysisAreasLimit:-1,cacheTemplates:!0,printMapTaskUrl:null,resetReportItemsCache:!0,_infographicOptionsProvider:null,constructor:function(a){h.mixin(this,a);this._infographicOptionsProvider=new B},_getAttachmentsStore:function(a){return(new C(a)).initialize()},getCustomReports:function(a){return d.getCustomReports(a)},_currentContext:null,getReportData:function(a,g){var c=this,f=g&&g.progressCallback||function(){},b=
h.mixin({},a);b.portalUrl=J.getPortalUrl(b.portalUrl);b.hierarchy||b.analysisAreas.some(function(a){if(a.geographies&&a.geographies[0].hierarchy)return b.hierarchy=a.geographies[0].hierarchy,!0});c.resetReportItemsCache&&d.resetCache();c._currentContext=b;b.analysisAreas=q.areasFromJson(b.analysisAreas);b.combinedAreasInfo=b.combinedAreasInfo&&q.combinedAreasInfoFromJson(b.combinedAreasInfo)||{};A.populateCombinedAreasInfo(b.combinedAreasInfo,b.analysisAreas);b.fieldData={runReportTaskIDs:null,metadata:{},
areaData:[],errors:[]};return l([m(d.tryFindReportIdByAlias(b),function(a){b.reportID=a||b.reportID}),this._discoverPortal(b),function(){return b.variables&&m(F.preprocessVariables(b.variables,b.portalUrl),function(a){b.variables=a})}()]).then(function(){return m(r.preprocessAreas(b,{analysisAreasLimit:c.analysisAreasLimit}),function(){f(.25);setTimeout(function(){c._onCreateReportStarted()});var a={initGE:n.initialize(),countryInfo:n.getCountryInfo(b.countryID),infographicOptions:c._infographicOptionsProvider.getInfographicOptions(b),
attachmentsStore:b.attachmentsProvider?D(b.attachmentsProvider):c._getAttachmentsStore(b.analysisAreas)};b.reportID?(a.reportObject=d.getCustomReportByID(b),a.templateJsonInfo=t.getTemplateJsonByID(b,c.cacheTemplates),a.runReportResult=k.runReportAndGetData(b)):b.variables&&(a.reportObject=d.getFakeCustomReportByContext(b),a.templateJsonInfo=t.createTemplateJsonFromVariables(b),a.runReportResult=k.runReportFromVariables(b));return l(a).then(function(a){var c=a.reportObject,g=a.infographicOptions,
e=a.attachmentsStore,d=a.templateJsonInfo.templateJson,h=a.templateJsonInfo.templateVariableProvider,l=a.runReportResult;f(.75);if(!d||!c||!b.fieldData)return null;k.applyRunReportAndGetDataResults(l,b);p.setCountry(a.countryInfo.country);p.setHierarchyID(b.hierarchy);p.setGeographiesModel(a.countryInfo.geographiesModels[p.getHierarchyID()]);return m(e&&k.populateReportDataFromAttachmentsStore(b,e),function(){f(1);d.theme||(d.theme=H.getReportThemeById(c.isGraphicReport?u.GRAPHIC:u.CLASSIC));return{isClassic:!c.isGraphicReport,
isMultiFeature:c.isMultiFeature&&1<b.analysisAreas.length,reportType:c.type,reportTitle:b.reportTitle||c.title,templateJson:d,reportObject:c,fieldData:b.fieldData,analysisAreas:b.analysisAreas,combinedAreasInfo:b.combinedAreasInfo,reverseAnalysisAreasOnMap:b.reverseAnalysisAreasOnMap,infographicOptions:g,attachmentsStore:e,geClient:n.getClient(),templateVariableProvider:h,customLogo:b.customLogo,config:{portalUrl:b.portalUrl,geoenrichmentUrl:b.geoenrichmentUrl,geometryServiceUrl:b.geometryServiceUrl,
printMapTaskUrl:b.printMapTaskUrl,countryID:b.countryID,hierarchy:b.hierarchy,reportID:b.reportID,variables:b.variables}}})})})})},_discoverPortal:function(a){var g=this;return E.getPortalInfo(a.portalUrl).then(function(c){a.geoenrichmentUrl=a.geoenrichmentUrl||c.portal.helperServices.geoenrichment.url;var f=w.id.findCredential(a.portalUrl),f=f&&f.token;n.setGeoenrichmentUrl(a.geoenrichmentUrl,f);g._infographicOptionsProvider.setServerUrl(a.geoenrichmentUrl,f);a.geometryServiceUrl=a.geometryServiceUrl||
c.portal.helperServices.geometry.url;I.setGeometryServiceUrl(a.geometryServiceUrl);a.printMapTaskUrl=a.printMapTaskUrl||c.portal.helperServices.printTask.url;G.setPrintMapTaskUrl(a.printMapTaskUrl)})},reportDataToSingleAreaReportData:function(a,g){var c=g.currentFeatureIndex||0,f=h.mixin({},a.fieldData);f.areaData=[f.areaData[c]];var b=[h.mixin({},a.analysisAreas[c])];r.removeGroupInfo(b);var d=a.infographicOptions&&this._infographicOptionsProvider.getInfographicOptionsFromJson(a.infographicOptions.toJsonAt(c)),
e=a.attachmentsStore;return{isClassic:a.isClassic,isMultiFeature:!1,reportType:a.reportType,reportTitle:g.reportTitle,templateJson:g.templateJson,reportObject:a.reportObject,fieldData:f,analysisAreas:b,combinedAreasInfo:null,reverseAnalysisAreasOnMap:!1,infographicOptions:d,attachmentsStore:e&&{getAttachments:function(){e.setCurrentAnalysisAreaIndex&&e.setCurrentAnalysisAreaIndex(c);return e.getAttachments()},getAttributes:function(){e.setCurrentAnalysisAreaIndex&&e.setCurrentAnalysisAreaIndex(c);
return e.getAttributes()},getNotes:function(){e.setCurrentAnalysisAreaIndex&&e.setCurrentAnalysisAreaIndex(c);return e.getNotes()}},geClient:a.geClient,templateVariableProvider:a.templateVariableProvider,config:a.config}},_getCurrentContext:function(){return this._currentContext},_onCreateReportStarted:function(){},enrichFieldData:function(a,d){return k.enrichFieldData(a,d)}})});