// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/renderers/ClassBreaksRenderer","dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/has ../kernel ../lang ../symbols/jsonUtils ./Renderer ../support/expressionUtils".split(" "),function(k,g,f,p,q,n,m,r,t){k=k(r,{declaredClass:"esri.renderer.ClassBreaksRenderer",constructor:function(a,b){this.breaks=[];this._symbols={};this.infos=[];this.isMaxInclusive=!0;if(a&&!a.declaredClass){b=a;this.attributeField=b.field;this.setValueExpression(b.valueExpression);this.valueExpressionTitle=b.valueExpressionTitle;
this.legendOptions=b.legendOptions;this.defaultSymbol=(a=b.defaultSymbol)&&(a.declaredClass?a:m.fromJson(a));this.backgroundFillSymbol=(a=b.backgroundFillSymbol)&&(a.declaredClass?a:m.fromJson(a));this._copy(["defaultLabel","classificationMethod:rest","normalizationType:rest","normalizationField","normalizationTotal"],b,this);var c=b.minValue;(a=b.classBreakInfos)&&a[0]&&n.isDefined(a[0].classMaxValue)&&g.forEach(a,function(a){var b=a.classMaxValue;a.minValue=c;c=a.maxValue=b},this);g.forEach(a,this._addBreakInfo,
this)}else this.defaultSymbol=a,this.attributeField=b},addBreak:function(a,b,c){a=f.isObject(a)?a:{minValue:a,maxValue:b,symbol:c};this._addBreakInfo(a)},removeBreak:function(a,b){var c,d=this.breaks,e,l=d.length,h=this._symbols;for(e=0;e<l;e++)if(c=d[e],c[0]==a&&c[1]==b){d.splice(e,1);delete h[a+"-"+b];this.infos.splice(e,1);break}},clearBreaks:function(){this.breaks=[];this._symbols={};this.infos=[]},getBreakIndex:function(a){var b=this.attributeField,c=a.attributes,d=this.breaks,e=d.length,l=this.isMaxInclusive;
if(this.valueExpression)a=this._getDataValue(a,this._cbInfo,null,this._cache.cbInfo);else if(f.isFunction(b))a=b(a);else{a=parseFloat(c[b]);var b=this.normalizationType,h;if(b)if(h=parseFloat(this.normalizationTotal),c=parseFloat(c[this.normalizationField]),"log"===b)a=Math.log(a)*Math.LOG10E;else if("percent-of-total"===b&&!isNaN(h))a=a/h*100;else if("field"===b){if(isNaN(a)||isNaN(c))return-1;a/=c}}if(null!=a&&!isNaN(a)&&"number"===typeof a)for(c=0;c<e;c++)if(b=d[c],b[0]<=a&&(l?a<=b[1]:a<b[1]))return c;
return-1},getBreakInfo:function(a){a=this.getBreakIndex(a);return-1!==a?this.infos[a]:null},getSymbol:function(a){return(a=this.breaks[this.getBreakIndex(a)])?this._symbols[a[0]+"-"+a[1]]:this.defaultSymbol},setMaxInclusive:function(a){this.isMaxInclusive=a},setValueExpression:function(a){this.valueExpression=a;this._cbInfo={valueExpression:a};this._cache.cbInfo=this._createCache(this._cbInfo)},getFieldsUsedInExpressions:function(){var a=this.inherited(arguments);this.valueExpression&&(a=a.concat(t.extractFieldNames(this.valueExpression)));
a.sort();return g.filter(a,function(b,c){return 0===c||a[c-1]!==b})},isContinuousRenderer:function(){var a=!1;if(this.infos&&1===this.infos.length)var b=this.attributeField,c=this.normalizationField,d=this.valueExpression,a=this.getVisualVariablesForType("colorInfo",!1)||[],e=this.getVisualVariablesForType("sizeInfo",!1)||[],l=this.getVisualVariablesForType("opacityInfo",!1)||[],a=a.concat(e).concat(l),a=g.some(a,function(a){return(a.field===b||a.valueExpression===d)&&a.normalizationField==c});return a},
_normalizationTypeEnums:[["field","esriNormalizeByField"],["log","esriNormalizeByLog"],["percent-of-total","esriNormalizeByPercentOfTotal"]],_classificationMethodEnums:[["natural-breaks","esriClassifyNaturalBreaks"],["equal-interval","esriClassifyEqualInterval"],["quantile","esriClassifyQuantile"],["standard-deviation","esriClassifyStandardDeviation"],["geometrical-interval","esriClassifyGeometricalInterval"],["defined-interval","esriClassifyDefinedInterval"]],_copy:function(a,b,c){g.forEach(a,function(a){var e=
a.split(":"),d,h,g;1<e.length&&(a=e[0],d=this["_"+a+"Enums"],"rest"===e[1]?(h="1",g="0"):"sdk"===e[1]&&(h="0",g="1"));e=b[a];if(void 0!==e&&(c[a]=e,d&&h)){var f,k=d.length;for(f=0;f<k;f++)if(d[f][h]===e){c[a]=d[f][g];break}}},this)},_addBreakInfo:function(a){var b=a.minValue,c=a.maxValue;this.breaks.push([b,c]);this.infos.push(a);var d=a.symbol;d&&!d.declaredClass&&(a.symbol=m.fromJson(d));this._symbols[b+"-"+c]=a.symbol},toJson:function(){var a=this.infos||[],b=n.fixJson,c=a[0]&&a[0].minValue,d=
this.backgroundFillSymbol,a=f.mixin(this.inherited(arguments),{type:"classBreaks",field:this.attributeField,valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,legendOptions:f.clone(this.legendOptions),defaultSymbol:this.defaultSymbol&&this.defaultSymbol.toJson(),backgroundFillSymbol:d&&d.toJson(),minValue:-Infinity===c?-Number.MAX_VALUE:c,classBreakInfos:g.map(a,function(a){a=f.mixin({},a);a.symbol=a.symbol&&a.symbol.toJson();a.classMaxValue=Infinity===a.maxValue?
Number.MAX_VALUE:a.maxValue;delete a.minValue;delete a.maxValue;return b(a)})});this._copy(["defaultLabel","classificationMethod:sdk","normalizationType:sdk","normalizationField","normalizationTotal"],this,a);a.hasOwnProperty("normalizationType")&&!a.normalizationType&&delete a.normalizationType;a.hasOwnProperty("classificationMethod")&&!a.classificationMethod&&delete a.classificationMethod;return b(a)}});p("extend-esri")&&f.setObject("renderer.ClassBreaksRenderer",k,q);return k});