// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var w=function(h,m){w=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,m){h.__proto__=m}||function(h,m){for(var q in m)m.hasOwnProperty(q)&&(h[q]=m[q])};return w(h,m)};return function(h,m){function q(){this.constructor=h}w(h,m);h.prototype=null===m?Object.create(m):(q.prototype=m.prototype,new q)}}();
define("esri/arcade/featureSetUtils","require exports ../request ./featureSetCollection ./featureset/sources/FeatureLayerDynamic ./featureset/sources/FeatureLayerDynamicMap ./featureset/sources/FeatureLayerMemoryMap ./featureset/sources/FeatureSetRelated ./featureset/support/cache ./featureset/support/shared ./polyfill/promiseUtils ../arcgis/Portal ../layers/FeatureLayer ./featureset/actions/GroupBy".split(" "),function(w,h,m,q,B,C,D,E,l,z,r,F,t){function A(c){if(null!==l.applicationCache){var b=
l.applicationCache.getLayerInfo(c);if(null!==b)return b}b=m({url:c,content:{f:"json"},callbackParamName:"callback",handleAs:"json"}).then(function(d){return d?(d.layers||(d.layers=[]),d.tables||(d.tables=[]),r.resolve(d)):r.resolve({layers:[],tables:[]})});null!==l.applicationCache&&(l.applicationCache.setLayerInfo(c,b),b=b.catch(function(d){l.applicationCache.clearLayerInfo(c);throw d;}));return b}function G(c){if(null!==l.applicationCache){var b=l.applicationCache.getLayerInfo(c);if(null!==b)return b}b=
m({url:c,content:{f:"json"},callbackParamName:"callback",handleAs:"json"}).then(function(d){return d?r.resolve(d):r.resolve(null)});null!==l.applicationCache&&(l.applicationCache.setLayerInfo(c,b),b=b.catch(function(d){l.applicationCache.clearLayerInfo(c);throw d;}));return b}function H(c,b){var d="QUERYDATAELEMTS:"+b.toString()+":"+c;if(null!==l.applicationCache){var e=l.applicationCache.getLayerInfo(d);if(null!==e)return e}c=m({url:c+"/queryDataElements",usePost:!0,handleAs:"json",content:{layers:JSON.stringify([b.toString()]),
f:"json"}}).then(function(a){if(a&&a.layerDataElements&&a.layerDataElements[0])return a.layerDataElements[0];throw Error("Not Found");});null!==l.applicationCache&&(l.applicationCache.setLayerInfo(d,c),c=c.catch(function(a){l.applicationCache.clearLayerInfo(d);throw a;}));return c}function u(c,b,d,e,a){void 0===d&&(d=null);void 0===e&&(e=!0);void 0===a&&(a=null);null===d&&(d=["*"]);return new B({url:c,outFields:d,spatialReference:b,includeGeometry:e,lrucache:a})}function v(c,b,d,e,a){void 0===d&&
(d=null);void 0===e&&(e=!0);void 0===a&&(a=null);return r.resolve(u(c,b,d,e,a))}function x(c,b,d,e,a){void 0===b&&(b=null);void 0===d&&(d=null);void 0===e&&(e=!0);void 0===a&&(a=null);if(!c.getMap())throw Error("FeatureSets can only be used once the layer is added to a Map");if(c.mode===t.MODE_SNAPSHOT&&!c.url)return new D({layer:c,spatialReference:b,outFields:d,includeGeometry:e});if(c.mode===t.MODE_SNAPSHOT||c.mode===t.MODE_ONDEMAND||c.mode===t.MODE_AUTO)return new C({layer:c,spatialReference:b,
outFields:d,includeGeometry:e,lrucache:a});throw Error("FeatureSets only support for Snapshot or OnDemand FeatureSet");}function I(c,b){var d=b.portalUrl+(b.portalUrl.match(/\/$/)?"":"/")+"content/items/"+c;return r.create(function(e,a){return m({url:d,content:{f:"json"},callbackParamName:"callback",load:function(a){e({item:a})},error:function(d){a(d)}})})}Object.defineProperty(h,"__esModule",{value:!0});h.initialiseMetaDataCache=function(){null===l.applicationCache&&(l.applicationCache=new l)};h.constructFeatureSetFromUrlRaw=
u;h.constructFeatureSetFromUrl=v;h.constructFeatureSet=x;var J=function(c){function b(d,e,a){void 0===e&&(e=null);void 0===a&&(a=null);var g=c.call(this)||this;g._map=d;g._overridespref=e;g.lrucache=a;g._instantLayers=[];return g}__extends(b,c);b.prototype.makeAndAddFeatureSet=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var g=x(d,this._overridespref,null===a?["*"]:a,e,this.lrucache);this._instantLayers.push({featureset:g,opitem:d,includeGeometry:e,outFields:JSON.stringify(a)});return g};
b.prototype.makeAndAddFeatureSetTable=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var g=u(d.url,this._overridespref,a,e,this.lrucache);this._instantLayers.push({featureset:g,opitem:{name:d.title,id:d.id},includeGeometry:e,outFields:JSON.stringify(a)});return g};b.prototype.featureSetByName=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var g=JSON.stringify(a),b=0;b<this._instantLayers.length;b++){var c=this._instantLayers[b];if(c.opitem.name===
d&&c.includeGeometry===e&&c.outFields===g)return this.resolvePromise(this._instantLayers[b].featureset)}g=null;b=0;for(c=this._map.graphicsLayerIds;b<c.length;b++){var k=this._map.getLayer(c[b]);if(k instanceof t&&k.name===d){g=k;break}}return g?this.resolvePromise(this.makeAndAddFeatureSet(g,e,a)):this._map.tables&&(g=this._map.tables.find(function(a){return a.title&&a.title===d||a.title&&a.title===d?!0:!1}))?this.resolvePromise(this.makeAndAddFeatureSetTable(g,e,a)):this.resolvePromise(null)};b.prototype.featureSetById=
function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=["*"]);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var b=JSON.stringify(a),c=0;c<this._instantLayers.length;c++){var f=this._instantLayers[c];if(f.opitem.id===d&&f.includeGeometry===e&&f.outFields===b)return this.resolvePromise(this._instantLayers[c].featureset)}b=null;c=0;for(f=this._map.graphicsLayerIds;c<f.length;c++){var k=this._map.getLayer(f[c]);if(k instanceof t&&k.id===d){b=k;break}}return b?this.resolvePromise(this.makeAndAddFeatureSet(b,
e,a)):this._map.tables&&(b=this._map.tables.find(function(a){return a.id&&a.id===d||a.id&&a.id===d?!0:!1}))?this.resolvePromise(this.makeAndAddFeatureSetTable(b,e,a)):this.resolvePromise(null)};return b}(q);h.createFeatureSetCollectionFromMap=function(c,b,d){void 0===d&&(d=null);return new J(c,b,d)};var K=function(c){function b(d,b,a){void 0===b&&(b=null);void 0===a&&(a=null);var e=c.call(this)||this;e._url=d;e._overridespref=b;e.lrucache=a;e.metadata=null;e._instantLayers=[];return e}__extends(b,
c);Object.defineProperty(b.prototype,"url",{get:function(){return this._url},enumerable:!0,configurable:!0});b.prototype._loadMetaData=function(){var d=this;return A(this._url).then(function(b){return d.metadata=b})};b.prototype.makeAndAddFeatureSet=function(d,b,a){void 0===b&&(b=!0);void 0===a&&(a=null);var e=x(d,this._overridespref,null===a?["*"]:a,b,this.lrucache);this._instantLayers.push({featureset:e,opitem:d,includeGeometry:b,outFields:JSON.stringify(a)});return e};b.prototype.load=function(){return this._loadMetaData()};
b.prototype.clone=function(){return new b(this._url,this._overridespref,this.lrucache)};b.prototype.featureSetByName=function(b,e,a){var d=this;void 0===e&&(e=!0);void 0===a&&(a=null);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var c=JSON.stringify(a),f=0;f<this._instantLayers.length;f++){var k=this._instantLayers[f];if(k.opitem.name===b&&k.includeGeometry===e&&k.outFields===c)return this.resolvePromise(this._instantLayers[f].featureset)}return this._loadMetaData().then(function(c){for(var g=
null,f=0,k=c.layers?c.layers:[];f<k.length;f++){var p=k[f];p.name===b&&(g=p)}if(!g)for(f=0,c=c.tables?c.tables:[];f<c.length;f++)p=c[f],p.name===b&&(g=p);return g?d.resolvePromise(u(d._url+"/"+g.id,d._overridespref,a,e,d.lrucache)):d.resolvePromise(null)})};b.prototype.featureSetById=function(b,c,a){var d=this;void 0===c&&(c=!0);void 0===a&&(a=["*"]);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();var e=JSON.stringify(a);b=null!==b&&void 0!==b?b.toString():"";for(var f=0;f<this._instantLayers.length;f++){var k=
this._instantLayers[f];if(k.opitem.id===b&&k.includeGeometry===c&&k.outFields===e)return this.resolvePromise(this._instantLayers[f].featureset)}return this._loadMetaData().then(function(e){for(var f=null,g=0,k=e.layers?e.layers:[];g<k.length;g++){var p=k[g];null!==p.id&&void 0!==p.id&&p.id.toString()===b&&(f=p)}if(!f)for(g=0,e=e.tables?e.tables:[];g<e.length;g++)p=e[g],null!==p.id&&void 0!==p.id&&p.id.toString()===b&&(f=p);return f?d.resolvePromise(u(d._url+"/"+f.id,d._overridespref,a,c,d.lrucache)):
d.resolvePromise(null)})};return b}(q);h.createFeatureSetCollectionFromService=function(c,b,d){void 0===d&&(d=null);return new K(c,b,d)};h.getPortal=function(c,b){return null===c?b:new F.Portal(c.field("url"))};h.constructFeatureSetFromPortalItem=function(c,b,d,e,a,g,h){return r.create(function(f,k){if(l.applicationCache){var m=l.applicationCache.getLayerInfo(c+":"+g.url);if(m){m.then(function(c){try{var g=v(z.extractServiceUrl(c.item.url)+"/"+b,d,e,a,h);f(g)}catch(y){k(y)}},function(a){k(a)});return}}m=
I(c,g);l.applicationCache&&l.applicationCache.setLayerInfo(c+":"+g.url,m);m.then(function(c){try{var g=v(z.extractServiceUrl(c.item.url)+"/"+b,d,e,a,h);f(g)}catch(y){k(y)}},function(a){l.applicationCache&&l.applicationCache.clearLayerInfo(c+":"+g.url);k(a)})})};h.constructFeatureSetFromRelationship=function(c,b,d,e,a,g,h){void 0===e&&(e=null);void 0===a&&(a=null);void 0===g&&(g=!0);void 0===h&&(h=null);var f=c.serviceUrl();if(!f)return null;f="/"===f.charAt(f.length-1)?f+b.relatedTableId.toString():
f+"/"+b.relatedTableId.toString();return v(f,e,a,g,h).then(function(f){return new E({layer:c,relatedLayer:f,relationship:b,objectId:d,spatialReference:e,outFields:a,includeGeometry:g,lrucache:h})})};h.constructAssociationMetaDataFeatureSetFromUrl=function(c,b){var d=[],e=null,a={},g=null;return A(c).then(function(h){if(h.controllerDatasetLayers&&void 0!==h.controllerDatasetLayers.utilityNetworkLayerId&&null!==h.controllerDatasetLayers.utilityNetworkLayerId){if(h.layers)for(var f=0,k=h.layers;f<k.length;f++){var l=
k[f];a[l.id]=l.name}if(h.tables)for(f=0,k=h.tables;f<k.length;f++)l=k[f],a[l.id]=l.name;var m=h.controllerDatasetLayers.utilityNetworkLayerId;return H(c,m).then(function(f){if(f){e=f;g={};e.dataElement.domainNetworks||(e.dataElement.domainNetworks=[]);f=0;for(var h=e.dataElement.domainNetworks;f<h.length;f++){for(var k=h[f],l=0,q=k.edgeSources?k.edgeSources:[];l<q.length;l++){var n=q[l],n={layerId:n.layerId,sourceId:n.sourceId,className:a[n.layerId]?a[n.layerId]:null};n.className&&(g[n.className]=
n)}l=0;for(k=k.junctionSources?k.junctionSources:[];l<k.length;l++)n=k[l],n={layerId:n.layerId,sourceId:n.sourceId,className:a[n.layerId]?a[n.layerId]:null},n.className&&(g[n.className]=n)}if(e.terminalConfigurations)for(f=0,h=e.dataElement.terminalConfigurations;f<h.length;f++)for(k=0,n=h[f].terminals;k<n.length;k++)l=n[k],d.push({terminalId:l.terminalId,terminalName:l.terminalName});return G(c+"/"+m).then(function(a){return a.systemLayers&&void 0!==a.systemLayers.associationsTableId&&null!==a.systemLayers.associationsTableId?
v(c+"/"+a.systemLayers.associationsTableId.toString(),b,"OBJECTID FROMNETWORKSOURCEID TONETWORKSOURCEID FROMGLOBALID TOGLOBALID TOTERMINALID FROMTERMINALID ASSOCIATIONTYPE ISCONTENTVISIBLE GLOBALID".split(" "),!1,null).then(function(a){return a.load()}).then(function(a){return{lkp:g,associations:a,terminals:d}}):{associations:null,lkp:null,terminals:[]}})}return{associations:null,lkp:null,terminals:[]}})}return{associations:null,lkp:null,terminals:[]}})}});