// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var l=function(q,t){l=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(q,l){q.__proto__=l}||function(q,l){for(var t in l)l.hasOwnProperty(t)&&(q[t]=l[t])};return l(q,t)};return function(q,t){function w(){this.constructor=q}l(q,t);q.prototype=null===t?Object.create(t):(w.prototype=t.prototype,new w)}}();
define("esri/arcade/featureset/actions/Adapted","require exports ../../../graphic ../../kernel ../support/FeatureSet ../support/IdSet ../support/shared ../support/sqlUtils ../../polyfill/promiseUtils ../../polyfill/sql/WhereClause ../../../SpatialReference".split(" "),function(l,q,t,w,y,x,v,r,u,z,C){Object.defineProperty(q,"__esModule",{value:!0});l=function(){function p(){this.sqlRewritable=!1}p.prototype.extractValue=function(d){return null};p.prototype.postInitialization=function(d,a){};p.prototype.rewriteSql=
function(d,a){return{rewritten:this.sqlRewritable,where:d}};return p}();q.AdaptedField=l;var A=function(p){function d(a){var b=p.call(this)||this;b.field=a;b.sqlRewritable=!0;return b}__extends(d,p);d.prototype.extractValue=function(a){return a.attributes[this.field.name]};d.prototype.rewriteSql=function(a,b){return{rewritten:this.sqlRewritable,where:a}};return d}(l);q.OriginalField=A;var B=function(p){function d(a,b,c){var f=p.call(this)||this;f.originalField=a;f.sqlRewritable=!0;f.field=v.cloneField(a);
f.field.name=b;f.field.alias=c;return f}__extends(d,p);d.prototype.rewriteSql=function(a,b){return{rewritten:this.sqlRewritable,where:r.reformulateWithoutField(a,this.field.name,this.originalField.name,b.getFieldsIndex())}};d.prototype.extractValue=function(a){return a.attributes[this.originalField.name]};return d}(l);q.FieldRename=B;var D=function(p){function d(a,b,c){var f=p.call(this)||this;f.field=a;f.codefield=b;f.lkp=c;f.reverseLkp={};for(var e in c)f.reverseLkp[c[e]]=e;f.sqlRewritable=!0;return f}
__extends(d,p);d.prototype.rewriteSql=function(a,b){var c=this.evaluateNodeToWhereClause(a.parseTree,v.FeatureServiceDatabaseType.Standardised,this.field.name,this.codefield instanceof z.WhereClause?r.toWhereClause(this.codefield,v.FeatureServiceDatabaseType.Standardised):this.codefield,a.parameters);return 0<=c.indexOf(d.BADNESS)?{rewritten:!1,where:a}:{rewritten:this.sqlRewritable,where:z.WhereClause.create(c,b._parent.getFieldsIndex())}};d.prototype.evaluateNodeToWhereClause=function(a,b,c,f,e){void 0===
c&&(c=null);void 0===f&&(f=null);var h;switch(a.type){case "interval":return r.convertIntervalToSql(this.evaluateNodeToWhereClause(a.value,b,c,f,e),a.qualifier,a.op,v.FeatureServiceDatabaseType.Standardised);case "case_expression":h=" CASE ";"simple"===a.format&&(h+=this.evaluateNodeToWhereClause(a.operand,b,c,d.BADNESS,e));for(f=0;f<a.clauses.length;f++)h+=" WHEN "+this.evaluateNodeToWhereClause(a.clauses[f].operand,b,c,d.BADNESS,e)+" THEN "+this.evaluateNodeToWhereClause(a.clauses[f].value,b,c,
d.BADNESS,e);null!==a.else&&(h+=" ELSE "+this.evaluateNodeToWhereClause(a.else,b,c,d.BADNESS,e));return h+" END ";case "param":c=e[a.value.toLowerCase()];if("string"===typeof c)return"'"+e[a.value.toLowerCase()].toString().replace(/'/g,"''")+"'";if(c instanceof Date)return r.makeDateString(c,b);if(c instanceof Array){a=[];for(f=0;f<c.length;f++)"string"===typeof c[f]?a.push("'"+c[f].toString().replace(/'/g,"''")+"'"):c[f]instanceof Date?a.push(r.makeDateString(c[f],b)):a.push(c[f].toString());return a}return c.toString();
case "expr_list":h=[];var k=0;for(a=a.value;k<a.length;k++)h.push(this.evaluateNodeToWhereClause(a[k],b,c,f,e));return h;case "unary_expr":return" ( NOT "+this.evaluateNodeToWhereClause(a.expr,b,c,d.BADNESS,e)+" ) ";case "binary_expr":switch(a.operator){case "AND":return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" AND "+this.evaluateNodeToWhereClause(a.right,b,c,f,e)+") ";case "OR":return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" OR "+this.evaluateNodeToWhereClause(a.right,b,c,
f,e)+") ";case "IS":if("null"!==a.right.type)throw Error("Unsupported RHS for IS");return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" IS NULL )";case "ISNOT":if("null"!==a.right.type)throw Error("Unsupported RHS for IS");return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" IS NOT NULL )";case "IN":h=[];if("expr_list"===a.right.type){if("column_ref"===a.left.type&&a.left.column.toUpperCase()===this.field.name.toUpperCase()){h=[];for(var k=!0,n=0,g=a.right.value;n<g.length;n++){var m=
g[n];if("string"===m.type)if(void 0!==this.lkp[m.value])h.push(this.lkp[m.value].toString());else{k=!1;break}else{k=!1;break}}if(k)return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" IN ("+h.join(",")+")) "}h=this.evaluateNodeToWhereClause(a.right,b,c,f,e);return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" IN ("+h.join(",")+")) "}h=this.evaluateNodeToWhereClause(a.right,b,c,f,e);return h instanceof Array?" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" IN ("+h.join(",")+")) ":
" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" IN ("+h+")) ";case "NOT IN":h=[];if("expr_list"===a.right.type){if("column_ref"===a.left.type&&a.left.column.toUpperCase()===this.field.name.toUpperCase()){h=[];k=!0;n=0;for(g=a.right.value;n<g.length;n++)if(m=g[n],"string"===m.type)if(void 0!==this.lkp[m.value])h.push(this.lkp[m.value].toString());else{k=!1;break}else{k=!1;break}if(k)return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" NOT IN ("+h.join(",")+")) "}h=this.evaluateNodeToWhereClause(a.right,
b,c,f,e);return" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" NOT IN ("+h.join(",")+")) "}h=this.evaluateNodeToWhereClause(a.right,b,c,f,e);return h instanceof Array?" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" NOT IN ("+h.join(",")+")) ":" ("+this.evaluateNodeToWhereClause(a.left,b,c,f,e)+" NOT IN ("+h+")) ";case "BETWEEN":return f=this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)," ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" BETWEEN "+f[0]+" AND "+f[1]+" ) ";
case "NOTBETWEEN":return f=this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)," ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" NOT BETWEEN "+f[0]+" AND "+f[1]+" ) ";case "LIKE":return""!==a.escape?" ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" LIKE "+this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)+" ESCAPE '"+a.escape+"') ":" ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" LIKE "+this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)+") ";case "NOT LIKE":return""!==
a.escape?" ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" NOT LIKE "+this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)+" ESCAPE '"+a.escape+"') ":" ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" NOT LIKE "+this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)+") ";case "\x3c\x3e":case "\x3d":if("column_ref"===a.left.type&&"string"===a.right.type){if(a.left.column.toUpperCase()===this.field.name.toUpperCase()&&void 0!==this.lkp[a.right.value.toString()])return" ("+
f+" "+a.operator+" "+this.lkp[a.right.value.toString()].toString()+") "}else if("column_ref"===a.right.type&&"string"===a.left.type&&a.right.column.toUpperCase()===this.field.name.toUpperCase())return" ("+this.lkp[a.right.value.toString()].toString()+" "+a.operator+" "+f+") ";return" ("+this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" "+a.operator+" "+this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)+") ";case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "*":case "-":case "+":case "/":return" ("+
this.evaluateNodeToWhereClause(a.left,b,c,d.BADNESS,e)+" "+a.operator+" "+this.evaluateNodeToWhereClause(a.right,b,c,d.BADNESS,e)+") "}throw Error("Not Supported Operator "+a.operator);case "null":return"null";case "bool":return!0===a.value?"1":"0";case "string":return"'"+a.value.toString().replace(/'/g,"''")+"'";case "timestamp":return r.makeDateString(a.value,b);case "date":return r.makeDateString(a.value,b);case "number":return a.value.toString();case "column_ref":return"CURRENT_DATE"===a.column.toUpperCase()?
r.makeToday(!0,b):"CURRENT_TIMESTAMP"===a.column.toUpperCase()?r.makeToday(!1,b):c&&c.toLowerCase()===a.column.toLowerCase()?"("+f+")":a.column;case "function":return e=this.evaluateNodeToWhereClause(a.args,b,c,d.BADNESS,e),r.translateFunctionToDatabaseSpecific(a.name,e,b)}throw Error("Unsupported sql syntax "+a.type);};d.prototype.extractValue=function(a){return this.codefield instanceof z.WhereClause?this.reverseLkp[this.codefield.calculateValueCompiled(a)]:a.attributes[this.codefield]};d.BADNESS=
"_!!!_BAD_LKP_!!!!";return d}(l);q.StringToCodeAdapted=D;l=function(p){function d(a,b){var c=p.call(this)||this;c.field=a;c.sql=b;return c}__extends(d,p);d.prototype.rewriteSql=function(a,b){return{rewritten:!0,where:r.reformulateWithoutField(a,this.field.name,r.toWhereClause(this.sql,v.FeatureServiceDatabaseType.Standardised),b.getFieldsIndex())}};d.prototype.postInitialization=function(a,b){};d.prototype.extractValue=function(a){return this.sql.calculateValueCompiled(a)};return d}(l);q.SqlExpressionAdapted=
l;y=function(p){function d(a){var b=p.call(this,a)||this;b._calcFunc=null;b.declaredClass="esri.arcade.featureset.actions.Adapted";b.adaptedFields=null;b._extraFilter=null;b._extraFilter=a.extraFilter;b._parent=a.parentfeatureset;b._maxProcessing=30;b.adaptedFields=a.adaptedFields;return b}__extends(d,p);d.findField=function(a,b){for(var c=0;c<a.length;c++){var f=a[c];if(f.name.toLowerCase()===b.toString().toLowerCase())return f}return null};d.prototype._initialiseFeatureSet=function(){null!==this._parent?
(this.geometryType=this._parent.geometryType,this.objectIdField=this._parent.objectIdField,this.spatialReference=this._parent.spatialReference,this.hasM=this._parent.hasM,this.hasZ=this._parent.hasZ,this.typeIdField=this._parent.typeIdField,this.types=this._parent.types):(this.spatialReference=new C({wkid:4326}),this.objectIdField="",this.geometryType=v.layerGeometryEsriConstants.point,this.typeIdField="",this.types=null);this.fields=[];for(var a=0,b=this.adaptedFields;a<b.length;a++){var c=b[a];
c.postInitialization(this,this._parent);this.fields.push(c.field)}};d.prototype._getSet=function(a){var b=this;return null===this._wset?this._ensureLoaded().then(function(){return b._extraFilter?b._getFilteredSet("",null,null,null,a):b._parent._getSet(a)}).then(function(c){b._checkCancelled(a);b._wset=new x(c._candidates.slice(0),c._known.slice(0),c._ordered,b._clonePageDefinition(c.pagesDefinition));return b._wset}):u.resolve(this._wset)};d.prototype._isInFeatureSet=function(a){return this._parent._isInFeatureSet(a)};
d.prototype._getFeatures=function(a,b,c,f){var e=this,d=[];-1!==b&&void 0===this._featureCache[b]&&d.push(b);var k=this._maxQueryRate();if(!0===this._checkIfNeedToExpandKnownPage(a,k,f))return this._expandPagedSet(a,k,0,0,f).then(function(d){return e._getFeatures(a,b,c,f)});for(var n=0,g=a._lastFetchedIndex;g<a._known.length&&!(n++,n<=c&&(a._lastFetchedIndex+=1),void 0===this._featureCache[a._known[g]]&&(a._known[g]!==b&&d.push(a._known[g]),d.length>=k-1));g++);if(0===d.length)return u.resolve("success");
a=new x([],d,a._ordered,null);var m=Math.min(d.length,c);return this._parent._getFeatures(a,-1,m,f).then(function(a){e._checkCancelled(f);a=[];for(var b=0;b<m;b++){var c=e._parent._featureFromCache(d[b]);void 0!==c&&a.push({geometry:c.geometry,attributes:c.attributes,id:d[b]})}for(b=0;b<a.length;b++){for(var c=a[b],h=[],g=0,k=e.adaptedFields;g<k.length;g++){var n=k[g];h[n.field.name]=n.extractValue(c)}e._featureCache[c.id]=new t({attributes:h,geometry:w.cloneGeometry(c.geometry)})}return"success"})};
d.prototype._fetchAndRefineFeatures=function(a,b,c){return u.reject(Error("Fetch and Refine should not be called in this featureset"))};d.prototype._getFilteredSet=function(a,b,c,f,e){var d=this,k=!1,n=this.reformulateWithoutAdaptions(c),k=n.cannot;c=n.where;var g=!1;if(null!==f){for(var g=!0,n=[],m=0,p=this.adaptedFields;m<p.length;m++){var l=p[m];if(!(l instanceof A)&&!0===f.scanForField(l.field.name))if(l instanceof B)n.push({field:l.field.name,newfield:l.originalField.name});else{f=null;g=!1;
break}}f&&0<n.length&&(f=f.replaceFields(n))}null!==c?null!==this._extraFilter&&(c=r.combine(this._extraFilter,c)):c=this._extraFilter;return this._ensureLoaded().then(function(){return d._parent._getFilteredSet(a,b,c,f,e)}).then(function(a){d._checkCancelled(e);return!0===k?new x(a._candidates.slice(0).concat(a._known.slice(0)),[],!0===g?a._ordered:!1,d._clonePageDefinition(a.pagesDefinition)):new x(a._candidates.slice(0),a._known.slice(0),!0===g?a._ordered:!1,d._clonePageDefinition(a.pagesDefinition))})};
d.prototype.reformulateWithoutAdaptions=function(a){var b={cannot:!1,where:a};if(null!==a)for(var c=0,f=this.adaptedFields;c<f.length;c++){var e=f[c];if(!0===r.scanForField(a,e.field.name))if(e=e.rewriteSql(a,this),!0===e.rewritten)b.where=e.where;else{b.cannot=!0;b.where=null;break}}return b};d.prototype._stat=function(a,b,c,f,e,d,k){var h=this,g=!1,m=this.reformulateWithoutAdaptions(b),g=m.cannot;b=m.where;m=this.reformulateWithoutAdaptions(e);g=g||m.cannot;e=m.where;null!==e?null!==this._extraFilter&&
(e=r.combine(this._extraFilter,e)):e=this._extraFilter;return!0===g?null===e&&""===c&&null===f?this._manualStat(a,b,d,k):u.resolve({calculated:!1}):this._parent._stat(a,b,c,f,e,d,k).then(function(g){return!1===g.calculated?null===e&&""===c&&null===f?h._manualStat(a,b,d,k):{calculated:!1}:g})};d.prototype._canDoAggregates=function(a,b,c,f,e){if(null===this._parent)return u.resolve(!1);for(var d=0;d<a.length;d++)for(var k=0,n=this.adaptedFields;k<n.length;k++){var g=n[k];if(a[d].toLowerCase()===g.field.name.toLowerCase()&&
!(g instanceof A))return u.resolve(!1)}k=[];for(d=0;d<b.length;d++){g=b[d];if(null!==g.workingexpr){n=this.reformulateWithoutAdaptions(g.workingexpr);if(n.cannot)return u.resolve(!1);g=g.clone();g.workingexpr=n.where}k.push(g)}b=this.reformulateWithoutAdaptions(e);if(b.cannot)return u.resolve(!1);e=b.where;null!==e?null!==this._extraFilter&&(e=r.combine(this._extraFilter,e)):e=this._extraFilter;return this._parent._canDoAggregates(a,k,c,f,e)};d.prototype._getAggregatePagesDataSourceDefinition=function(a,
b,c,d,e,h,k){if(null===this._parent)return u.reject(Error("Should never be called"));for(var f=[],g=0;g<b.length;g++){var m=b[g];if(null!==m.workingexpr){var l=this.reformulateWithoutAdaptions(m.workingexpr);if(l.cannot)return u.reject(Error("Should never be called"));m=m.clone();m.workingexpr=l.where}f.push(m)}b=this.reformulateWithoutAdaptions(e);if(b.cannot)return u.reject(Error("Should never be called"));e=b.where;null!==e?null!==this._extraFilter&&(e=r.combine(this._extraFilter,e)):e=this._extraFilter;
return this._parent._getAggregatePagesDataSourceDefinition(a,f,c,d,e,h,k)};return d}(y);q.AdaptedFeatureSet=y});