// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var u=function(h,l){u=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(l,m){l.__proto__=m}||function(l,m){for(var h in m)m.hasOwnProperty(h)&&(l[h]=m[h])};return u(h,l)};return function(h,l){function v(){this.constructor=h}u(h,l);h.prototype=null===l?Object.create(l):(v.prototype=l.prototype,new v)}}();
define("esri/arcade/featureset/actions/GroupBy","require exports ../../../graphic ../../languageUtils ./Adapted ./AttributeFilter ./OrderBy ../support/FeatureSet ../support/IdSet ../support/OrderbyClause ../support/sha ../support/shared ../support/sqlUtils ../support/sqlUtils ../support/stats ../support/StatsField ../../polyfill/promiseUtils ../../polyfill/sql/WhereClause ../../../SpatialReference ../../../layers/Field ../../polyfill/sql/FieldsIndex".split(" "),function(u,h,l,v,m,D,E,A,w,F,G,q,x,
n,r,B,k,t,H,y,I){function J(l){if(!l)return"COUNT";switch(l.toLowerCase()){case "max":return"MAX";case "var":case "variance":return"VAR";case "avg":case "average":case "mean":return"AVG";case "min":return"MIN";case "sum":return"SUM";case "stdev":case "stddev":return"STDDEV"}return"COUNT"}var C=function(h){function g(b){var a=h.call(this,b)||this;a._decodedStatsfield=[];a._decodedGroupbyfield=[];a._candosimplegroupby=!0;a.phsyicalgroupbyfields=[];a.objectIdField="ROW__ID";a._internalObjectIdField=
"ROW__ID";a._adaptedFields=[];a.declaredClass="esri.arcade.featureset.actions.Aggregate";a._uniqueIds=1;a._maxQuery=10;a._maxProcessing=10;a._parent=b.parentfeatureset;a._config=b;return a}__extends(g,h);g.prototype.isTable=function(){return!0};g.prototype._getSet=function(b){var a=this;return null===this._wset?this._getFilteredSet("",null,null,null,b).then(function(b){a._wset=b;return a._wset}):k.resolve(this._wset)};g.prototype._isInFeatureSet=function(b){return q.IdState.InFeatureSet};g.prototype.nextUniqueName=
function(b){for(;1===b["T"+this._uniqueIds.toString()];)this._uniqueIds++;var a="T"+this._uniqueIds.toString();b[a]=1;return a};g.prototype.convertToEsriFieldType=function(b){return b};g.prototype._initialiseFeatureSet=function(){var b={},a=!1,e=1,c=this._parent?this._parent.getFieldsIndex():new I([]);for(this.objectIdField="ROW__ID";!1===a;){for(var f=!1,d=0;d<this._config.groupbyfields.length;d++)if(this._config.groupbyfields[d].name.toLowerCase()===this.objectIdField.toLowerCase()){f=!0;break}if(!1===
f)for(d=0;d<this._config.statsfields.length;d++)if(this._config.statsfields[d].name.toLowerCase()===this.objectIdField.toLowerCase()){f=!0;break}!1===f?a=!0:(this.objectIdField="ROW__ID"+e.toString(),e++)}a=0;for(e=this._config.statsfields;a<e.length;a++)d=e[a],f=new B,f.field=d.name,f.tofieldname=d.name,f.workingexpr=d.expression instanceof t.WhereClause?d.expression:t.WhereClause.create(d.expression,c),f.typeofstat=J(d.statistic),this._decodedStatsfield.push(f);this._decodedGroupbyfield=[];a=0;
for(e=this._config.groupbyfields;a<e.length;a++)d=e[a],d={name:d.name,singlefield:null,tofieldname:d.name,expression:d.expression instanceof t.WhereClause?d.expression:t.WhereClause.create(d.expression,c)},this._decodedGroupbyfield.push(d);if(null!==this._parent){this.geometryType=this._parent.geometryType;this.spatialReference=this._parent.spatialReference;this.hasM=this._parent.hasM;this.hasZ=this._parent.hasZ;this.typeIdField="";c=0;for(a=this._parent.fields;c<a.length;c++)d=a[c],b[d.name.toUpperCase()]=
1;this.types=null}else this.geometryType=q.layerGeometryEsriConstants.point,this.typeIdField="",this.types=null,this.spatialReference=new H({wkid:4326});this.fields=[];c=new B;c.field=this.nextUniqueName(b);c.tofieldname=this.objectIdField;c.workingexpr=t.WhereClause.create(this._parent.objectIdField,this._parent.getFieldsIndex());c.typeofstat="MIN";this._decodedStatsfield.push(c);d=0;for(e=this._decodedGroupbyfield;d<e.length;d++){a=e[d];c=new y;a.name=this.nextUniqueName(b);c.name=a.tofieldname;
c.alias=c.name;if(x.isSingleField(a.expression)){f=this._parent.getField(n.toWhereClause(a.expression,q.FeatureServiceDatabaseType.Standardised));if(!f)throw Error("Field is not present for Aggregation");a.name=f.name;a.singlefield=f.name;this.phsyicalgroupbyfields.push(f.name);c.type=f.type}else c.type=this.convertToEsriFieldType(n.predictType(a.expression,this._parent.fields)),f=new y,f.name=a.name,f.alias=f.name,this.phsyicalgroupbyfields.push(a.name),this._adaptedFields.push(new m.SqlExpressionAdapted(f,
a.expression)),this._candosimplegroupby=!1;this.fields.push(c)}if(0<this._adaptedFields.length)for(c=0,a=this._parent.fields;c<a.length;c++)d=a[c],this._adaptedFields.push(new m.OriginalField(d));for(d=0;d<this._decodedStatsfield.length;d++){c=new y;f=null;a=this._decodedStatsfield[d];a.field=this.nextUniqueName(b);a.tofieldname===this.objectIdField&&(this._internalObjectIdField=a.field);c.name=a.tofieldname;c.alias=c.name;a=null!==a.workingexpr?x.isSingleField(a.workingexpr)?n.toWhereClause(a.workingexpr,
q.FeatureServiceDatabaseType.Standardised):"":"";switch(this._decodedStatsfield[d].typeofstat){case "SUM":if(""!==a){f=this._parent.getField(a);if(!f)throw Error("Field is not present for Aggregation");c.type=f.type}else c.type="double";break;case "MIN":case "MAX":if(""!==a){f=this._parent.getField(a);if(!f)throw Error("Field is not present for Aggregation");c.type=f.type}else c.type="double";break;case "COUNT":c.type="integer";break;case "STDDEV":case "VAR":case "AVG":if(""!==a&&(f=this._parent.getField(a),
!f))throw Error("Field is not present for Aggregation");c.type="double"}this.fields.push(c)}};g.prototype._canDoAggregates=function(b,a,e,c,f){return k.resolve(!1)};g.prototype._getFeatures=function(b,a,e,c){var f=this,d=[];-1!==a&&void 0===this._featureCache[a]&&d.push(a);d=this._maxQuery;return!0===this._checkIfNeedToExpandKnownPage(b,d,c)?this._expandPagedSet(b,d,0,0,c).then(function(d){return f._getFeatures(b,a,e,c)}):k.resolve("success")};g.prototype._getFilteredSet=function(b,a,e,c,f){var d=
this;if(""!==b)return k.resolve(new w([],[],!0,null));var g=null,p=!1,z=!1;return this._ensureLoaded().then(function(){if(null!==e)for(var a=0;a<d._decodedStatsfield.length;a++)if(!0===x.scanForField(e,d._decodedStatsfield[a].tofieldname)){z=!0;e=null;break}if(null!==c){p=!0;for(a=0;a<d._decodedStatsfield.length;a++)if(!0===c.scanForField(d._decodedStatsfield[a].tofieldname)){c=null;p=!1;break}if(null!==c)for(var a=0,b=d._decodedGroupbyfield;a<b.length;a++){var f=b[a];if(null===f.singlefield&&!0===
c.scanForField(f.tofieldname)){c=null;p=!1;break}}}return!1===d._candosimplegroupby?k.resolve(!1):d._parent._canDoAggregates(d.phsyicalgroupbyfields,d._decodedStatsfield,"",null,null)}).then(function(a){if(a){a=null;e&&(a=d._reformulateWhereClauseWithoutGroupByFields(e));var b=null;c&&(b=d._reformulateOrderClauseWithoutGroupByFields(c));return d._parent._getAggregatePagesDataSourceDefinition(d.phsyicalgroupbyfields,d._decodedStatsfield,"",null,a,b,d._internalObjectIdField).then(function(a){d._checkCancelled(f);
return g=!0===z?new w(a._candidates.slice(0).concat(a._known.slice(0)),[],!0===p?a._ordered:!1,d._clonePageDefinition(a.pagesDefinition)):new w(a._candidates.slice(0),a._known.slice(0),!0===p?a._ordered:!1,d._clonePageDefinition(a.pagesDefinition))})}a=d._parent;0<d._adaptedFields.length&&(a=new m.AdaptedFeatureSet({parentfeatureset:d._parent,adaptedFields:d._adaptedFields,extraFilter:null}));!0!==z&&null!==e&&(b=null,e&&(b=d._reformulateWhereClauseWithoutGroupByFields(e)),a=new D({parentfeatureset:a,
whereclause:b}));return g=new w(["GETPAGES"],[],!1,{aggregatefeaturesetpagedefinition:!0,resultOffset:0,resultRecordCount:d._maxQuery,internal:{fullyResolved:!1,workingItem:null,type:"manual",iterator:null,set:[],subfeatureset:new E({parentfeatureset:a,orderbyclause:new F(d.phsyicalgroupbyfields.join(",")+","+d._parent.objectIdField+" ASC")})}})})};g.prototype._reformulateWhereClauseWithoutStatsFields=function(b){for(var a=0,e=this._decodedStatsfield;a<e.length;a++){var c=e[a];b=n.reformulateWithoutField(b,
c.tofieldname,n.toWhereClause(c.workingexpr,q.FeatureServiceDatabaseType.Standardised),this._parent.getFieldsIndex())}return b};g.prototype._reformulateWhereClauseWithoutGroupByFields=function(b){for(var a=0,e=this._decodedGroupbyfield;a<e.length;a++){var c=e[a];c.tofieldname!==c.name&&(b=n.reformulateWithoutField(b,c.tofieldname,n.toWhereClause(c.expression,q.FeatureServiceDatabaseType.Standardised),this._parent.getFieldsIndex()))}return b};g.prototype._reformulateOrderClauseWithoutGroupByFields=
function(b){for(var a=[],e=0,c=this._decodedGroupbyfield;e<c.length;e++){var f=c[e];f.tofieldname!==f.name&&a.push({field:f.tofieldname,newfield:f.name})}return 0<a.length?b.replaceFields(a):b};g.prototype._clonePageDefinition=function(b){return null===b?null:!0===b.aggregatefeaturesetpagedefinition?{aggregatefeaturesetpagedefinition:!0,resultRecordCount:b.resultRecordCount,resultOffset:b.resultOffset,internal:b.internal}:this._parent._clonePageDefinition(b)};g.prototype._refineSetBlock=function(b,
a,e){var c=this;try{if(!0===this._checkIfNeedToExpandCandidatePage(b,this._maxQuery,e))return this._expandPagedSet(b,this._maxQuery,0,0,e).then(function(f){return c._refineSetBlock(b,a,e)});this._checkCancelled(e);this._refineKnowns(b,a);return k.resolve(b)}catch(f){return k.reject(f)}};g.prototype._expandPagedSet=function(b,a,e,c,f){return this._expandPagedSetFeatureSet(b,a,e,c,f)};g.prototype._getPhysicalPage=function(b,a,e){var c=this;return!0===b.pagesDefinition.aggregatefeaturesetpagedefinition?
k.create(function(a,d){c._sequentialGetPhysicalItem(b,b.pagesDefinition.resultRecordCount,e,[]).then(function(c){a(c)},d)}):this._getAgregagtePhysicalPage(b,a,e).then(function(a){for(var b=0;b<a.length;b++){for(var f=a[b],e={geometry:f.geometry,attributes:{}},g=0,h=c._decodedGroupbyfield;g<h.length;g++){var k=h[g];e.attributes[k.tofieldname]=f.attributes[k.name]}g=0;for(h=c._decodedStatsfield;g<h.length;g++)k=h[g],e.attributes[k.tofieldname]=f.attributes[k.field];c._featureCache[e.attributes[c.objectIdField]]=
new l(e)}return a.length})};g.prototype._sequentialGetPhysicalItem=function(b,a,e,c){var f=this;return k.create(function(d,g){null===b.pagesDefinition.internal.iterator&&(b.pagesDefinition.internal.iterator=b.pagesDefinition.internal.subfeatureset.iterator(e));!0===b.pagesDefinition.internal.fullyResolved?d(c.length):0===a?d(c.length):f._nextAggregateItem(b,a,e,c,function(g){null===g?d(c.length):(--a,d(f._sequentialGetPhysicalItem(b,a,e,c)))},g)})};g.prototype._nextAggregateItem=function(b,a,e,c,
f,d){var g=this;try{v.tick(b.pagesDefinition.internal.iterator.next()).then(function(h){if(null===h){if(null!==b.pagesDefinition.internal.workingItem){var k=g._calculateAndAppendAggregateItem(b.pagesDefinition.internal.workingItem);c.push(k);b.pagesDefinition.internal.workingItem=null;b.pagesDefinition.internal.set.push(k.attributes[g.objectIdField])}b.pagesDefinition.internal.fullyResolved=!0;f(null)}else{var l=g._generateAggregateHash(h);if(null===b.pagesDefinition.internal.workingItem)b.pagesDefinition.internal.workingItem=
{features:[h],id:l};else{if(l!==b.pagesDefinition.internal.workingItem.id){k=g._calculateAndAppendAggregateItem(b.pagesDefinition.internal.workingItem);c.push(k);b.pagesDefinition.internal.workingItem=null;b.pagesDefinition.internal.set.push(k.attributes[g.objectIdField]);--a;b.pagesDefinition.internal.workingItem={features:[h],id:l};f(k);return}b.pagesDefinition.internal.workingItem.features.push(h)}g._nextAggregateItem(b,a,e,c,f,d)}},d)}catch(p){d(p)}};g.prototype._calculateFieldStat=function(b,
a,e){for(var c=[],f=0;f<b.features.length;f++)if(null!==a.workingexpr){var d=a.workingexpr.calculateValue(b.features[f]);null!==d&&c.push(d)}else c.push(null);switch(a.typeofstat){case "MIN":e.attributes[a.tofieldname]=r.calculateStat("min",c,-1);break;case "MAX":e.attributes[a.tofieldname]=r.calculateStat("max",c,-1);break;case "SUM":e.attributes[a.tofieldname]=r.calculateStat("sum",c,-1);break;case "COUNT":e.attributes[a.tofieldname]=c.length;break;case "VAR":e.attributes[a.tofieldname]=r.calculateStat("var",
c,-1);break;case "STDDEV":e.attributes[a.tofieldname]=r.calculateStat("stddev",c,-1);break;case "AVG":e.attributes[a.tofieldname]=r.calculateStat("avg",c,-1)}return!0};g.prototype._calculateAndAppendAggregateItem=function(b){for(var a={attributes:{},geometry:null},e=0,c=this._decodedGroupbyfield;e<c.length;e++){var f=c[e],d=f.singlefield?b.features[0].attributes[f.singlefield]:f.expression.calculateValue(b.features[0]);a.attributes[f.tofieldname]=d}e=0;for(c=this._decodedStatsfield;e<c.length;e++)this._calculateFieldStat(b,
c[e],a);e=[];for(c=0;c<this._decodedStatsfield.length;c++)e.push(this._calculateFieldStat(b,this._decodedStatsfield[c],a));this._featureCache[a.attributes[this.objectIdField]]=new l({attributes:a.attributes,geometry:a.geometry});return a};g.prototype._generateAggregateHash=function(b){for(var a="",e=0,c=this._decodedGroupbyfield;e<c.length;e++)var f=c[e],f=f.singlefield?b.attributes[f.singlefield]:f.expression.calculateValue(b),a=null===f||void 0===f?a+":":a+(":"+f.toString());return(new G(a,"TEXT")).getHash("SHA-1",
"B64")};g.prototype._stat=function(b,a,e,c,f,d,g){return k.resolve({calculated:!1})};g.prototype.getFeatureByObjectId=function(b,a){return k.resolve(null)};return g}(A);A._featuresetFunctions.groupby=function(h,g){return new C({parentfeatureset:this,groupbyfields:h,statsfields:g})};return C});