// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainerStack/utils/ComparisonSectionProcessor","dojo/_base/lang ../../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../../sections/sectionUtils/SectionJsonUtil ../../supportClasses/tableJson/TableJsonUtil ../../infographics/InfographicTypes ../../infographics/utils/InfographicJsonConversionUtil ../../infographics/utils/InfographicLayoutResizer ../../infographics/utils/InfographicVariableLayoutUtil ../../infographics/utils/InfographicThemeUtil ../../grid/coreUtils/GridDataUtil".split(" "),
function(t,l,k,v,q,w,x,u,y,z){function A(a){a=t.mixin({},a.getComparisonSettings());a.preserveRelativeSize=!1;a.equalizeVariableText=a.splitPanels;a.equalizeDescriptionText=a.splitPanels;(a.equalizeLayout=a.splitPanels)?(a.spaceOutFactor=null,a.scale=a.scaleSplit):(a.spaceOutFactor=1/a.scale,a.scale=null);return a}var g={getProcessor:function(a){return function(b){var c=A(a);b=g._filterSectionJsons(b,a.viewModel);b=b.map(function(a){var b=k.getSectionJsonInfographic(a);return b&&b.type===q.STATIC?
t.clone(a):a});c.spaceOutFactor&&1!==c.spaceOutFactor&&g._spaceOutSectionJsons(b,c);c.splitPanels&&(b=g._splitSectionJsons(b));b=g._equalizeSectionJsons(b,c,a.viewModel);c.hideBackgroundImage&&(b=g._hideBackgroundElements(b));c.scale&&1!==c.scale&&(b=g._zoomOutSectionJsons(b,c));return b}},_filterSectionJsons:function(a,b){return a.filter(function(a){if(a.stack&&a.stack.some(function(a){return a.isMap}))return!0;var c=!1;l.processSectionFieldInfos(a,function(a){c=g._isComparableFieldInfo(a,b)||c});
return c})},_isComparableFieldInfo:function(a,b){return a.isChart?!0:a.isInfographic?a.infographicJson.type===q.ATTACHMENTS?!1:a.infographicJson.type===q.AREA_DETAILS?b.dynamicReportInfo.attachmentsStore&&b.dynamicReportInfo.attachmentsStore.supportsMultipleAreas:!0:a.isMap||a.hasVariable?!0:!1},_spaceOutSectionJsons:function(a,b){a.forEach(function(a){var c=k.getSectionJsonInfographic(a);if(c&&c.type===q.STATIC&&!(2>c.variableTables.length)){var d=b.spaceOutFactor,e=c.style.width,f=e*d,n=(f-e)/2;
c.header&&(c.header.data.columns[0].style.width="100%",c.header.style.left=-n,c.header.style.width=f);c.variableTables.forEach(function(a){a.style.left=a.style.left*d-n+(a.style.width*d-a.style.width)/2});c=l.getParentBox(a);g._applyParentBoxWidth(a,c.w*d)}})},_splitSectionJsons:function(a){var b=[];a.forEach(function(a){var c=k.getSectionJsonInfographic(a);if(c&&c.type===q.STATIC){var d=c.variableTables;if(c.header){var e=c.header;if(e.data.data[0][e.data.columns[0].field]||e.data.data[0].fieldInfos&&
e.data.data[0].fieldInfos[e.data.columns[0].field]){e=t.clone(a);c=k.getSectionJsonInfographic(e);c.variableTables=[];var c=v.calcTableBox(c.header),f=l.getParentBox(e);f.y+=c.y;f.h=c.h;l.setParentBox(e,f);b.push(e)}}d.forEach(function(c,f){c=t.clone(a);var n=k.getSectionJsonInfographicTable(c),e=k.getSectionJsonInfographic(c);delete e.header;e.variableTables=[e.variableTables[f]];var p=e.variableTables[0];f=w.variableTableToNormalTables(p);e=k.wrapInDetailsSectionJson(f.tableJsons);e.style=p.style;
var d=k.calcSectionJsonBox(e),e=p.variable.style.horizontalAlign||"left";f=Math.min(1.75,(d.contentW+(f.isVariableInShape||"left"===e?2*p.variable.style.width:p.variable.style.width))/d.contentW);z.isNumericVariableFieldCell(p.variable.fieldInfo)||(f=1);var h=n.style.left+(d.x+d.contentLeft)-d.contentW*(f-1)/2,g=n.style.top+(d.y+d.contentTop);n.style.left=0;n.style.top=0;p.style.left=d.contentW*(f-1)/2;p.style.top=0;x.VARIABLE_TABLE_ELEMENTS.forEach(function(a){p[a]&&(p[a].style.left-=d.contentLeft,
p[a].style.top-=d.contentTop)});c.stack.filter(function(a){return a!==n}).forEach(function(a){a.style.left-=h;a.style.top-=g});e=l.getParentBox(c);e.x+=h;e.y+=g;e.w=d.contentW*f;e.h=d.contentH;l.setParentBox(c,e);b.push(c)})}else b.push(a)});return b},_zoomOutSectionJsons:function(a,b){return a.map(function(a){var c=k.getSectionJsonInfographic(a);c&&c.type===q.STATIC&&(c=l.getParentBox(a),g._applyParentBoxWidth(a,c.w/b.scale));return a})},_equalizeSectionJsons:function(a,b,c){var h=[],d=[];a=a.map(function(a){var c=
k.getSectionJsonInfographic(a);c&&c.type===q.STATIC&&(b.splitPanels?c.header?h.push(a):d.push(a):d.push(a));return a});b.preserveRelativeSize&&(g._equalizeBox(h),g._equalizeBox(d));b.equalizeVariableText&&(g._equalizeVariableAndHeaderText(h,c,!0),g._equalizeVariableAndHeaderText(d,c,!1));b.equalizeDescriptionText&&g._equalizeDescriptionText(d,c);b.equalizeIcons&&g._equalizeIcons(d,c);b.equalizeLayout&&g._equalizeLayout(d,c);return a},_equalizeBox:function(a){var b=0;a.forEach(function(a){a=l.getParentBox(a);
b=Math.max(b,a.w)});a.forEach(function(a){g._applyParentBoxWidth(a,b)})},_equalizeVariableAndHeaderText:function(a,b,c){function h(a){return g._getFont(a,b,d,c?"header":"variable")}var d=0;a.forEach(function(a){a=l.getParentBox(a);d=Math.max(d,a.w)});var e=Infinity,f;a.forEach(function(a){if(a=h(a))e=Math.min(e,a.fontSize),a.isBold||(f=!0)});a.forEach(function(a){var b=h(a);b&&(b=l.getParentBox(a).w*b.fontSize/e,g._applyParentBoxWidth(a,b),!c&&f&&(k.getSectionJsonInfographic(a).variableTables[0].variable.style.fontWeight=
"normal"))})},_applyParentBoxWidth:function(a,b){var c=l.getParentBox(a),h=(c.w-b)/2,d=k.getSectionJsonInfographicTable(a);d.style.left-=h;a.stack.filter(function(a){return a!==d}).forEach(function(a){a.style.left-=h});c.x+=h;c.w=b;l.setParentBox(a,c)},_equalizeDescriptionText:function(a,b){var c=0;a.forEach(function(a){a=l.getParentBox(a);c=Math.max(c,a.w)});var h=Infinity,d;a.forEach(function(a){if(a=g._getFont(a,b,c,"description"))h=Math.min(h,a.fontSize),a.isBold||(d=!0)});a.forEach(function(a){var b=
k.getSectionJsonInfographic(a).variableTables[0].description;b&&(a=l.getParentBox(a).w/c,b.style.fontSize=h*a,d&&(b.style.fontWeight="normal"))})},_getFont:function(a,b,c,h){var d=l.getParentBox(a);a=k.getSectionJsonInfographic(a);y.applyThemeSettingsToJson(a,b.getInfographicDefaultStyles().staticInfographic);var e,f;if("header"===h)f=a.header.data.data[0],b=a.header.data.columns[0].field,e=f.style.fields[b].fontSize||f.themeStyle&&f.themeStyle.fields[b].fontSize,f=f.style.fields[b].fontWeight||f.themeStyle&&
f.themeStyle.fields[b].fontWeight;else if(b=a.variableTables[0][h])e=b.style.fontSize||b.themeStyle&&b.themeStyle.fontSize,f=b.style.fontWeight||b.themeStyle&&b.themeStyle.fontWeight;c/=d.w;return e&&{fontSize:(e||0)*c,isBold:"bold"===f}},_equalizeIcons:function(a,b){function c(a,c){if(d[c])return d[c];var f=l.getParentBox(a);a=k.getSectionJsonInfographic(a).variableTables[0].shape;return a&&a.shapeJson&&!a.shapeJson.showAsBar?(a=u.getActualShapeBox(a,b))?d[c]={areaFactor:h/f.w*Math.sqrt(a.w*a.h)}:
null:null}a=a.filter(function(a){a=k.getSectionJsonInfographic(a);return!u.isVariableInShape(a.variableTables[0])});var h=0;a.forEach(function(a){a=l.getParentBox(a);h=Math.max(h,a.w)});var d=[],e=Infinity;a.forEach(function(a,b){(a=c(a,b))&&(e=Math.min(e,a.areaFactor))});a.forEach(function(a,b){var d=k.getSectionJsonInfographic(a).variableTables[0].shape;if(a=d&&c(a,b)){a=e/a.areaFactor;b=(d.style.width-d.style.width*a)/2;var n=(d.style.height-d.style.height*a)/2;d.style.width*=a;d.style.height*=
a;d.style.left+=b;d.style.top+=n}})},_equalizeLayout:function(a,b){a=a.filter(function(a){a=k.getSectionJsonInfographic(a).variableTables[0];if(a.shape&&a.shape.shapeJson&&a.shape.shapeJson.showAsBar)return!1;a=u.getClosestId(a,"custom");return"v1"===a||"v4"===a});var c=0;a.forEach(function(a){a=l.getParentBox(a);c=Math.max(c,a.w)});var h=0,d=0,e=0,f=0;a.forEach(function(a,b){b=l.getParentBox(a);b=c/b.w;a=k.getSectionJsonInfographic(a).variableTables[0];a=u.getBoxes(a);a.iconBox&&(h=Math.max(h,a.iconBox.h*
b),d=Math.max(d,a.iconBox.w*b));e=Math.max(e,a.variableBox.h*b);f=Math.max(f,a.descriptionBox.h*b)});a.forEach(function(a,b){b=l.getParentBox(a);var g=c/b.w,m=k.getSectionJsonInfographic(a).variableTables[0],p=u.getBoxes(m),r=m.shape||m.image;if(r&&(r.style.height=h/g,r.style.width=d/g,m.image&&m.image.imageJson)){var n=m.image.imageJson.style=m.image.imageJson.style||{};n.left=0;n.top=0;n.width=r.style.width;n.height=r.style.height}m.variable.style.height=e/g;m.description.style.height=f/g;r?(r.style.top=
0,m.variable.style.top=r.style.top+r.style.height):m.variable.style.top=0;m.description.style.top=m.variable.style.top+m.variable.style.height;var m=u.getBoxes(m),n=0,q=-10/g;r&&(r.style.left-=(m.iconBox.w-p.iconBox.w)/2,q+=m.iconBox.y-p.iconBox.y,n=-q);n+=m.descriptionBox.y+m.descriptionBox.h-p.descriptionBox.y-p.descriptionBox.h;b.y+=q;b.h+=n;l.setParentBox(a,b);var t=k.getSectionJsonInfographicTable(a);t.style.top-=q;a.stack.filter(function(a){return a!==t}).forEach(function(a){a.style.top-=q})})},
_hideBackgroundElements:function(a){return a.map(function(a){var b=k.getSectionJsonInfographic(a);b&&b.type===q.STATIC&&(a.stack=[k.getSectionJsonInfographicTable(a)]);return a})}};return g});