// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer",["./utils","./_FieldInfoPreviewRenderer","./_FieldInfoDataRenderer","dojo/i18n!esri/nls/jsapi"],function(f,h,k,d){var n=d.geoenrichment.dijit.ReportPlayer.ReportPlayer.missingVariable,p=d.geoenrichment.dijit.ReportPlayer.ReportPlayer.unsupportedContent;d=d.geoenrichment.dijit.ReportPlayer.VariableStates;var e={},g={renderPreview:function(a,c){return c.fieldData?k.getValueFromFieldData(a,
c):h.getValuePreview(a,c)},tryProvideConditionalStylePreview:function(a,c,b){a.isUnavailableData||a.conditionalStyle||b.fieldData||!(c=h.getConditionalStylePreview(c,b))||(a.conditionalStyle=b.previewConditionalStyle?c:!1)},tryProvideRangeFilterPreview:function(a,c){a.isUnavailableData||a.rangeValue||c.fieldData||!c.presetFilter||(a.rangeValue=h.getRangeFilterPreview(c))}},l={buildVariableLabel:function(a){function c(b,a){return!b||b.length<=a?b:b.substr(0,a-3)+"..."}function b(b,a){switch(a){case "p":a=
d.statePercent_short;break;case "a":a=d.stateAverage_short;break;case "i":a=d.stateIndex_short;break;case "r":a=d.stateReliability_short;break;default:return b}return b+" ("+a+")"}return"["+(a.isWebMap?c(a.webMapFieldName,15)+"(WebMap)":a.isSiteAttribute?c(a.alias,15)+"(SiteAttribute)":a.isDataLayerAttribute?c(a.alias,15)+"(NearbyLocations)":a.isCustomDataCollection?c(a.alias,15)+"(CustomData)":b(a.variableID,a.statefulName&&a.statefulName.charAt(0).toLowerCase()))+"]"},buildScriptLabel:function(a){return"["+
f.name.renderScriptName(a.name)+"]"}},m={renderRichTextFieldInfoInTableCell:function(a,c){return f.richText.createRichTextFromFieldInfo(a,function(a){var b=e.renderFieldInfoInTableCell(a,c),d=b.formattedValue;c&&c.isBenchmarked&&(a=c.getBenchmarkInfo(b.value,a),d+=" ("+(a.isGreater?"+":"-")+a.formattedValue+")");return d},function(a){return e.renderFieldInfoInTableCell(a,c).formattedValue})}};e.renderFieldInfoInTableCell=function(a,c){c=c||{};var b={formattedValue:null,value:null,formatFunction:null,
isUnavailableData:!1,conditionalStyle:null,rangeValue:null};if(a.isRichText)return b.formattedValue=m.renderRichTextFieldInfoInTableCell(a,c),b;if(a.isMissing)return b.formattedValue=n,b.isUnavailableData=!0,b;if(a.isUnsupportedContent)return b.formattedValue=p,b.isUnavailableData=!0,b;c.previewValues?b=g.renderPreview(a,c):b.formattedValue=a.hasVariable?l.buildVariableLabel(a):a.script?l.buildScriptLabel(a.script):"["+a.alias+"]";if(a.hasVariable||a.script)if(g.tryProvideConditionalStylePreview(b,
a,c),g.tryProvideRangeFilterPreview(b,c),b.formattedValue=f.format.providePercentCurrencySymbols(b.formattedValue,a,{placePercentCurrencyInFront:!c.previewValues}),b.formatFunction){var d=b.formatFunction;b.formatFunction=function(b){return f.format.providePercentCurrencySymbols(d(b),a,{placePercentCurrencyInFront:!c.previewValues})};b.conditionalStyle&&void 0===b.conditionalStyle.formattedValue&&(b.conditionalStyle.formattedValue=b.formatFunction(b.conditionalStyle.value));b.rangeValue&&void 0===
b.rangeValue.formattedValue&&(b.rangeValue.formattedValue=b.formatFunction(b.rangeValue.value))}return b};e.getConditionalStylePreview=function(a,c){var b={};g.tryProvideConditionalStylePreview(b,a,{rowIndex:c,previewConditionalStyle:!0});return b.conditionalStyle};e.renderRichTextFieldInfoInTableCell=m.renderRichTextFieldInfoInTableCell;e.getValueFromFieldData=k.getValueFromFieldData;e.getFieldDataValue=k.getFieldDataValue;return e});