// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/comparison/ComparisonSelectionBuilder","dojo/_base/declare dojo/_base/lang dojo/aspect dojo/on esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct ../../comparison/ComparisonSelect esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),function(u,v,n,w,x,y,p,z,A,l,t,g){g=g.geoenrichment.dijit.ReportPlayer.ComparisonTableInfographic;
return u(null,{grid:null,groups:null,fields:null,selectedLevelsCache:null,additionalColumnsCache:null,variablesInColumns:!1,isEditMode:!1,simplifySelectionForSingleGeography:!0,numThisAreas:1,constructor:function(a){v.mixin(this,a);this.grid.own(n.after(this.grid,"refresh",this._initDropDowns.bind(this)));this.grid.canSortCellFunc=function(a){return!l.isMouseOver(a.__geographySelect&&a.__geographySelect.domNode)&&!l.isMouseOver(a.__removeAdditionalColumnOrRowButton)};this._initDropDowns()},_initDropDowns:function(){var a;
x(this.grid.getRenderPromise(),function(){if(this.variablesInColumns){var b=this.grid.getSortRowIndexMapping();a=this.grid.queryCells({columnIndex:0});b&&(_fieldCells=[],a.forEach(function(a,c){_fieldCells[b[c]]=a}),a=_fieldCells)}else a=this.grid.queryCells({rowIndex:0});a.shift();for(var f=0;f<this.numThisAreas;f++)a.shift();this._addDropDownsToCells(a)}.bind(this))},_addDropDownsToCells:function(a){a.forEach(function(a,f){this._addDropDownToCell(a,this.groups[f])},this)},_addDropDownToCell:function(a,
b){function f(){var b=a.getFullStyle();c.style.paddingLeft=c.style.paddingRight=b.horizontalPadding+"px";var q=a.getContentWidth()-2+"px";r.style.maxWidth=c.style.width=q;d?d.domNode.style.maxWidth=q:e.style.maxWidth=q;c.style.textAlign=b.horizontalAlign;r.style.height=r.style.lineHeight=a.getContentHeight()/2+"px";e.style.height=e.style.lineHeight=a.getContentHeight()/2+"px";k&&(k.style.top=(e.clientHeight-k.clientHeight)/2+"px")}var h=this;a.__addDropDownCleanUp&&a.__addDropDownCleanUp();if(b.features.length){var c=
p.create("div",{"class":"esriGEComparisonSelectionBuilder_root"}),r=p.create("div",{innerHTML:b.label,"class":"esriGEComparisonSelectionBuilder_title TrimWithEllipses"},c),e=p.create("div",{"class":"esriGEComparisonSelectionBuilder_select"},c);if(1<b.features.length||!this.simplifySelectionForSingleGeography){var d=(new z({"class":"esriGEOnDemandSelectNoBackground",fields:this.fields,canAddFeatures:!0,addFeatureMessage:this.variablesInColumns?g.showInSeparateRow:g.showInSeparateColumn,featureIsAlreadyAddedMessage:g.alreadyAdded,
onFeatureSelected:function(a,b){h.onFeatureSelected(a,b)},isFeatureAdded:function(a,c){return(h.selectedLevelsCache[b.levelId]||b.features[0].attributes.StdGeographyID)===c?!0:(a=h.additionalColumnsCache[b.levelId])&&-1!==a.indexOf(c)},onAddFeature:function(a,b){h.onAddFeature(a,b)}})).placeAt(e);a.own(d);d.setGroups([b]);d.setValue(b.levelId,this.selectedLevelsCache[b.levelId]||b.features[0].attributes.StdGeographyID);var l=a.getFullStyle().color;d.selectedLabel.style.color=l;d.arrow.style.borderTopColor=
l}else if(e.innerHTML=b.features[0].attributes.StdGeographyName,y.add(e,"TrimWithEllipses"),b.isRemovable){e.style.position="relative";var k=p.create("div",{"class":"esriGEComparisonTableInfographic_removeButton"},e);t.setTooltipToNode(k,this.variablesInColumns?g.removeRow:g.removeColumn);w(k,"click",function(a){a.stopPropagation();h.onRemoveAdditionalFeature(b.levelId,b.additionalFeatureId)});a.__removeAdditionalColumnOrRowButton=k}var m=[];m.push(n.after(a,"setWidth",f));m.push(n.after(a,"setHeight",
f));m.push(n.after(this.grid,"renderCell",function(c){c===a&&h._addDropDownToCell(a,b)},!0));m.forEach(function(b){a.own(b)});A.enableContentAbsolute(e,!this.isEditMode,{isTransparent:!0});a.setContent(c);a.set("value","");f();a.__addDropDownCleanUp=function(){m.forEach(function(a){a.remove()});d&&d.destroy();delete a.__addDropDownCleanUp};a.__geographySelect=d;t.autoTooltip(c)}},onFeatureSelected:function(a,b){},onAddFeature:function(a,b){},onRemoveAdditionalFeature:function(a,b){}})});