// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/lists/FlowList","dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/dom-class dojo/on ../utils/DeviceUtil ../utils/DnDUtil ../utils/MouseUtil ../utils/PopupUtil ../utils/TooltipUtil ./FlowListDefaultItemRenderer dijit/_WidgetBase dijit/_TemplatedMixin".split(" "),function(m,n,e,f,g,h,p,q,k,r,l,t,u){var d=m([t,u],{templateString:"\x3cdiv class\x3d'esriGEFlowList esriGENonSelectable'\x3e\x3c/div\x3e",idProperty:"value",labelProperty:"label",selectedIndex:-1,
selectedItem:null,items:null,store:null,defaultItemRendererClass:l,itemRenderer:null,itemClass:null,itemClassSelected:null,keepScrollPosition:!1,allowRepetitiveSelection:!0,selectOnMouseDown:!1,noDragTolerance:0,selectionValidator:null,allowManualSelection:!0,stopMouseEventPropagation:!0,hasSelectableItems:!0,autoDetectUrlsInLabels:!1,storeItemsInInnerDiv:!1,_addedWrappers:null,_clickHandles:null,_valueOnCreation:null,_isCreated:!1,itemsDiv:null,postCreate:function(){this.inherited(arguments);this.itemsDiv=
this.storeItemsInInnerDiv?e.create("div",{"class":"esriGEFlowList_innerDiv"},this.domNode):this.domNode;this._clearHandlers();this._setUpItemRenderer();r.autoTooltip(this.domNode);this._isCreated=!0;this._valueOnCreation?this._setValueAttr(this._valueOnCreation):this.refresh()},_setUpItemRenderer:function(){this.itemRenderer||(this.itemRenderer=new this.defaultItemRendererClass);this.itemClass&&(this.itemRenderer.itemClass=this.itemClass);this.itemClassSelected&&(this.itemRenderer.itemClassSelected=
this.itemClassSelected)},_getValueAttr:function(){return this.selectedItem&&this.selectedItem[this.idProperty]},_setValueAttr:function(a){var c=this;if(this._isCreated){var b=this.items||this.store&&this.store.data;b&&b.some(function(b){if(b[c.idProperty]==a)return c.setSelectedItem(b),!0})}else this._valueOnCreation=a},_scrollTopMemo:0,memoScroll:function(){this._scrollTopMemo=this.domNode.scrollTop},applyScrollFromMemo:function(){this.domNode.scrollTop=this._scrollTopMemo||0},_setItemsAttr:function(a){this.setItems(a)},
setItems:function(a,c){this.keepScrollPosition&&this.memoScroll();this.clear();this.items=a;c||(this.items&&this._isCreated?(this._addItems(a),this._checkIfStillSelected(),this.keepScrollPosition&&this.applyScrollFromMemo()):this._checkIfStillSelected())},_checkIfStillSelected:function(){if(-1!=this.selectedIndex||this.selectedItem){var a=this;this._addedWrappers&&this._addedWrappers.some(function(c,b){return a._isItemSelected(c,b)})||(this.selectedIndex=-1,this.selectedItem=null)}},refresh:function(){this.store?
this.setStore(this.store):this.setItems(this.items)},setSelectedItem:function(a,c){this.hasSelectableItems&&(this.selectedItem=a,this.selectedIndex=-1,this.refresh(),c&&this._dispatchChangeEvent())},setSelectedIndex:function(a,c){this.hasSelectableItems&&(this.selectedIndex=a,this.selectedItem=null,this.refresh(),c&&this._dispatchChangeEvent())},getItemNode:function(a){var c;this._addedWrappers&&this._addedWrappers.some(function(b){if(b.itemRef===a)return c=b.__itemPresentation,!0});return c},getItemByNode:function(a){var c;
this._addedWrappers&&this._addedWrappers.some(function(b){if(b.__itemPresentation===a)return c=b.itemRef,!0});return c},__selectedPresentation:null,_addItems:function(a){this._addedWrappers=this._addedWrappers||[];var c=this;a.forEach(function(a){var b=n.mixin({},a);b.itemRef=a;c.__addWrapper(b)})},__addWrapper:function(a){var c=this._addedWrappers.length,b=this.itemRenderer.createPresentation(a.itemRef,this._isItemSelected(a,c),this.itemsDiv,this,a);b&&(b.index=c,b.item=a.itemRef,a.__itemPresentation=
b,this._isItemSelected(a,c)&&(this.selectedItem=a.itemRef,this.selectedIndex=c,this.__selectedPresentation=b),this._addClickHandler(b),this._addedWrappers.push(a),a=this._addedWrappers.length-1,f.add(b,"listItem_"+a),f.add(b,"listItem_"+(0==a%2?"even":"odd")))},_isItemSelected:function(a,c){return this.hasSelectableItems&&this._isItemClickable(a)?c==this.selectedIndex||a.itemRef===this.selectedItem?!0:a.itemRef&&this.selectedItem?(a=a.itemRef[this.idProperty],c=this.selectedItem[this.idProperty],
void 0!==a&&a===c):!1:!1},_isItemClickable:function(a){return this.selectionValidator?this.selectionValidator(a):this._selectionValidatorDefault(a)},_selectionValidatorDefault:function(a){return!!a&&!a.isSeparator&&!1!==a.enabled},_addClickHandler:function(a){function c(){(b.allowRepetitiveSelection||b.__selectedPresentation!=a)&&b._isItemClickable(a.item)&&(b.__selectedPresentation&&b.itemRenderer.selectPresentation&&b.itemRenderer.selectPresentation(b.__selectedPresentation,!1,b.__selectedPresentation.item),
b.itemRenderer.selectPresentation&&b.itemRenderer.selectPresentation(a,b.hasSelectableItems,a.item),b.__selectedPresentation=a,b.selectedIndex=a.index,b.selectedItem=a.item,b._dispatchChangeEvent())}var b=this;if(this.allowManualSelection){var d;d=this.selectOnMouseDown||!this.noDragTolerance?g(a,this.selectOnMouseDown?h.press:h.click,function(a){b.stopMouseEventPropagation&&a.stopPropagation();c()}):p.addNoDragClickHandler(a,c,{tolerance:this.noDragTolerance});this._clickHandles.push(d)}},_dispatchChangeEvent:function(){this.onChange({type:"change",
selectedIndex:this.selectedIndex,selectedItem:this.selectedItem,value:this.selectedItem&&this.selectedItem[this.idProperty]})},clear:function(){this.__selectedPresentation=null;this._addedWrappers=this._addedWrappers||[],this._addedWrappers.forEach(function(a){a.destroyPresentation&&a.destroyPresentation()});this._addedWrappers.length=0;this.itemsDiv&&e.empty(this.itemsDiv);this._clearHandlers()},_clearHandlers:function(){this._clickHandles=this._clickHandles||[];this._clickHandles.forEach(function(a){a.remove()});
this._clickHandles.length=0},scrollToItem:function(a){if(a=this.getItemNode(a))this.domNode.scrollTop=a.offsetTop},store:null,onDemandModeLoadStep:1E3,onDemandPopulateLimit:1E3,onDemandPopulatePeriod:200,_setStoreAttr:function(a){this.setStore(a)},setStore:function(a){this.keepScrollPosition&&this._memoScroll();this.clear();this.idProperty=(this.store=a)&&a.idProperty;if(this.store&&this._isCreated){this._loadNextPart();this._checkIfStillSelected();this.keepScrollPosition&&this.applyScrollFromMemo();
var c=this;this.own(g(this.domNode,"scroll",function(){var a=c._addedWrappers[c._addedWrappers.length-30];(a=a?a.__itemPresentation:null)&&a.offsetTop<c.domNode.scrollTop&&c._loadNextPart()}))}else this._checkIfStillSelected()},_loadNextPart:function(){if(this.store&&this.store.query().length!=this._addedWrappers.length){var a=this.store.query(null,{start:this._addedWrappers.length,count:this.onDemandModeLoadStep});delete a.total;this._addItems(a);a.length&&this._addedWrappers.length<this.onDemandPopulateLimit&&
(a=this._loadNextPart.bind(this),setTimeout(a,this.onDemandPopulatePeriod))}},isMouseOver:function(a){return q.isMouseOver(this.domNode,{event:a})},onChange:function(a){},destroy:function(){this.clear();this.inherited(arguments)}});d.itemRenderers={DefaultItemRenderer:l};d.createPopup=function(a){function c(){b||(b=new d({"class":a.listClass,itemRenderer:a.itemRenderer,items:a.options,onChange:function(c){a.onChange(c);!a.keepSelection&&b.setSelectedItem(null);k.close(b)}}),a.doNotOwn||a.wizard.own(b),
a.isDeferred&&a.isDeferred(b));return b}var b;k.makePopup(a.isDeferred?c:c(),a.wizard,a.aroundNode,a.popupOptions||{});return b};return d});