// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/paginatableTable/SectionJsonsBuilder","dojo/_base/lang ../../sections/SectionTypes ../../grid/coreUtils/GridDataUtil ../../supportClasses/tableJson/TableJsonResizeUtil ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoFormatUtil esri/dijit/geoenrichment/utils/FieldUtil".split(" "),function(f,y,t,p,z,u){function v(b,a){return u.isNumericField(b)&&"number"===typeof a&&!isNaN(a)}var d={buildSectionJsonsAndStat:function(b){var a=
d._collectGridDataObjectsAndStats(b);if(!a)return null;if(a.gridDataObjects.length)var c=d._splitRowsByPages(a.gridDataObjects,b).map(function(a){return d._buildSectionJsonForPage(a,b)});return{sectionJsons:c,stats:a.stats,unitedSectionJson:d._buildSectionJsonForPage(a.gridDataObjects,b)}},buildStats:function(b){return(b=d._collectGridDataObjectsAndStats(b,!0))&&b.stats},_collectGridDataObjectsAndStats:function(b,a){var c=b.calculatorDataArray,d=b.searchTextRe;if(!c||!c.length)if(b.allowNoResults)c=
[];else return null;var e=b.dataSectionJson.stack[0],k=e.data.data[0],l=e.data.data[1],g={numAttributesTotal:0,numAttributesShown:0,ranges:{}},q;b.filterRanges&&(q={},b.filterRanges.forEach(function(b){q[b.fieldName]=b}));for(var p in k.fieldInfos){var m=k.fieldInfos[p];u.isNumericField(m)&&(g.ranges[m.name]={fieldName:m.name,alias:m.alias,min:Infinity,max:-Infinity,sumTotal:0,sumShown:0,decimals:m.decimals,dataArray:[]})}var r=[];c.forEach(function(c,x){var n={style:null,fieldInfos:{}};g.numAttributesTotal++;
var l=!1,f=!1,w=!1;e.data.columns.forEach(function(b){var a=k.fieldInfos[b.field],h=c[a.name];if(v(a,h)){var e=g.ranges[a.name];e.min=Math.min(e.min,h);e.max=Math.max(e.max,h);e.dataArray.push(h)}void 0===h||"string"===typeof h?n[b.field]=h||"":(n[b.field]=z.formatNumber(h,a),t.setNumericDataValue(h,n,b.field));n.__attributeIndex=x;(b=q&&q[a.name])&&(h<b.min||h>b.max)&&(l=!0);d&&"string"===typeof h&&(f=!0,d.test(h)&&(w=!0))});var m=l||f&&!w;m||a||(r.push(n),g.numAttributesShown++);e.data.columns.forEach(function(b){var a=
k.fieldInfos[b.field];b=c[a.name];v(a,b)&&(a=g.ranges[a.name],a.sumTotal+=b,m||(a.sumShown+=b))});b.setAttributeVisibleAt&&b.setAttributeVisibleAt(x,!m)});b.sorting&&r.sort(function(a,c){var d=t.getNumericDataValue(a,b.sorting.field),d=void 0!==d?d:a[b.sorting.field];a=t.getNumericDataValue(c,b.sorting.field);a=void 0!==a?a:c[b.sorting.field];c="number"===typeof d?d-a:d.localeCompare(a);return"desc"===b.sorting.order?-c:c});r.forEach(function(a,b){a.style=f.clone((0!==b%2?l||k:k).style);a.style.height=
k.style.height});g.ranges=Object.keys(g.ranges).map(function(a){return g.ranges[a]});return{stats:g,gridDataObjects:r}},getAttributeIndexForGridData:function(b){return b.__attributeIndex},_splitRowsByPages:function(b,a){var c=d._getHeaderHeight(a),f=d._getDataRowHeight(a),e=d._getDataListHeight(b,a),k=[],l,g=0;b.forEach(function(a){l||(l=[],k.push(l),g+=c);l.push(a);g+=f;g+f>e&&(l=null,g=0)});return k},_getHeaderHeight:function(b){return b.scaleToFitHeight?b.minRowHeight:b.headerSectionJson?b.headerSectionJson.stack[0].data.data[0].style.height:
0},_getDataRowHeight:function(b){return b.scaleToFitHeight?b.minRowHeight:b.dataSectionJson.stack[0].data.data[0].style.height},_getDataListHeight:function(b,a){var c=d._getHeaderHeight(a),f=d._getDataRowHeight(a),e=a.height-(a.hasFooter?a.footerHeight:0)-(a.hasTitle?a.titleHeight:0);a=a.height-a.footerHeight-(a.hasTitle?a.titleHeight:0);return c+f*b.length<=e?e:a},_buildSectionJsonForPage:function(b,a){var c;a.headerSectionJson?(c=a.headerSectionJson.stack[0],c={id:"table",attributes:{},style:{width:a.width},
data:{columns:f.clone(c.data.columns),data:[f.clone(c.data.data[0])].concat(f.clone(b))}}):c={id:"table",attributes:{},style:{width:a.width},data:{columns:f.clone(a.dataSectionJson.stack[0].data.columns),data:f.clone(b)}};c.data.data.forEach(function(b,c){b.style.height=0===c&&a.headerSectionJson?d._getHeaderHeight(a):d._getDataRowHeight(a)});a.scaleToFitHeight&&(b=d._getDataListHeight(b,a),p.resizeTableJsonToFitHeight(c,b));p.resizeTableJsonToFitWidth(c,a.width);return{type:y.DETAILS,stack:[c]}}};
return d});