// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/commands/CreateHTMLCommand","require dojo/_base/declare esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when ./createHTML/CommandMode ../../PlayerCommands ./supportClasses/ProgressSteps dojo/i18n!esri/nls/jsapi".split(" "),function(w,x,y,e,n,z,f,g){function A(){var c=new y;w(["dijit/Dialog","./createHTML/HTMLToSVGBuilder","./createHTML/HTMLStringBuilder","esri/dijit/geoenrichment/utils/FileUtil","./mapToImage/MapToImageUtil"],function(b,
e,a,f,d){k=b;p=e;u=a;v=f;l=d;c.resolve()});return c.promise}g=g.geoenrichment.dijit.ReportPlayer.ReportPlayer;var k,p,u,v,l;return x(null,{id:z.HTML,errorMessage:g.exportInfographicError,exportMapErrorMessage:g.exportMapError,_player:null,_saveFiles:!0,_stopPrintableContainer:!0,_printableContainer:null,_mode:n.SVG_IN_HTML,_requestSizeLimit:0,_mergePageIndexes:!0,_currentProgressBack:null,execute:function(c,b,g){var a=this;return A().then(function(){function k(){return e(h&&h.undo(),function(){return e(a._stopPrintableContainer&&
d&&d.stop(),function(b){a._stepFinished(f.UNSET_LAYOUT);return b})})}this._player=c;var d,h;this._currentProgressBack=g;var m={svgInHtmlString:null,svgStrings:null,documentOptions:null,additionalFiles:null};return e(function(){d=b.printableContainer;a._printableContainer=d;l.enableCaching();return e(l.replaceMapWithImage(c,{saveImagesAsDataUrl:!0,printMapTaskUrl:b.printMapTaskUrl}),function(b){h=b;l.clearCaching();a._stepFinished(f.REPLACE_MAPS)})}(),function(){if(d)return e(u.buildHtmlStringForPlayer(d,
a._mergePageIndexes),function(g){function h(c,d){if(!b.returnAsHtmlText&&!b.returnAsSvgText&&a._saveFiles&&c)return a._confirmSaveFile(d,function(){return v.saveTextFile(c,d)})}function k(){var b=q+".svg";return e(p.htmlToSvg(g.domString,d.getFitParams(),a._requestSizeLimit,t),function(a){m.svgStrings=a;return h(a[0],b)})}function l(){var b=q+".html";return e(p.htmlToSvgInHtml(g.domString,q,d.getFitParams(),a._requestSizeLimit,t),function(a){m.svgInHtmlString=a;return h(a,b)})}if(g.domString){a._stepFinished(f.PREPARE_DOM);
var q=c.getReportTitle(),t=function(b,c){a._stepFinished(f.RENDER_PAGE,b+1,c)};m.documentOptions=d.getDocumentOptions();var r=a._mode;b.returnAsHtmlText&&(r=n.SVG_IN_HTML);b.returnAsSvgText&&(r=n.SVG);switch(r){case n.SVG:return k();case n.SVG_IN_HTML:return l()}}})}).otherwise(function(c){return!b.skipErrorNotification&&a._handleError(c)}).always(function(){return e(k(),function(){return h&&h.errors.length?(!b.skipErrorNotification&&a._handleExportMapError(h.errors[0]),null):b.returnAsHtmlText?m.svgInHtmlString:
b.returnAsSvgText?m.svgStrings:m})})}.bind(this))},_stepFinished:function(c,b,e){if(this._currentProgressBack){var a=0;switch(c){case f.REPLACE_MAPS:a=10;break;case f.PREPARE_DOM:a=20;break;case f.RENDER_PAGE:a=20+70*b/e;break;case f.UNSET_LAYOUT:a=100}this._currentProgressBack(a/100)}},_handleError:function(c){console.log(c);(new k({title:"Error",content:this.errorMessage})).show()},_handleExportMapError:function(c){console.log(c);(new k({title:"Error",content:this.exportMapErrorMessage})).show()},
_confirmSaveFile:function(c,b,e){return b()}})});