// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/htmlToSvg/supportClasses/text/TextMeasurer","dojo/dom-construct ../dom-style ./TextStyleBuilder ../TransformUtil ./FlowCalculator ./ReplaceUtil ./SiblingsUtil".split(" "),function(h,l,z,w,A,x,y){var g={_linesNode:null,_wordNode:null,_wordsNode:null,createTempLinesNode:function(a){this._linesNode=this._linesNode||this._createTempNode();return this._styleNode(this._linesNode,a,!0)},createTempWordNode:function(a){this._wordNode=this._wordNode||this._createTempNode(!0);
return this._styleNode(this._wordNode,a)},createTempWordsNode:function(a){this._wordsNode=this._wordsNode||this._createTempNode(!0);return this._styleNode(this._wordsNode,a)},_createTempNode:function(a){var b=h.create("div",null,document.body);l.set(b,{position:"absolute",display:"inline-block",left:a?"600px":"300px",top:"100px",color:"yellow"});return b},_styleNode:function(a,b,e){z.resetTextStyle(a);l.set(a,"display","inline-block");b&&(l.set(a,"width",e?b.style.cw+"px":""),l.set(a,b.style.getTextStyleObject()));
return a},dispose:function(a){a&&l.set(a,"display","none")},cleanUp:function(){this._linesNode&&h.destroy(this._linesNode);this._linesNode=null;this._wordNode&&h.destroy(this._wordNode);this._wordNode=null;this._wordsNode&&h.destroy(this._wordsNode);this._wordsNode=null}},B={getParagraphs:function(a,b){function e(a){return x.collapseMultipleSpaces(a.trim())}var c=b.style.getTextStyle("whiteSpace");(b="pre-wrap"===c||"pre"===c||"pre-line"===c)||(a=x.removeReturns(a));(c="pre-wrap"===c||"pre"===c)||
(a=e(a));a=b?a.split(String.fromCharCode(10)):[a];1<a.length&&!c&&(a=a.map(e));return a}},t={measureWidth:function(a,b){b.innerHTML=a;return l.get(b,"width")}},v={getLinesForWords:function(a,b,e,c,d){function C(){var a=c.innerHTML;c.innerHTML="";a=a.split("");return v.getLinesForWords(a,b,e,c,{checkBreaking:!1,separator:""}).lines}function l(a){a=a.split("");return v.getLinesForWords(a,b,e,c,{checkBreaking:!1,separator:"",clearLinesNodeBeforeMeasure:!d.isBreakAll}).lines}function k(a,b){b=b||"";return g.test(a)?
a+b:a+d.separator+b}var m,q,p=0;d.checkBreaking&&(c.innerHTML="a",q=c.clientHeight);var f=0,n="";d.clearLinesNodeBeforeMeasure&&(c.innerHTML="");var g=/[^\s]-$/;a.some(function(a){if(m){var b;d.checkBreaking&&(b=c.innerHTML);c.innerHTML=k(c.innerHTML,a);var r=c.clientHeight;0<f&&r>f&&r-f<p/2&&(p+=r-f,f=r);if(0<f&&r>f){m.push({text:n,w:t.measureWidth(n,e),lineHeight:p});var h;if(d.checkBreaking&&(r-f>1.2*q||d.isBreakAll)){c.innerHTML=k(n);var g=l(a);c.innerHTML=k(b,a);1<g.length&&(h=!0,g.forEach(function(a,
b){b<g.length-1?0===b&&d.isBreakAll?(b=m[m.length-1],b.text=k(b.text,a.text),b.w=t.measureWidth(b.text,e)):m.push(a):(p=a.lineHeight,n=a.text)}),f=r)}h||(n=a,p=r-f,f=r)}else n=k(n,a),0===f&&(p=f=c.clientHeight)}else if(m=[],c.innerHTML=d.clearLinesNodeBeforeMeasure?a:c.innerHTML+a,n=a,p=f=c.clientHeight,d.checkBreaking&&f>1.2*q){var u=C();1<u.length&&u.forEach(function(a,b){b<u.length-1?m.push(a):(p=a.lineHeight,n=a.text)})}});m.push({text:n,w:t.measureWidth(n,e),lineHeight:p});var h=c.clientWidth;
"justify"===b.style.textAlign&&m.forEach(function(a,b){if(!d.isInsideParagraph||b!==m.length-1){var c=0;a.words=a.text.split(" ").map(function(a){var b=t.measureWidth(a,e);c+=b;return{text:a,w:b}});a.wordSpace=2>a.words.length?0:(h-c)/(a.words.length-1)}});return{lines:m,textWidth:h,lineHeight:p}}},D={getLinesForParagraph:function(a,b,e,c){a=this._splitIntoWords(a);var d="break-word"===b.style.getTextStyle("overflowWrap")||"break-word"===b.style.getTextStyle("wordWrap"),g="break-all"===b.style.getTextStyle("wordBreak");
return v.getLinesForWords(a,b,e,c,{checkBreaking:d||g,isBreakAll:g,clearLinesNodeBeforeMeasure:!0,separator:" ",isInsideParagraph:!0})},_splitIntoWords:function(a){return a.replace(/([^\s])-([^\s])/g,"$1- $2").split(" ")}},q={_node:null,_originalInnerHTML:null,_nextSiblingsHideInfo:null,setNode:function(a){this._node=a;this._nextSiblingsHideInfo=this._originalInnerHTML=null},doPresets:function(){this._originalInnerHTML=this._node.innerHTML;this.hideNextSibling()},undoPresets:function(){this.showNextSibling();
this._node.innerHTML=this._originalInnerHTML},hideNextSibling:function(){this._nextSiblingsHideInfo||(this._nextSiblingsHideInfo=y.hideNextSiblings(this._node))},showNextSibling:function(){y.showNextSiblings(this._nextSiblingsHideInfo);this._nextSiblingsHideInfo=null}};return{getLines:function(a,b){if(a.innerHTML&&a.innerHTML.trim()){var e=w.disableTransform(a,b.parentVs);q.setNode(a);q.doPresets();var c=B.getParagraphs(a.innerHTML,b),d=b.isSpanLike?a:g.createTempLinesNode(b),h=g.createTempWordNode(b),
l,k=[];c.forEach(function(a){a=D.getLinesForParagraph(a,b,h,d);l=a.textWidth;k=k.concat(a.lines)});b.isSpanLike&&(d.innerHTML=q._originalInnerHTML,a=d.clientHeight,q.showNextSibling(),c=d.clientHeight,c>a&&(k[k.length-1].lineHeight+=(c-a)/2),q.hideNextSibling());q.undoPresets();g.dispose(h);!b.isSpanLike&&g.dispose(d);w.restoreTransform(e);return{lines:k,textWidth:l}}},getSpanFlowOffsets:function(a,b){return A.getSpanFlowOffsets(a,b)},cleanUp:function(){g.cleanUp()}}});