// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/urlUtils","dojo/_base/lang dojo/_base/array dojo/_base/url dojo/global dojo/io-query ./kernel ./lang ./config ./sniff dojo/i18n!./nls/jsapi".split(" "),function(k,w,p,l,r,m,t,x,q,y){var c={},n=x.defaults.io,z=/^[a-z][a-z0-9\+\-\.]*:/i,u=/^\s*http:/i,v=/^\s*https:/i,A=/:\d+$/,B=/^https?:\/\/[^/]+\.arcgis.com\/sharing(\/|$)/i;c.isHTTP=function(a){var b=l.location.protocol;return null==a?"http:"===b||"https:"===b:a?"https:"===b:"http:"===b};c.getProtocolForWebResource=function(a){return c.isHTTP()?
l.location.protocol:a?"https:":"http:"};c.urlToObject=function(a){var b={},c=new p(a),d=a.indexOf("?");null===c.query?b={path:a,query:null}:(b.path=a.substring(0,d),b.query=r.queryToObject(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b};c.getProxyUrl=function(a,b){var e=k.isString(a)?0===k.trim(a).toLowerCase().indexOf("https:"):a,d=n.proxyUrl,f,g=y.io.proxyNotSet;k.isString(a)&&(a=c.getProxyRule(a))&&(d=a.proxyUrl);
if(!d)throw console.log(g),Error(g);e&&!1!==b&&0!==l.location.href.toLowerCase().indexOf("https:")&&(b=d,0!==b.toLowerCase().indexOf("http")&&(b=c.getAbsoluteUrl(b)),b=b.replace(/^http:/i,"https:"),c.canUseXhr(b)&&(d=b,f=1));d=c.urlToObject(d);d._xo=f;return d};c.addProxy=function(a){var b=c.getProxyRule(a),e;b?e=c.urlToObject(b.proxyUrl):n.alwaysUseProxy&&(e=c.getProxyUrl());e&&(b=c.urlToObject(a),a=e.path+"?"+b.path,(e=r.objectToQuery(k.mixin(e.query||{},b.query)))&&(a+="?"+e));return a};c.addProxyRule=
function(a){var b=a.urlPrefix=c.urlToObject(a.urlPrefix).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),e=n.proxyRules,d,f=e.length,g,h=f;for(d=0;d<f;d++)if(g=e[d].urlPrefix,0===b.indexOf(g)){if(b.length===g)return-1;h=d;break}else 0===g.indexOf(b)&&(h=d+1);e.splice(h,0,a);return h};c.getProxyRule=function(a){var b=n.proxyRules,e=b.length,d=c.urlToObject(a).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),f;for(a=0;a<e;a++)if(0===d.indexOf(b[a].urlPrefix)){f=
b[a];break}return f};c.hasSameOrigin=function(a,b,c){a=a.toLowerCase();b=b.toLowerCase();var d=l.location.href.toLowerCase();a=0===a.indexOf("http")?new p(a):d=new p(d);b=0===b.indexOf("http")?new p(b):k.isString(d)?new p(d):d;return(c||a.scheme===b.scheme)&&a.host===b.host&&a.port===b.port};c.canUseXhr=function(a,b){var e=q("esri-phonegap")?!0:!1,d=c.hasSameOrigin,f=n.corsEnabledServers,g,h=-1;!e&&q("esri-cors")&&f&&f.length&&(e=w.some(f,function(b,c){b=!b||"object"!==typeof b||b instanceof RegExp?
b:b.host;if(b instanceof RegExp){if(b.test(a))return h=c,!0}else if(b&&(g=0!==b.trim().toLowerCase().indexOf("http"),d(a,g?"http://"+b:b)||g&&d(a,"https://"+b)))return h=c,!0;return!1}));return b?h:e};c.getAbsoluteUrl=function(a){var b=c.getProtocolForWebResource();return k.isString(a)&&!z.test(a)?0===a.indexOf("//")?b+a:0===a.indexOf("/")?b+"//"+l.location.host+a:m._appBaseUrl+a:a};c.fixUrl=function(a){a=k.trim(a);a=c.getAbsoluteUrl(a);a=c.normalizeSlashes(a);a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,
"$1www.$2");a=c.downgradeToHTTP(a);return a=c.upgradeToHTTPS(a)};c.normalize=function(a){return c.fixUrl(a)};c.normalizeSlashes=function(a){if(/^https?:\/\//i.test(a)){var b,c,d=a.indexOf("?");-1<d?(b=a.slice(0,d),c=a.slice(d+1)):b=a;a=b.replace(/\/{2,}/g,"/");a=a.replace("/","//");c&&(a+="?"+c)}return a};c.downgradeToHTTP=function(a){return c.isHTTP(!1)&&v.test(a)&&c.hasSameOrigin(l.location.href,a,!0)&&!c.canUseXhr(a)?a.replace(v,"http:"):a};c.upgradeToHTTPS=function(a){var b=n.httpsDomains,e=c.isHTTP(!1),
d=c.isHTTP(!0);if(!u.test(a))return a;a=k.trim(a);var f=a.indexOf("/",7),f=-1===f?a:a.slice(0,f),f=f.toLowerCase().slice(7);if(A.test(f))if(t.endsWith(f,":80"))f=f.slice(0,-3),a=a.replace(":80","");else return a;if(e&&f===l.location.host&&(!B.test(a)||!c.canUseXhr(a)))return a;e=!1;if(d&&f===l.location.host)e=!0;else if(b)for(var g=0;g<b.length;g++){var h=b[g];if(f===h||t.endsWith(f,"."+h)){e=!0;break}}e||!d||n.alwaysUseProxy||c.getProxyRule(a)||(e=!0);e&&(a=a.replace(u,"https:"));return a};q("extend-esri")&&
(k.mixin(m,c),m._getProxyUrl=c.getProxyUrl,m._getProxiedUrl=c.addProxy,m._hasSameOrigin=c.hasSameOrigin,m._canDoXOXHR=c.canUseXhr,m._getAbsoluteUrl=c.getAbsoluteUrl,m.fixUrl=c.fixUrl);return c});