// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/mesh/templates/WGLMarkerTemplate","require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Logger ../../../../../../core/screenUtils ../../../../../../core/libs/gl-matrix/mat2d ../../../../../../core/libs/gl-matrix/vec2 ../../color ../../definitions ../../enums ../../number ../../WGLDisplayRecord ./WGLMeshTemplate".split(" "),function(u,A,C,D,r,y,v,B,E,w,t,F,G){Object.defineProperty(A,"__esModule",{value:!0});var z=
D.getLogger("esri.views.2d.engine.webgl.WGLMeshTemplate");u=function(u){function d(c,a,b,n,g,l,k,h,f,d,p){if(255<k||255<h)z.error("mapview-oversized-resource","Marker size was clamped to the maximum allowed value of 200x200 pixels"),k>h?(h*=255/k,k=255):(k*=255/h,h=255);var m=u.call(this)||this;m.geometryType=w.WGLGeometryType.MARKER;var e=v.create(),q=y.create(),x=p.sdf?.5:1;y.translate(q,q,new Float32Array([x*b,x*-n]));g&&y.rotate(q,q,3.14159265359/180*g);m._materialStore=c;m.vvFlags=a;m._materialId=
c.createSpriteMaterial(p,m.geometryType,a);m._fillColor=l;m._outlineColor=f;m._sizeOutlineWidth=t.i8888to32(k,h,d,0);c=Math.round(p.rect.x/4);a=Math.round(p.rect.y/4);g=c+Math.round(p.rect.width/4);p=a+Math.round(p.rect.height/4);e.set([-.5*k,-.5*h]);v.transformMat2d(e,e,q);m._offsetAndTexUpperLeft=t.i8888to32(e[0],e[1],c,a);e.set([.5*k,-.5*h]);v.transformMat2d(e,e,q);m._offsetAndTexUpperRight=t.i8888to32(e[0],e[1],g,a);e.set([-.5*k,.5*h]);v.transformMat2d(e,e,q);m._offsetAndTexBottomLeft=t.i8888to32(e[0],
e[1],c,p);e.set([.5*k,.5*h]);v.transformMat2d(e,e,q);m._offsetAndTexBottomRight=t.i8888to32(e[0],e[1],g,p);m.height=h;m.width=k;m.xOffset=b;m.yOffset=n;return m}C(d,u);d.fromPictureMarker=function(c,a,b,n,g){g=Math.round(r.pt2px(b.width));var l=Math.round(r.pt2px(b.height)),k=E.PICTURE_FILL_COLOR,h=Math.round(r.pt2px(b.xoffset||0)),f=Math.round(r.pt2px(b.yoffset||0));return new d(c,a,h,f,b.angle,k,g,l,0,0,n)};d.fromSimpleMarker=function(c,a,b,n,g){g=B.premultiplyAlphaRGBA(b.color);var l=Math.round(r.pt2px(b.size)),
k=Math.round(r.pt2px(b.xoffset||0)),h=Math.round(r.pt2px(b.yoffset||0)),f=b.outline,x=(f&&f.color&&B.premultiplyAlphaRGBA(f.color))|0,f=(f&&f.width&&Math.round(r.pt2px(f.width)))|0;return new d(c,a,k,h,b.angle,g,l,l,x,f,n)};d.prototype.writeMesh=function(c,a,b,n,g,l,k){l=this._materialStore.get(this._materialId);var h=a.indexVector;a=a.get("geometry");var f=new F(n,this.geometryType,this._materialId),d=this._getOffset(a,l);c.push(f);f.vertexFrom=d;f.indexFrom=h.length;switch(b){case "esriGeometryPoint":b=
g.geometry;c=b.x;b=b.y;this._writeVertices(f,a,n,this._getPos(c,b),l,k);this._writeIndices(f,h,d);break;case "esriGeometryPolyline":this._writeMany(f,h,a,d,n,g.geometry.paths[0],l,k);break;case "esriGeometryPolygon":(b=g.centroid)?(c=b.x,b=b.y,this._writeVertices(f,a,n,this._getPos(c,b),l,k),this._writeIndices(f,h,d)):z.error("Tried to render polygon geometries as markers, but found no centroid!");break;case "esriGeometryMultipoint":this._writeMany(f,h,a,d,n,g.geometry.points,l,k);break;default:z.error("Unable to handle geometryType: "+
b)}};d.prototype._getPos=function(c,a){return t.i1616to32(c,a)};d.prototype._writeMany=function(c,a,b,d,g,l,k,h){for(var f=0,n=0,p=0,m=0;m<l.length;m++){var e=l[m],q=e[0],e=e[1];this._writeVertices(c,b,g,this._getPos(q+f,e+n),k,h);this._writeIndices(c,a,d+p);f+=q;n+=e;p+=4}};d.prototype._getOffset=function(c,a){a=a.materialKeyInfo.hasVV()?10:6;return c.length/a};d.prototype._writeVertices=function(c,a,b,d,g,l){a.push(d);a.push(this._offsetAndTexUpperLeft);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);
a.push(this._sizeOutlineWidth);this._writeVV(a,l,g);a.push(d);a.push(this._offsetAndTexUpperRight);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,l,g);a.push(d);a.push(this._offsetAndTexBottomLeft);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,l,g);a.push(d);a.push(this._offsetAndTexBottomRight);a.push(b);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);
this._writeVV(a,l,g);c.vertexCount+=4};d.prototype._writeVV=function(c,a,b){b.materialKeyInfo.hasVV()&&(c.push(a[w.VVType.SIZE]),c.push(a[w.VVType.COLOR]),c.push(a[w.VVType.OPACITY]),c.push(a[w.VVType.ROTATION]))};d.prototype._writeIndices=function(c,a,b){a.push(b+0);a.push(b+1);a.push(b+2);a.push(b+1);a.push(b+3);a.push(b+2);c.indexCount+=6};return d}(G.default);A.default=u});