// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/renderer/RasterStretchColorRampRenderer","dojo/_base/declare dojo/_base/lang ./RasterRenderer ../function/StretchFunction ../function/ContrastBrightnessFunction ../function/ColormapFunction ../function/rasterUtils".split(" "),function(h,k,l,m,n,p,q){return h([l],{declaredClass:"esri.layers.rasterLib.renderer.RasterStretchColorRampRenderer",rendererName:"Stretch",bandIndex:0,colorRamp:null,invert:!1,stretchType:0,min:0,max:255,numberOfStandardDeviations:2,statistics:null,
histograms:null,dra:!1,minPercent:.25,maxPercent:.5,useGamma:!1,gamma:null,computeGamma:!1,sigmoidStrengthLevel:1,constructor:function(a){this.stretchType="number"===typeof this.stretchType?this.stretchType:"none   standardDeviation histogramEqualization minMax percentClip   sigmoid".split(" ").indexOf(this.stretchType);a=k.mixin({},a,{stretchType:this.stretchType});Object.keys(a).forEach(function(b){null==a[b]&&delete a[b]});this._function=new n(a);this._stretchFunction=new m(a);this._stretchFunction.outputPixelType=
"U8";this._stretchFunction.renderTexture=!1;this._clrFunction=new p(a);this._clrFunction.functionArguments.raster=this._stretchFunction;this._clrFunction.renderTexture=!1;this._function.functionArguments.raster=this._clrFunction},hasTilingEffects:function(){return this._stretchFunction.hasTilingEffects()},draw2D:function(a){this._updateStretchParameters();a=this._clonePixelData(a);if("U8"===a.pixelBlock.pixelType&&!(this.contrastOffset||this.brightnessOffset||this.colorRamp))return a;this._stretchFunction._stretch(a);
var b=a.pixelBlock,c=this.bandIndex;b&&1<b.pixels.length&&b.pixels.length>c&&(b.pixels=[b.pixels[c]],b.statistics&&(b.statistics=[b.statistics[c]]));this.colorRamp&&(a=this._clrFunction._colorize(a));if(this.contrastOffset||this.brightnessOffset)a.pixelBlock=q.contrastBrightnessStretch(a.pixelBlock,{contrastOffset:this.contrastOffset,brightnessOffset:this.brightnessOffset});return a},drawGL:function(a){this._updateStretchParameters();var b=a.pixelBlock,c=this.bandIndex,d=this.statistics,e=this.histograms,
f,g;b&&1<b.pixels.length&&b.pixels.length>c&&(b.pixels=[b.pixels[c]],b.statistics&&(b.statistics=[b.statistics[c]]),d&&0<d.length&&(f=[d[c]]),e&&0<e.length&&(g=[e[c]]));this._stretchFunction.functionArguments.statistics=f||d;this._stretchFunction.functionArguments.histograms=g||e;b=!!this.colorRamp;this.contrastOffset||this.brightnessOffset?(this._stretchFunction.renderTexture=!1,this._clrFunction.renderTexture=!1,this._function.renderTexture=!0,a=this._stretchFunction._stretchGL(a),b&&(a=this._clrFunction._colorizeGL(a)),
this._function._cbGL(a)):b?(this._stretchFunction.renderTexture=!1,this._clrFunction.renderTexture=!0,a=this._stretchFunction._stretchGL(a),this._clrFunction._colorizeGL(a)):(this._stretchFunction.renderTexture=!0,this._stretchFunction._stretchGL(a))},toJson:function(){var a=this._stretchFunction.toJson().rasterFunctionArguments;a.colorRamp=this.colorRamp||"";this.invert&&(a.invert=!0);a.contrastOffset=this.contrastOffset;a.brightnessOffset=this.brightnessOffset;return{rendererName:this.rendererName,
rendererArguments:a}},_updateStretchParameters:function(){var a=this._stretchFunction.functionArguments;a.stretchType=this.stretchType;a.min=this.min;a.max=this.max;a.numberOfStandardDeviations=this.numberOfStandardDeviations;a.statistics=this.statistics;a.histograms=this.histograms;a.dra=this.dra;a.minPercent=this.minPercent;a.maxPercent=this.maxPercent;a.useGamma=this.useGamma;a.gamma=this.gamma;a.computeGamma=this.computeGamma}})});