// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/_DataDrillingSupport","dojo/_base/declare dojo/aspect dojo/on esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct dojo/dom-style dojo/query ./SimpleInfographicViewModes ../../grid/coreUtils/GridDataUtil ./dataDrilling/DataDrillingLibrary ../utils/InfographicJsonUtil esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/utils/WaitingUtil ../../sections/SectionTypes ../../sections/sectionUtils/SectionJsonUtil ../../supportClasses/ViewModes ./DataDrillingBackgroundUtil ./DataDrillingExportUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(t,D,m,l,E,n,A,w,x,F,y,B,u,q,C,p,z,G,H,I,J,K,v,r){r=r.geoenrichment.dijit.ReportPlayer.Infographics;var h={w:700,h:600,minW:400,minH:500};t=t(null,{_drillingSections:null,_drillingSectionsButtons:null,postCreate:function(){var a=this;this.inherited(arguments);m(this.backToMainViewButton,"click",function(){a._setViewMode(x.VIEW_MAIN,!0)});q.isMobileDevice()&&this.own(m(window,"resize, orientationchange",function(){a._setViewMode(x.VIEW_MAIN,!1)}));p.hide([this.exportButton,this.printButton]);
this.viewModel.dynamicReportInfo&&(v.canExportDataDrilling(this)&&(z.setTooltipToNode(this.exportButton,r.exportInfographic),p.show(this.exportButton),m(this.exportButton,"click",function(){v.exportDataDrilling(a)})),v.canPrintDataDrilling(this)&&(z.setTooltipToNode(this.printButton,r.printInfographic),p.show(this.printButton),m(this.printButton,"click",function(){v.printDataDrilling(a)})))},_getCountryID:function(){return this.viewModel.dynamicReportInfo.infographicOptions.countryID},_addDataDrillingHandlers:function(a,
b){var c=this;this.onShowWaiting(l(y.init({variableProvider:this.viewModel.dynamicReportInfo.templateVariableProvider,countryID:this.viewModel.dynamicReportInfo.countryID}),function(){var f=F.getFieldInfo(b.getFirstCell()),d=B.getDataDrilling(c._currentInfographicJson,f.templateName),e=d&&d.sectionJson?d:null,g=(d=d&&d.isStandard&&y.getDrillingOptions(c._getCountryID(),d.standardId||f))&&d[0];if(e||g)a.getTables().forEach(function(a){a.getFieldCells().forEach(function(a){z.setTooltipToNode(a.domNode,
null)})}),c._setUpDataDrillingButton(a,function(a){a=c._setViewMode(x.VIEW_DATA_DRILLING,!0,a,e&&e.sectionJson);e?c._renderCustomSectionJson({customDDPanelInfo:e,fieldInfo:f,animationPromise:a}):c._loadStandardDataDrillingView({fieldInfo:f,optionName:g.name,calcState:null,sectionVisualState:null,animationPromise:a})})}))},_setUpDataDrillingButton:function(a,b){function c(){var b=n.create("div",{"class":"simpleInfographic_drillDataButton"},a.domNode);n.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonIcon esriGESpaceAfterBig"},
b);var d=n.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonLabel",innerHTML:r.drillForMoreData},b),c=[];a.getTables().forEach(function(a){c.push(a.domNode)});var e=p.uniteNodeBoxes(c,a.domNode);A.set(b,{left:e.x+"px",top:e.y+"px",width:e.w+"px",height:e.h+"px",lineHeight:e.h+"px"});var k=b.clientWidth;k>e.w&&A.set(b,"left",e.x-(k-e.w)/2+"px");d.style.maxWidth=k-50+"px";d.style.whiteSpace="normal";f._drillingSectionsButtons.push({destroy:function(){n.destroy(b)}});return b}var f=
this,d;if(q.isMobileDevice()){var e=function(a){d.style.opacity=a?1:0;g=a;k&&k.remove()},g=!1,k;C.addNoDragClickHandler(a.domNode,function(){g||(d=d||c(),e(!0),setTimeout(function(){k=C.addNoDragClickHandler(d,function(){e(!1);b(d)});m.once(document.body,"touchend",function(){e(!1)})}))},{detectLongPress:!0,longPressTimeout:750,ignoreReleaseIfLongPressHappened:!0,longPressCallback:function(){d=d||c();e(!0);b(d);setTimeout(function(){e(!1)})}})}else a.own(m.once(this.domNode,"mouseover",function(){d=
d||c();m(d,"click",function(){b(d)})}))},_dataDrillingState:null,_loadStandardDataDrillingView:function(a){var b=a.fieldInfo,c=a.optionName,f=a.calcState,d=a.sectionVisualState,e=a.animationPromise,g=this;this._dataDrillingState={fieldInfo:b,optionName:c,calcState:f,sectionVisualState:d};this._destroyDrillingSections();this._showDDProgress(!0);return l(function(){var a=g._getDataDrillingPanelDimensions(),d=B.getDataDrilling(g._currentInfographicJson,b.templateName),e=y.getDrillingOptionInfo(g._getCountryID(),
d.standardId||b,c,a.w,a.h,f),a=e.enrichInfos;return l(a&&a.length&&g.viewModel.enrichFieldData(a),function(){return e})}(),function(a){return l(g._renderStandardOptionInfo({drillingDataOptionInfo:a,fieldInfo:b,animationPromise:e,optionName:c,calcState:f,sectionVisualState:d}),function(){g._showDDProgress(!1)})})},_renderStandardOptionInfo:function(a){var b=a.drillingDataOptionInfo,c=a.fieldInfo,f=a.animationPromise,d=a.optionName,e=a.sectionVisualState,g=this,k;this._destroyDrillingSections();var h=
this._getDataDrillingPanelSectionParams();h.json={type:H.DETAILS,stack:[b.tableJson]};h.calculationStatesGroup=b.calculationStatesGroup;h.onCalculationStateChanged=function(a){g._loadStandardDataDrillingView({fieldInfo:c,optionName:d,calcState:a,sectionVisualState:k.getVisualState(),animationPromise:null})};return l(f,function(){return u.delay(function(){k=g._createDataDrillingSection(h);k.fitContentNicely();k.domNode.style.opacity="0.01";return l(k.getContentFullPromise(),function(){return u.delay(function(){k.setVisualState(e);
k.domNode.style.opacity="";k.notifyShown()},100)})})})},_renderCustomSectionJson:function(a){var b=a.customDDPanelInfo,c=a.animationPromise,f=a.sectionVisualState,d=this;this._destroyDrillingSections();this._dataDrillingState=null;var e,g=this._getDataDrillingPanelSectionParams(b.sectionJson);g.json=b.sectionJson;this._showDDProgress(!0);return l(c,function(){return u.delay(function(){e=d._createDataDrillingSection(g,!0);e.fitContentNicely();e.domNode.style.opacity="0.01";return l(e.getContentFullPromise(),
function(){return u.delay(function(){e.setVisualState(f);e.domNode.style.opacity="";e.notifyShown();d._showDDProgress(!1)})})})})},_getDataDrillingPanelSectionParams:function(a){var b={"class":"infographicContainer_dataDrillingSection"};b.initialWidth=this._getDataDrillingPanelDimensions(a).w;b.initialHeight=this._getDataDrillingPanelDimensions(a).h;b.viewModel=this.viewModel;b.theme=this.theme;b.parentWidget=this;b.isDataDrillingView=!0;b.currentFeatureIndex=this.currentFeatureIndex||0;b.initialViewMode=
J.PREVIEW_VALUES;n.empty(this.dynamicSettingsToolbarRoot);b.dynamicSettingsToolbarRoot=this.dynamicSettingsToolbarRoot;return b},_createDataDrillingSection:function(a,b){var c=this._getDataDrillingPanelDimensions(b&&a.json);a=this.viewModel.layoutBuilder.createElement("section",a,this.drilledDataViewDivScaler);this._drillingSections.push(a);E[w(".sectionDynamicSettings_settingsButton",this.dataDrillingViewDiv)[0]?"add":"remove"](this.dataDrillingViewDiv,"hasChartSettingsButton");this._setUpDDPanelBackgroundColor();
c.scale&&(a.notifyPanelScaleChanged(c.scale),this._applyScaleToDataDrillingToolbarButtons(c.buttonScale||c.scale),D.after(a,"onDynamicSettingsButtonsCreated",function(){this._applyScaleToDataDrillingToolbarButtons(c.buttonScale||c.scale)}.bind(this)));return a},_applyScaleToDataDrillingToolbarButtons:function(a){var b=1/a;a=[];var c=w(".sectionDynamicSettings_buttonBar",this.dynamicSettingsToolbarRoot)[0];if(c)for(var f=0;f<c.children.length;f++)a.push(c.children[f]);a.push(this.exportButton);a.push(this.printButton);
a.push(this.backToMainViewButton);a.forEach(function(a,c){a.style.transformOrigin=this.viewModel.showDataDrillingInsidePanel?"100% 0":"100% 100%";a.style.transform="scale("+b+")";a.style["webkit-transform"]="scale("+b+")";0<c&&(c=(this.viewModel.showDataDrillingInsidePanel?5:26)*b,c+=32*(b-1),a.style.marginLeft=c+"px")},this)},_setUpDDPanelBackgroundColor:function(){var a=this.viewModel.getDocumentDefaultStyles(this.theme),a=a.backgroundImage&&a.backgroundImage.data;this.viewModel.showDataDrillingInsidePanel&&
!a||K.setUpDDPanelBackgroundColor({viewModel:this.viewModel,theme:this.theme,infographicJson:this._currentInfographicJson,node:this.dataDrillingViewDiv})},_getDataDrillingPanelDimensions:function(a){if(this.viewModel.showDataDrillingInsidePanel){a=1/this._panelScale;var b=this.width/a,c=this.height/a,f=h.minW>b,d=h.minH>c;this.dataDrillingViewDiv.style.overflowX=f?"auto":"hidden";this.dataDrillingViewDiv.style.overflowY=d?"auto":"hidden";return{scale:a,buttonScale:1/a,w:Math.max(b,h.minW)-(d?p.getScrollbarSize().w/
a:0),h:Math.max(c,h.minH)-(f?p.getScrollbarSize().h/a:0)}}b=document.body.clientWidth-(q.isLandscape()?80:40);c=document.body.clientHeight-80;if(a&&1<a.stack.length)return d=I.calcSectionJsonBox(a),f=a.style&&a.style.width||Math.max(d.w,h.w),d=a.style&&a.style.height||Math.max(d.h,h.h),a=Math.min(1,b/f,c/d),q.isMobileDevice()?{w:f,h:d,scale:a,yOffset:10,animateFromCenter:!0}:{w:f,h:d,scale:a,yOffset:c-30>d?0:15};a=Math.max(.7,Math.min(1,b/h.minW,c/h.minH));return q.isMobileDevice()?{w:b/a,h:c/a,scale:a,
yOffset:10,animateFromCenter:!0}:{w:Math.min(b/a,h.w),h:Math.min(c/a,h.h),scale:a,yOffset:c-30>h.h?0:15}},_showDDProgress:function(a){G[a?"showProgress":"removeProgress"](this.viewModel.showDataDrillingInsidePanel?this.domNode:this.dataDrillingViewDiv);var b=w(".simpleInfographic_topToolbar",this.dataDrillingViewDiv)[0];b&&(b.style.opacity=a?"0.001":"")},_getDataDrillingState:function(){return this._dataDrillingState},_setDataDrillingState:function(a){a&&this._loadStandardDataDrillingView({fieldInfo:a.fieldInfo,
optionName:a.optionName,calcState:a.calcState,sectionVisualState:a.sectionVisualState,animationPromise:null})},_panelScale:1,notifyPanelScaleChanged:function(a){this._panelScale=a;this.domNode.style.fontSize=13/(a||1)+"px"},_destroyDrillingSections:function(){this._drillingSections=this._drillingSections||[];this._drillingSections.forEach(function(a){a.destroy()});this._drillingSections.length=0;this.domNode&&n.empty(this.drilledDataViewDivScaler)},_destroyDrillingSectionsButtons:function(){this._drillingSectionsButtons=
this._drillingSectionsButtons||[];this._drillingSectionsButtons.forEach(function(a){a.destroy()});this._drillingSectionsButtons.length=0}});t.DATA_DRILLING_BOX_ZOOM=h;return t});