// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/ColormapFunction","dojo/_base/declare dojo/_base/lang ../../../renderers/colorRampGenerator ./RasterFunctionX ./pixelShaders ./RasterFunctionWebGLMixin ./rasterUtils".split(" "),function(m,n,k,p,q,r,l){return m([p,r],{declaredClass:"esri.layers.rasterLib.function.ColormapFunction",functionName:"Colormap",pixelType:"U8",renderTexture:!1,supportWebGL:!0,support2D:!0,constructor:function(a){this.functionArguments=this.mixinIgnoreCase({colormap:null,colorRampName:null,
colorRamp:null,colorMapName:null,raster:null},a);this.invert=a&&a.invert;a=a.colormap||a.Colormap;var d,c,e,b,f,h,g;if(a){if(a.features||a[0].attributes){a=a.features||a;d=Object.keys(a[0].attributes);e=d.filter(function(a){return"alpha"===a.toLowerCase()})[0];c=d.filter(function(a){return"value"===a.toLowerCase()})[0];b=d.filter(function(a){return"red"===a.toLowerCase()})[0];f=d.filter(function(a){return"green"===a.toLowerCase()})[0];h=d.filter(function(a){return"blue"===a.toLowerCase()})[0];if(!(c&&
b&&f&&h))throw"invalid colormap";a=a.map(function(a){return e?[a.attributes[c],a.attributes[b],a.attributes[f],a.attributes[h],a.attributes[e]]:[a.attributes[c],a.attributes[b],a.attributes[f],a.attributes[h]]});g=1.1>Math.max.apply(null,a.map(function(a){return a[1]}));d=e&&1.1>Math.max.apply(null,a.map(function(a){return a[4]}));if(g)for(g=0;g<a.length;g++)a[g][1]=Math.round(255*a[g][1]),a[g][2]=Math.round(255*a[g][2]),a[g][3]=Math.round(255*a[g][3]),d&&(a[g][4]=Math.round(255*a[g][4]))}this.functionArguments.colormap=
this._sortClr(a)}this._initialize()},bind:function(a){this._initialize();a=this.getSourceRasterInfo(a);if(!a.raster||"F32"===a.raster.pixelType)return Error("The raster input to colormap function is invalid. It must be integer type.");this.rasterInfo=n.mixin(a.raster,{bandCount:3,pixelType:this._calculatePixelType(this.pixelType,"U8"),statistics:null,histogram:null});this.rasterInfo.keyProperties=this.rasterInfo.keyProperties||{};this.rasterInfo.keyProperties.DataType="Processed";return!0},read2D:function(a){return this._colorize(a.raster)},
readGL:function(a){return this._colorizeGL(a.raster)},_colorize:function(a){this._performance.start();var d=l.colorize(a.pixelBlock,{indexedColormap:this._indexedColormap,indexedColormapOffset:this._indexedColormapOffset,indexed2DColormap:this._indexed2DColormap,alphaSpecified:this._alphaSpecified});this._addPerformanceMetric(this._performance.elapsed());return{extent:a.extent,pixelBlock:d}},_binarySearchClr:function(a,d){for(var c=0,e=a.length-1,b=0,f=0;c<e;)if(b=Math.floor((c+e)/2),f=a[b],f[0]<
d)c=b;else if(f[0]>d)e=b;else return f.slice(1);return null},_sortClr:function(a,d){var c,e,b=[];for(c=0;c<a.length;c++)b.push(a[c]);for(c=0;c<b.length-1;c++)for(e=b[c],a=c+1;a<b.length;a++)e[0]>b[a][0]&&(e=b[a],b[a]=b[c],b[c]=e);if(d)for(c=0;c<b.length/2;c++)e=b[c],b[b.length-1-c]=b[c],b[c]=e;return b},_invertColorRamp:function(a){if(!a)return a;var d={type:a.type};"random"===a.type?d=a:"multipart"===a.type?d.colorRamps=a.colorRamps.map(function(a){return{fromColor:a.toColor,toColor:a.fromColor}}).reverse():
(d.fromColor=a.toColor,d.toColor=a.fromColor);return d},_initialize:function(){this._indexedColormapOffset=0;if(this.functionArguments.colormap){var a=l.buildIndexedColormap(this.functionArguments.colormap);this._alphaSpecified=a&&a.alphaSpecified;this._indexedColormap=a&&a.indexedColormap;this._indexedColormapOffset=a&&a.offset;this._indexedColormap||(this._indexed2DColormap=this._getIndexed2DColormap())}else this.functionArguments.colorRamp?this._indexedColormap="multipart"===this.functionArguments.colorRamp.type?
this.invert?k.createMultiPartColorRamp(this._invertColorRamp(this.functionArguments.colorRamp)):k.createMultiPartColorRamp(this.functionArguments.colorRamp):this.invert?k.createAlgorithmicColorRamp(this._invertColorRamp(this.functionArguments.colorRamp)):k.createAlgorithmicColorRamp(this.functionArguments.colorRamp):this.functionArguments.colormapName&&"random"===this.functionArguments.colormapName.toLowerCase()&&(this._indexedColormap=k.createRandomColorRamp())},_getIndexed2DColormap:function(){var a=
this.functionArguments.colormap;if(!a)return null;var d=0;0>a[0][0]&&(d=a[0][0]);var c=[],e=5===a[0].length,b;for(b=0;b<a.length;b++)c[a[b][0]-d]=e?a[b].slice(1):a[b].slice(1).concat([255]);return c},_colorizeGL:function(a){this._performance.start();this._initializeProgram({fragment:q.colormap,fragmentName:"Colormap"});var d=this._indexedColormap,c=this._indexedColormapOffset;this._clrTexture||(this._clrTexture=this._setupColormapTexture(d));var e=this._clrTexture,b=this.gl,f=this.bindFrameBuffer(),
h=b.getUniformLocation(this.rasterProgram,"u_image"),g=b.getUniformLocation(this.rasterProgram,"u_image1");b.uniform1i(h,0);b.uniform1i(g,1);a=this._setupTextureData(a);b.activeTexture(b.TEXTURE0);b.bindTexture(b.TEXTURE_2D,a.texture);b.activeTexture(b.TEXTURE1);b.bindTexture(b.TEXTURE_2D,e);this._setUniforms({u_indexedColormapOffset:c,u_indexedColormapMaxIndex:d.length/4-1});this._drawGL();return{extent:a.extent,texture:f.texture}},_setupColormapTexture:function(a){var d=this._createTexture(),c=
this.gl,e=a.length/4,b=new Float32Array(a.length),f,h=this.renderTexture?255:1;for(f=0;f<a.length;f++)b[f]=a[f]/h;c.getExtension("OES_texture_float");c.texImage2D(c.TEXTURE_2D,0,c.RGBA,e,1,0,c.RGBA,c.FLOAT,b);return d}})});