// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/HillshadeFunction","dojo/_base/declare dojo/_base/lang ./RasterFunctionX ../../../WKIDUnitConversion ../../PixelBlock ./pixelShaders ./RasterFunctionWebGLMixin ./surfaceUtils".split(" "),function(u,v,y,m,C,z,A,B){return u([y,A],{declaredClass:"esri.layers.rasterLib.function.HillshadeFunction",functionName:"Hillshade",supportWebGL:!0,support2D:!0,renderTexture:!0,constructor:function(a){this.functionArguments=this.mixinIgnoreCase({hillshadeType:0,altitude:45,
azimuth:315,zFactor:1,slopeType:1,psPower:.664,psFactor:.024,raster:null},a);this._azimuths=[315,270,225,360,180,0];this._altitudes=[60,60,60,60,60,90];this._weights=[3,5,3,2,1,4];var m=this._weights.reduce(function(a,m){return a+m});this._weights=this._weights.map(function(a){return a/m})},bind:function(a){a=this.getSourceRasterInfo(a);if(!a.raster)return Error("The raster input to hillshade function is invalid.");this.rasterInfo=v.mixin(a.raster,{bandCount:1,pixelType:this._calculatePixelType(this.pixelType,
"U8"),statistics:[{min:0,max:255}],histogram:null});this.rasterInfo.keyProperties=this.rasterInfo.keyProperties||{};this.rasterInfo.keyProperties.DataType="Generic";return!0},read2D:function(a){this._performance.start();a=a.raster;a=B.hillshade(a,{altitude:this.functionArguments.altitude,azimuth:this.functionArguments.azimuth,zFactor:this.functionArguments.zFactor,psPower:this.functionArguments.psPower,psFactor:this.functionArguments.psFactor,hillshadeType:this.functionArguments.hillshadeType,slopeType:this.functionArguments.slopeType,
isGCS:a.extent.spatialReference.wkid&&null==m[a.extent.spatialReference.wkid]});this._addPerformanceMetric(this._performance.elapsed());return a},readGL:function(a){this._performance.start();this._initializeProgram({fragment:z.hillshade,fragmentName:"Hillshade"});a=this._setupTextureData(a.raster);var u=this.bindFrameBuffer(),n=this.gl;n.bindTexture(n.TEXTURE_2D,a.texture);var w=n.drawingBufferWidth,n=n.drawingBufferHeight,b=a.extent,q=(b.xmax-b.xmin)/w,r=(b.ymax-b.ymin)/n,g=this.functionArguments.altitude,
h=this.functionArguments.azimuth,f=this.functionArguments.zFactor;1===this.functionArguments.hillshadeType&&(f*=2);var k=f/(8*q),p=f/(8*r);.001<f&&b.spatialReference.wkid&&null==m[b.spatialReference.wkid]&&(k/=111E3,p/=111E3);var d=this.functionArguments.psPower,e=this.functionArguments.psFactor;3===this.functionArguments.slopeType&&((k=b.spatialReference.wkid&&null==m[b.spatialReference.wkid])?(k=111E3*q,p=111E3*r,k=(f+Math.pow(k,d)*e)/(8*k),p=(f+Math.pow(p,d)*e)/(8*p)):(k=(f+Math.pow(q,d)*e)/(8*
q),p=(f+Math.pow(r,d)*e)/(8*r)));var c=(90-g)*Math.PI/180,g=Math.cos(c),t=(360-h+90)*Math.PI/180,h=Math.sin(c)*Math.cos(t),c=Math.sin(c)*Math.sin(t),d=Array(6),e=Array(6),b=Array(6),x,v=this._weights,l;if(1===this.functionArguments.hillshadeType)for(x=this._azimuths.length,l=0;l<x;l++)g=this._altitudes[l],h=this._azimuths[l],c=(90-g)*Math.PI/180,g=Math.cos(c),t=(360-h+90)*Math.PI/180,h=Math.sin(c)*Math.cos(t),c=Math.sin(c)*Math.sin(t),d[l]=g,e[l]=h,b[l]=c;else d[0]=g,e[0]=h,b[0]=c;d=d.map(function(a){return parseFloat(a)});
e=e.map(function(a){return parseFloat(a)});b=b.map(function(a){return parseFloat(a)});this._setUniforms({u_cellSize:[q,r],u_zfactor:f,u_xFactor:k,u_yFactor:p,u_sinZcosA:h,u_sinZsinA:c,u_cosZ:g,u_sinZcosAs:e,u_sinZsinAs:b,u_cosZs:d,u_weights:v,u_hillshadeType:this.functionArguments.hillshadeType,u_resolution:[1/w,1/n],u_scaled:!this.renderTexture});this._drawGL();this._addPerformanceMetric(this._performance.elapsed());return{extent:a.extent,texture:u.texture}}})});