// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/webglHelper",[],function(){var l={getUniforms:function(a,e){var b=a.getProgramParameter(e,a.ACTIVE_UNIFORMS),c,f,k={};for(c=0;c<b;c++)(f=a.getActiveUniform(e,c))&&(k[f.name]={location:a.getUniformLocation(e,f.name),info:f});return k},setUniform:function(a,e,b){var c=e.info,f=e.location,k=c.type;if(null==b)console.log("uniform "+e.info.name+" has null or undefined value");else switch(k){case a.FLOAT:1<c.size?0===b.length?console.log("uniform "+e.info.name+" has length 0"):
a.uniform1fv(f,b):a.uniform1f(f,b);break;case a.FLOAT_VEC2:if(0===b.length){console.log("uniform "+e.info.name+" has length 0");break}a.uniform2fv(f,b);break;case a.FLOAT_VEC3:if(0===b.length){console.log("uniform "+e.info.name+" has length 0");break}a.uniform3fv(f,b);break;case a.FLOAT_VEC4:if(0===b.length){console.log("uniform "+e.info.name+" has length 0");break}a.uniform4fv(f,b);break;case a.INT:case a.BOOL:1<c.size?0===b.length?console.log("uniform "+e.info.name+" has length 0"):a.uniform1iv(f,
b):a.uniform1i(f,b);break;case a.INT_VEC2:case a.BOOL_VEC2:if(0===b.length){console.log("uniform "+e.info.name+" has length 0");break}a.uniform2iv(f,b);break;case a.INT_VEC3:case a.BOOL_VEC3:if(0===b.length){console.log("uniform "+e.info.name+" has length 0");break}a.uniform3iv(f,b);break;case a.INT_VEC4:case a.BOOL_VEC4:0===b.length?console.log("uniform "+e.info.name+" has length 0"):a.uniform4iv(f,b)}},createTexture:function(a,e){var b=a.createTexture();a.bindTexture(a.TEXTURE_2D,b);a.texParameteri(a.TEXTURE_2D,
a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,e?a.LINEAR:a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,e?a.LINEAR:a.NEAREST);return b},createBufferTexture:function(a,e,b){e=l.createTexture(a,e);a.getExtension("OES_texture_float");b=b||[a.drawingBufferWidth,a.drawingBufferHeight];a.texImage2D(a.TEXTURE_2D,0,a.RGBA,b[0],b[1],0,a.RGBA,a.FLOAT,null);b=a.createFramebuffer();a.bindFramebuffer(a.FRAMEBUFFER,
b);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,e,0);return{texture:e,frameBuffer:b}},getShader:function(a,e,b){b=b?a.createShader(a.VERTEX_SHADER):a.createShader(a.FRAGMENT_SHADER);a.shaderSource(b,e);a.compileShader(b);a.getShaderParameter(b,a.COMPILE_STATUS)||(console.log(a.getShaderInfoLog(b)),b=null);return b},loadProgram:function(a,e,b){var c=a.createProgram();a.attachShader(c,e);a.attachShader(c,b);a.linkProgram(c);a.getProgramParameter(c,a.LINK_STATUS)||(console.warn("failed to load webgl program: "+
a.getProgramInfoLog(c)),a.deleteProgram(c),c=null);return c},createMesh:function(a,e){if(!a||1===a)return new Float32Array([0,0,1,0,0,1,0,1,1,0,1,1]);var b;b=a&&e?new Float32Array(a*a*20):new Float32Array(a*a*12);var c=.9998/a,f,k,g,h,d=0;for(f=0;f<a;f++)for(k=0;k<a;k++)g=1E-4+c*f,h=1E-4+c*k,a&&!e?(b[d++]=g,b[d++]=h,b[d++]=g+c,b[d++]=h,b[d++]=g,b[d++]=h+c,b[d++]=g,b[d++]=h+c,b[d++]=g+c,b[d++]=h,b[d++]=g+c,b[d++]=h+c):(b[d++]=g,b[d++]=h,b[d++]=g,b[d++]=h+c,b[d++]=g,b[d++]=h+c,b[d++]=g+c,b[d++]=h+c,
b[d++]=g+c,b[d++]=h+c,b[d++]=g+c,b[d++]=h,b[d++]=g,b[d++]=h,b[d++]=g+c,b[d++]=h,b[d++]=g,b[d++]=h+c,b[d++]=g+c,b[d++]=h);return b}};return l});