// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/_SectionQueryElementsMixin",["dojo/_base/declare","../grid/coreUtils/GridDataUtil","../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil"],function(f,d,g){return f(null,{_queryElementsById:function(a,b){return this._getStackElements(b).filter(function(b){return b.stackId===a})},getStackElements:function(a){return this._getStackElements(a)},containsElement:function(a){return-1!==this._stackElements.indexOf(a)},_getStackElements:function(a){return a?
this._stackElements.slice().reverse():this._stackElements},getTables:function(a){return this._queryElementsById("table",a)},getFirstTable:function(){return this.getTables()[0]},getTopMostTable:function(){return this.getTables(!0)[0]},getLastTable:function(){var a=this.getTables();return a[a.length-1]},getDataTables:function(){return this.isDataSection()?this.getTables():[]},hasNonEmptyTables:function(){return this.getTables().some(function(a){return 0<a.columns.length&&0<a.store.data.length})},hasTablesThatFitHeight:function(){return this.getTables().some(function(a){return a.needScaleToFitHeight()})},
hasMultiFeatureTables:function(){return this.getTables().some(function(a){return a.isMultiFeatureTable()})},hasLocatorTables:function(){return this.getTables().some(function(a){return a.isLocatorTable&&a.isLocatorTable()})},hasLocatorHeaderTables:function(){return this.getTables().some(function(a){return a.isLocatorHeaderTable&&a.isLocatorHeaderTable()})},hasLocatorFooterTables:function(){return this.getTables().some(function(a){return a.isLocatorFooterTable&&a.isLocatorFooterTable()})},hasSummarizeTables:function(){return this.getTables().some(function(a){return a.isSummarizeTable&&
a.isSummarizeTable()})},hasImages:function(){return!!this.getImages().length},getImages:function(a){return this.viewModel.isGraphicStyle?this.getTables(a).filter(function(a){return this.isImageTable(a)},this).map(function(a){return a.getFirstCell().content}):this._queryElementsById("img",a)},hasOnlyImage:function(){return 1===this._stackElements.length&&this.getImages().length},hasMapImages:function(){return!!this.getMapImages().length},getMapImages:function(a){return this.viewModel.isGraphicStyle?
this.getTables(a).filter(function(a){return this.isMapTable(a)},this).map(function(a){return a.getFirstCell().content}):this._queryElementsById("map",a)},hasChart:function(){var a=0;this.getTables().forEach(function(b){b.getFieldCells().forEach(function(b){d.isChartCell(b)&&a++})});return a},getChart:function(){var a;this.getTables().some(function(b){b.getFieldCells().some(function(b){if(d.isChartCell(b))return a=b.content,!0})});return a},getChartJson:function(){var a;this.getTables().some(function(b){if(a=
b.getChartJson())return!0});return a},hasSingleInfographic:function(a){return 1===this.getTables().length&&this.getTables()[0].isSingleCelledTable()&&this.hasInfographic(a)},getInfographicType:function(){var a=this.getInfographicWithTable();return a&&a.type},hasInfographic:function(a){var b=0;this.getTables().forEach(function(c){return c.getFieldCells().forEach(function(c){!d.isInfographicCell(c)||a&&d.getFieldInfo(c).infographicJson.type!==a||b++})});return b},getInfographic:function(){var a=this.getInfographicWithTable();
return a&&a.infographic},getInfographicWithTable:function(){var a,b;this.getTables().some(function(c){return c.getFieldCells().some(function(e){if(d.isInfographicCell(e))return a=e.content,b=c,!0})});return a?{infographic:a,table:b,type:a.getType()}:null},getInfographicJson:function(){var a;this.getTables().some(function(b){if(a=b.getInfographicJson())return!0});return a},getMovableElements:function(){return this._stackElements.filter(function(a){return"table"===a.stackId||"img"===a.stackId||"map"===
a.stackId})},hasPageBreak:function(){return!!this._queryElementsById("pageBreak").length},collectFieldInfos:function(a){var b=[];this.getTables().forEach(function(c){b=b.concat(c.collectFieldInfos(a))});return b},collectFieldInfosJson:function(){var a=[];g.processSectionFieldInfos(this.toJson(),function(b){a.push(b)});return a}})});