// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/_ServerSerializationSupport","require dojo/_base/declare esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when ./supportClasses/ReportDataProcessor ./supportClasses/tasks/parsers/DataXMLParser ./supportClasses/tasks/RunReportTask ./supportClasses/areas/AnalysisAreaUtil ./supportClasses/areas/AnalysisAreaJsonUtil ./supportClasses/CustomReportsManager ./supportClasses/GEUtil ../core/supportClasses/ReportTemplateTypes ../core/conversion/PortalToEditorConverter esri/dijit/geoenrichment/utils/ImageInfoUtil".split(" "),
function(w,x,g,y,l,q,z,A,B,k,C,D,E,F,G){function r(){var a=new y;w(["./supportClasses/attachments/AttachmentsStoreSerializer","../core/supportClasses/templateJsonUtils/TemplateJsonSerializer","../core/conversion/portalToEditorUtils/variables/PlayerVariableProvider","./commands/mapToImage/MapToURLUtil","esri/dijit/geoenrichment/utils/ProjectionUtil"],function(b,h,m,c,f){n=b;t=h;u=m;p=c;v=f;a.resolve()});return a.promise}var n,t,u,p,v;return x(null,{reportDataToServerData:function(a){var b=a.getReportData(),
h=this;return r().then(function(){return g({files:b.reportObject.templateData.getFiles(),attachmentsProvider:b.attachmentsStore&&n.getAttachmentsStoreJson(b.attachmentsStore,b.analysisAreas.length),mapImages:h._getMapImages(a)}).then(function(a){var c=A.CreateReportResultCache.getResults()[0].originalXMLs[0];a.mapImages&&a.mapImages.forEach(function(a){c=c.replace(/\<mapImage_0\>mapImage_.*?\.png\<\/mapImage_0\>/,"\x3cmapImage_0\x3e"+a+"\x3c/mapImage_0\x3e")});a.files.push({name:"data.xml",data:c});
return{portalItem:{properties:{isMultiFeature:b.reportObject.isMultiFeature?"true":"false"},resources:a.files},attachmentsProvider:a.attachmentsProvider,customLogo:b.customLogo,portalUrl:b.config.portalUrl,geometryServiceUrl:b.config.geometryServiceUrl,printMapTaskUrl:b.config.printMapTaskUrl,analysisAreas:k.areasToJson(b.analysisAreas),combinedAreasInfo:b.combinedAreasInfo&&k.combinedAreasInfoToJson(b.combinedAreasInfo),reverseAnalysisAreasOnMap:b.reverseAnalysisAreasOnMap}})})},_getMapImages:function(a){a=
a.collectMaps({allAreas:!0});return g(a.map(function(a){return p.mapToURL(a.map,a.legend,a.node).then(function(a){return G.getRemoteImageDataUrl(a,{sizeLimit:100})})}))},reportDataFromServerData:function(a){function b(b){var e=C.prepareCustomReportFromItem(a.portalItem);e.isGraphicReport=!0;e.portalJson={files:f};return l(F.provideEditorJson(e,{variableProvider:b}),function(){e.templateJson=t.deserialize(e.templateJson);delete e.portalJson;return e})}function h(a,b){var e=f.filter(function(a){return"data.xml"===
a.name})[0],d=/.*\.png/i,c={};f.forEach(function(a){d.test(a.name)&&(c[a.name]=a.data)});a={selectedReport:a,areaData:z.parse(e.data,function(a,b){return c[b]||b})};q.applyRunReportAndGetDataResults(a,b)}var m=this,c=a.portalItem.resources,f;if(Array.isArray(c))f=c;else{f=[];for(var g in c)f.push({name:g,data:c[g]})}return r().then(function(){var c=new u;return l(b(c),function(b){var e=k.areasFromJson(a.analysisAreas),d={isClassic:!1,isMultiFeature:b.isMultiFeature&&1<e.length,reportType:b.type||
E.STANDARD,reportTitle:b.title||"",templateJson:b.templateJson,reportObject:b,fieldData:{metadata:{},areaData:[],errors:[]},analysisAreas:e,combinedAreasInfo:a.combinedAreasInfo&&k.combinedAreasInfoFromJson(a.combinedAreasInfo)||{},reverseAnalysisAreasOnMap:a.reverseAnalysisAreasOnMap,infographicOptions:m._infographicOptionsProvider.getInfographicOptions({geoenrichmentUrl:"",countryID:"",reportID:"",analysisAreas:e}),attachmentsStore:a.attachmentsProvider&&n.getAttachmentsStoreFromJson(a.attachmentsProvider),
geClient:null,templateVariableProvider:c,config:{portalUrl:a.portalUrl,geoenrichmentUrl:null,geometryServiceUrl:a.geometryServiceUrl,printMapTaskUrl:a.printMapTaskUrl,countryID:null,hierarchy:null,reportID:b.reportID,variables:null},customLogo:a.customLogo};B.populateCombinedAreasInfo(d.combinedAreasInfo,d.analysisAreas);h(b,d);D.setGeoenrichmentUrl(d.config.geoenrichmentUrl);d.config.geometryServiceUrl&&v.setGeometryServiceUrl(d.config.geometryServiceUrl);d.config.printMapTaskUrl&&p.setPrintMapTaskUrl(d.config.printMapTaskUrl);
return l(d.attachmentsStore&&q.populateReportDataFromAttachmentsStore(d,d.attachmentsStore),function(){return d})})})}})});