// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/tile/RasterTileManager","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when ../DeferredList2 ../../../geometry/Extent ../../../SpatialReference ../../../geometry/Point ../../PixelBlock ./RasterTileInfo ../raster/rasterProjectionHelper".split(" "),function(E,q,u,C,D,z,F,G,A,J,y){var H=function(a,b){var c;for(c=0;c<a.length;c++)if(b(a[c]))return a[c]},I=function(a,b){var c;for(c=0;c<a.length;c++)if(b(a[c]))return c;return-1};return E(null,{declaredClass:"esri.layers.rasterLib.tile.RasterTileManager",
count:null,fullBoundary:null,tileBoundary:null,tiles:null,resolution:null,virtual:!0,prefetchBufferSize:0,_progressiveGlobal:!1,_MAX_TILES:128,_defaultMatrixResolution:20,constructor:function(a){this.tiles=[];this.tileInfo=a&&a.tileInfo;this.mapSpatialReference=a&&a.mapSR;this.virtual=this.tileInfo.virtual;this.layer=a&&a.layer;this.identifiers=this.layer.raster.rasterFunction?this.layer.raster.getMemberRasters().map(function(a){return a._rasterId}):[this.layer.raster._rasterId];a=!this.virtual&&
!this.mapSpatialReference.equals(this.tileInfo.spatialReference);var b=y.requirePE(this.mapSpatialReference,this.tileInfo.spatialReference);this.xformSetting={requireProjection:a,requirePE:b,meshSize:a?this._defaultMatrixResolution:1}},setTileInfo:function(a){this.tileInfo=a;this.virtual=a.virtual;this.mapResolution=null;this.tiles.length=0;this.xformSetting.requireProjection=!this.virtual&&!this.mapSpatialReference.equals(this.tileInfo.spatialReference);this.xformSetting.requirePE=y.requirePE(this.mapSpatialReference,
this.tileInfo.spatialReference);this.xformSetting.meshSize=this.xformSetting.requireProjection?this._defaultMatrixResolution:1},updateResolution:function(a,b){if(!(this.mapResolution&&a&&this._resolutionEqual(this.mapResolution.x,a.x)&&this._resolutionEqual(this.mapResolution.y,a.y))){this.tiles.forEach(q.hitch(this,function(a){a.fetch&&!a.fetch.isCanceled()&&a.fetch.cancel();a.update&&!a.update.isCanceled()&&a.update.cancel()}));this.tiles.length=0;var c=this.xformSetting.requireProjection;this.mapResolution=
this.resolution=a;c?this.resolution=y.projectResolution(a,this.tileInfo.spatialReference,b):this._resolution=this.resolution;var e,d=this.resolution;if(!this.tileInfo.virtual){b=H(this.tileInfo.lods,function(a){return Math.abs(a.resolution-d.x)<.01*d.x});if(!b)if(d.x>this.tileInfo.lods[0].resolution)b=this.tileInfo.lods[0],this.ooe=!0;else{if(d.x<this.tileInfo.lods[this.tileInfo.lods.length-1].resolution)b=this.tileInfo.lods[this.tileInfo.lods.length-1];else for(a=0;a<this.tileInfo.lods.length-1;a++)if(b=
this.tileInfo.lods[a],e=this.tileInfo.lods[a+1],b.resolution>d.x&&e.resolution<d.x){d.x/b.resolution>e.resolution<d.x&&(b=e);break}this.ooe=!1}this.level=b&&b.level;this.resolution=new G({x:b.resolution,y:b.resolution,spatialReference:this.tileInfo.spatialReference})}a=c?this.layer.raster.rasterInfo.extent:this.layer.raster.projectedFullExtent;b=this.tileInfo.origin;c=this.tileInfo.cols;e=this.tileInfo.rows;this.fullBoundary={rowStart:Math.floor((b.y-a.ymax)/d.y/e),rowEnd:Math.ceil((b.y-a.ymin-d.y)/
d.y/e),colStart:Math.floor((a.xmin-b.x)/d.x/c),colEnd:Math.ceil((a.xmax-b.x-d.x)/d.x/c)};if(a=a.spatialReference._getInfo())this.fullBoundary.colRange=Math.round((a.valid[1]-a.valid[0])/d.x/c);this.hasNewData=!0}},getXformGrid:function(a){var b=this.extent;return y.getProjectionOffsetGrid(this.mapExtent,this.layer._hasTilingEffects?b:this.fullExtent,a)},updateExtent:function(a,b){this.mapExtent=this.extent=a;var c=this.xformSetting.requireProjection;if(c){this.extent=y.project(a,this.tileInfo.spatialReference);
if(!this.extent)return;this.extent.spatialReference=new F(this.extent.spatialReference.toJson())}this.updateResolution(b,a);a=this.extent;var e=this.tileInfo,d=e.cols,f=e.rows;b=this.resolution;var k=a,c=c?this.layer.raster.rasterInfo.extent:this.layer.raster.projectedFullExtent;this.ooe&&(k=this._getIntersect(a,c));var l=k.xmin,c=k.xmax;if(c<l){var h=a.spatialReference._getInfo();h&&(c+=Math.ceil((l-c)/(h.valid[1]-h.valid[0]))*(h.valid[1]-h.valid[0]));k.xmax=c}var l=Math.floor((l-e.origin.x)/b.x/
d)-this.prefetchBufferSize,h=Math.floor((c-e.origin.x)/b.x/d)+this.prefetchBufferSize,n=Math.floor((e.origin.y-k.ymax)/b.y/f)-this.prefetchBufferSize,B=Math.floor((e.origin.y-k.ymin)/b.y/f)+this.prefetchBufferSize;this.tileBoundary={rowStart:n,rowEnd:B,colStart:l,colEnd:h};var g,m,p;if((B-n+1)*(h-l+1)>this._MAX_TILES)this.tiles.forEach(q.hitch(this,function(a){a.fetch&&!a.fetch.isCanceled()&&a.fetch.cancel();a.update&&!a.update.isCanceled()&&a.update.cancel()})),this.tiles.length=0;else{var c=this.tiles,
k=!1,r=this.fullBoundary.colRange,v=0;r&&(0>l||h>r)&&(this.wrapTimes=v=0>l?-1-Math.floor(-l/r):Math.floor(h/r));for(g=c.length-1;0<=g;g--)if(m=c[g].row,p=c[g].col,v&&r&&(0>l||h>r)&&(p=p>h?v*r+p:p<l?v*r+p:p),m<n||m>B||p<l||p>h)c[g].fetch&&!c[g].fetch.isCanceled()&&c[g].fetch.cancel(),c[g].update&&!c[g].update.isCanceled()&&c[g].update.cancel(),c.splice(g,1),k=!0;var w;for(g=n;g<=B;g++)for(n=l;n<=h;n++)m=new z(e.origin.x+b.x*d*n,e.origin.y-b.y*f*(g+1),e.origin.x+b.x*d*(n+1),e.origin.y-b.y*f*g,a.spatialReference),
w=r?0<=n?n%r:r- -n%r:n,p=I(c,function(a){return a.row===g&&a.col===w}),-1===p&&(c.push({row:g,col:w,cellsizeX:b.x,cellsizeY:b.y,width:d,height:f,extent:m,normalizedExtent:this._wrapExtent(m),pixelBlock:null,virtual:this.virtual,level:this.level,tileType:this.tileInfo.tileType||"Raster"}),k=!0);b=this.tileInfo.rows*(this.tileBoundary.rowEnd-this.tileBoundary.rowStart+1);this.width=this.tileInfo.cols*(this.tileBoundary.colEnd-this.tileBoundary.colStart+1);this.height=b;this.count=c.length;b=Math.min.apply(null,
c.map(function(a){return a.extent.xmin}));e=Math.max.apply(null,c.map(function(a){return a.extent.xmax}));d=Math.min.apply(null,c.map(function(a){return a.extent.ymin}));f=Math.max.apply(null,c.map(function(a){return a.extent.ymax}));b=this.fullExtent=new z(b,d,e,f,a.spatialReference);if(this.layer.roaming||this.layer.useWebGL)this.layer._hasTilingEffects?(this.xformSetting.offset=[0,0],this.xformSetting.scale=[1,1]):(k&&(this._tilesChanged=!0),this.xformSetting.offset=[(a.xmin-b.xmin)/(b.xmax-b.xmin),
-(b.ymin-a.ymin)/(b.ymax-b.ymin)],this.xformSetting.scale=[(a.xmax-a.xmin)/(b.xmax-b.xmin),(a.ymax-a.ymin)/(b.ymax-b.ymin)])}},fetchTiles:function(a){(this._tilesChanged||a)&&this._fetchTiles(a)},_fetchTiles:function(a){this._fetchCounter=0;var b=this.extent;this.fetchAllCompleted=a?new u:null;(this._tilesChanged||a&&this.layer._hasTilingEffects)&&this.tiles.forEach(q.hitch(this,function(a){a.filled=!1}));var c={};!this.layer.roaming&&this.layer._hasTilingEffects&&a?(this.identifiers.forEach(function(a,
b){c[a]={extent:this.extent,pixelBlock:new A({width:this.layer._map.width,height:this.layer._map.height,pixels:[],pixelType:"",mask:null,statistics:[]})}}.bind(this)),this.originalPixelData={extent:this.extent,src:c,isEmpty:!0}):this._tilesChanged&&(this.identifiers.forEach(function(a,b){c[a]={extent:this.fullExtent,pixelBlock:new A({width:128,height:128,pixels:[],pixelType:"",mask:null,statistics:[]})}}.bind(this)),this.originalPixelData={extent:this.fullExtent,src:c,isEmpty:!0});this.tiles.forEach(q.hitch(this,
function(c){if(c.fetch)c.update||(c.update=this.updateTile(c));else{if(this._isTileOutSide(c,b))return;this._requestTile(c)}this.layer.roaming&&this.layer.useWebGL&&this._tilesChanged?this._fillPixelData(c):c.src&&a&&(this.layer._hasTilingEffects||this.layer.useWebGL)&&(this._fillPixelData(c),this.layer._hasTilingEffects&&(c.filled=!0),c.processedPixelBlock=null,c.renderedPixelBlock=null)}));0===this._fetchCounter&&(this._fetched=!0);this._tilesChanged=!1;a&&this._updateFetchStatus()},updateTile:function(a,
b){var c=new u;if(!a.src&&!a.fetch)return c.resolve(a),c.promise;C(a.src||a._fetched||a.fetch,q.hitch(this,function(){var e=this.layer.tileMode&&this.layer._rasterHandler&&!(this.layer._hasTilingEffects||this.layer.useWebGL),d=this.layer._drawTile,f=this._validateRawPixelBlocks(a);this.layer._hasTilingEffects&&!this.layer.useWebGL&&(d=d&&(this._progressiveGlobal||b));(b||!b&&f)&&(e||d||this.layer.roaming)?(this.xformSetting.requireProjection&&this.layer.useWebGL&&(this.xformSetting.xformGrid=this.getXformGrid(this.xformSetting.meshSize)),
this._processTile(a,b).then(q.hitch(this,function(a){c.isCanceled()||this._renderTile(a,b).then(q.hitch(this,function(a){this.hasNewData=!1;c.isCanceled()||c.resolve(a)}))}))):(b||f||(a.filled=!0),this.layer.useWebGL||this.layer._hasTilingEffects?c.resolve(this.originalPixelData):c.resolve())}));return c.promise},setLayer:function(a){this.layer=a},_validateRawPixelBlocks:function(a){return a&&a.src&&!this.identifiers.some(function(b){return!(a.src[b].pixelBlock&&0!==a.src[b].pixelBlock.validPixelCount&&
a.src[b].pixelBlock.pixels&&0<a.src[b].pixelBlock.pixels.length)})},_wrapExtent:function(a){var b=a.spatialReference._getInfo(),c;if(b){var e=b.valid[0],b=b.valid[1];if(a.xmin<e-this.resolution.x||a.xmax>b+this.resolution.y)c=new z((a.xmin-e)%(b-e),a.ymin,(a.xmax-b)%(b-e),a.ymax,a.spatialReference),c.xmax<c.xmin&&(c=null)}return c||a},_getIntersect:function(a,b){return new z(Math.max(a.xmin,b.xmin),Math.max(a.ymin,b.ymin),Math.min(a.xmax,b.xmax),Math.min(a.ymax,b.ymax),a.spatialReference)},_isTileOutSide:function(a,
b){var c=!1,e,d;a.virtual?(d=a.normalizedExtent,(b=b||(this.xformSetting.requireProjection?this.layer.raster.rasterInfo.extent:this.layer.raster.projectedFullExtent))?(a=d.xmin-this.prefetchBufferSize*this.tileInfo.cols*this.resolution.x,c=d.ymin-this.prefetchBufferSize*this.tileInfo.rows*this.resolution.y,e=d.xmax+this.prefetchBufferSize*this.tileInfo.cols*this.resolution.x,d=d.ymax+this.prefetchBufferSize*this.tileInfo.rows*this.resolution.y,c=e<=b.xmin||a>=b.xmax||d<=b.ymin||c>=b.ymax):c=!1):c=
0>a.level||a.row<this.fullBoundary.rowStart||a.row>this.fullBoundary.rowEnd||a.col<this.fullBoundary.colStart||a.col>this.fullBoundary.colEnd;return c},_resolutionEqual:function(a,b){return a===b||a&&b&&Math.abs(a-b)<Math.abs(b/1E4)?!0:!1},_requestTile:function(a){var b,c=this.identifiers,e;this._isTileOutSide(a)?(b=new u,b.resolve(null),b=b.promise):b=this.layer.raster.rasterFunction?new D(this.layer.raster.getMemberRasters().map(function(b){return b.read(a)})):new D([this.layer.raster.read(a)]);
a.fetch=b;this._fetchCounter++;C(a.src||a._fetched||b,q.hitch(this,function(b){if(e=b&&b.some(function(a){return a[0]})){var d={};b.forEach(function(a,b){d[c[b]]=a[0]&&a[1]?{extent:a[1].extent,pixelBlock:a[1].pixelBlock,width:a[1].width,height:a[1].height}:null});a.src=d}else a.src=null;this._fetchCounter--;0===this._fetchCounter&&(this._fetched=!0);a._fetched=!0;this._updateFetchStatus()}),q.hitch(this,function(){this._fetchCounter--;0===this._fetchCounter&&(this._fetched=!0);a._fetched=!0;this._updateFetchStatus()}));
a.update=this.updateTile(a)},_updateFetchStatus:function(){this.layer._drawTile&&this.fetchAllCompleted&&!this.fetchAllCompleted.isResolved()&&!this.tiles.some(function(a){return!a._fetched})&&(this.tiles.forEach(q.hitch(this,function(a){this._fillPixelData(a)})),this.fetchAllCompleted.resolve())},_fillPixelData:function(a,b){if(a&&!a.filled)if(Math.abs(a.cellsizeX-this.resolution.x)>a.cellsizeX/10)a.filled=!0;else if(!1===this._validateRawPixelBlocks(a))a.filled=!0;else{var c=a.extent,e,d,f;this.layer.roaming||
this.layer.useWebGL&&!this.layer._hasTilingEffects?(e=this.fullExtent,d=this.tileInfo.cols*(this.tileBoundary.colEnd-this.tileBoundary.colStart+1),f=this.tileInfo.rows*(this.tileBoundary.rowEnd-this.tileBoundary.rowStart+1),b?this.originalPixelData.renderedPixelBlock||(this.originalPixelData.renderedPixelBlock=new A({width:d,height:f,pixels:[],pixelType:"",mask:null,statistics:[]})):this.identifiers.forEach(q.hitch(this,function(a){this.originalPixelData.src[a].pixelBlock.width=d;this.originalPixelData.src[a].pixelBlock.height=
f}))):(e=this.extent,d=this.layer._map.width,f=this.layer._map.height,b?this.originalPixelData.renderedPixelBlock||(this.originalPixelData.renderedPixelBlock=new A({width:d,height:f,pixels:[],pixelType:"",mask:null,statistics:[]})):this.identifiers.forEach(q.hitch(this,function(a){this.originalPixelData.src[a].pixelBlock.width=d;this.originalPixelData.src[a].pixelBlock.height=f})));if(e.xmax<=c.xmin||e.xmin>=c.xmax||e.ymax<=c.ymin||e.ymin>=c.ymax)return null;this.originalPixelData.isEmpty=!1;this.identifiers.forEach(q.hitch(this,
function(b){a.src&&this._fillPixelBlock(a.src[b],this.originalPixelData.src[b],{extent:e,width:d,height:f},!1)}));this.hasNewData=!0}},_fillPixelBlock:function(a,b,c,e){var d=a.extent,f=c.extent;e=c.width;c=c.height;if(a.pixelBlock&&a.pixelBlock.pixels&&a.pixelBlock.pixels[0]){var k=(d.xmax-d.xmin)/a.width,l=Math.max(d.xmin,f.xmin),h=Math.min(d.ymax,f.ymax),n=Math.round((l-d.xmin)/k),q=a.width-Math.round(Math.abs(d.xmax-Math.min(d.xmax,f.xmax))/k),g=Math.round(Math.abs(d.ymax-h)/k),d=a.height-Math.round((Math.max(d.ymin,
f.ymin)-d.ymin)/k),l=Math.round((l-f.xmin)/k),f=Math.round(Math.abs(f.ymax-h)/k),m,p,r,v,k=a.pixelBlock.pixels.length;b=b.pixelBlock;var h=a.width,w=b.mask||new Uint8Array(e*c),t=a.pixelBlock,u=t.mask,x=0;for(p=0;p<k;p++){r=t.pixels[p];v=b.pixels[p]||new r.constructor(e*c);for(a=g;a<d;a++)for(x=(f+a-g)*e+l,m=n;m<q;m++)v[x+m-n]=r[a*h+m];b.pixels[p]=v}if(u)for(a=g;a<d;a++)for(x=(f+a-g)*e+l,m=n;m<q;m++)w[x+m-n]=u[a*h+m];else for(a=g;a<d;a++)for(x=(f+a-g)*e+l,m=n;m<q;m++)w[x+m-n]=1;b.pixelType=b.pixelType||
t.pixelType;b.mask=w;if(!(b.statistics&&0<b.statistics.length))for(b.statistics=[],a=0;a<t.statistics.length;a++)b.statistics[a]={minValue:t.statistics[a].minValue,maxValue:t.statistics[a].maxValue};else if(t.statistics&&b.statistics)for(a=0;a<b.statistics.length;a++)b.statistics[a].minValue=Math.min(t.statistics[a].minValue,b.statistics[a].minValue),b.statistics[a].maxValue=Math.max(t.statistics[a].maxValue,b.statistics[a].maxValue)}},_processTile:function(a,b){var c=new u,e,d=this.layer._hasTilingEffects,
f=this.layer.useWebGL,k=d||f,l=this.layer.raster.rasterFunction&&a&&(d||f||!a.processedPixelBlock);b?e=a:(this._fillPixelData(a),e=k?this.originalPixelData:a);this.xformSetting.hasNewTexture=this.hasNewData;var h;l?(this.identifiers.forEach(function(a){if(0===e.src[a].pixelBlock.pixels.length||0===e.src[a].pixelBlock.pixels[0].length)h=!0}),h?c.resolve({extent:e.extent,processedPixelBlock:e.src[this.identifiers[0]],pixelBlock:e.src[this.identifiers[0]]}):f?(this.processedPixelData=this.layer.raster.rasterFunction.read(e),
c.resolve(this.processedPixelData)):this.layer._rasterHandler?this.layer._rasterHandler.process({extent:e.extent,src:e.src}).then(function(b){d?(this.processedPixelData=b,c.resolve(this.processedPixelData)):(a.processedPixelBlock=b.pixelBlock,c.resolve(a))}):(b=this.layer.raster.rasterFunction.read(a),a.processedPixelBlock=b.pixelBlock,c.resolve(a))):k?c.resolve(e.src[this.identifiers[0]]):(a.pixelBlock=e.src[this.identifiers[0]]&&e.src[this.identifiers[0]].pixelBlock,c.resolve(a));return c.promise},
_renderTile:function(a){var b=new u,c=this.layer._hasTilingEffects,e=this.layer.useWebGL,d=Math.abs((a.extent.xmax-a.extent.xmin)/a.width-this.layer.getCurrentResolution().x)>this.resolution.x/10,d=this.layer.useWebGL&&(d||this._isTileOutSide(a,this.layer._map.extent));this.xformSetting.hasNewTexture=this.hasNewData;this.layer._rasterRenderer&&a&&(a.texture||a.src||a.pixelBlock||a.processedPixelBlock)?e&&!d?(this.layer.raster.rasterFunction&&this.layer.raster.rasterFunction.renderTexture||this.layer._rasterRenderer.draw(a),
b.resolve(a)):this.layer._rasterHandler?this.layer._rasterHandler.render({extent:a.extent,pixelBlock:a.processedPixelBlock||a.pixelBlock}).then(function(d){c?(d.renderedPixelBlock=d.pixelBlock,b.resolve(d)):(a.renderedPixelBlock=d.pixelBlock,b.resolve(a))}.bind(this)):(a.renderedPixelBlock=this.layer._rasterRenderer.draw(a).pixelBlock,b.resolve(a)):(a.renderedPixelBlock=a.processedPixelBlock||a.pixelBlock,b.resolve(a));return b.promise}})});