// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/DomUtil","dojo/_base/lang dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style esri/dijit/geoenrichment/Deferred dojo/domReady!".split(" "),function(q,p,h,g,m,e,r){function t(){l||(l=g.create("div",{"class":"esriGEOffscreen"},document.body));return l}var d={isHidden:function(a){return a&&h.contains(a,"esriGEHidden")},hasVisibleChildren:function(a){if(!a||!a.children.length)return!1;for(var b=0;b<a.children.length;b++)if(!d.isHidden(a.children[b]))return!0;
return!1},hide:function(a){return d.addTag(a,"esriGEHidden")},show:function(a){return d.removeTag(a,"esriGEHidden")},display:function(a,b){return d[b?"show":"hide"](a)},addTag:function(a,b){return d.applyCallback(a,function(a){a&&h.add(a,b)})},removeTag:function(a,b){return d.applyCallback(a,function(a){a&&h.remove(a,b)})},applyCallback:function(a,b,c){c&&(b=q.hitch(c,b));Array.isArray(a)?a.forEach(b):b(a);return a},getChildIndex:function(a,b){if(!a||!a.children||!b)return-1;for(var c=0;c<a.children.length;c++)if(a.children[c]===
b)return c;return-1},getChildren:function(a){if(!a||!a.children)return null;for(var b=[],c=0;c<a.children.length;c++)b.push(a.children[c]);return b},getChildNodes:function(a){if(!a||!a.childNodes)return null;for(var b=[],c=0;c<a.childNodes.length;c++)b.push(a.childNodes[c]);return b},isChildOf:function(a,b,c){var f=!1,d=function(a){if(c&&!c(a))return!1;a.parentNode===b?f=!0:a.parentNode&&d(a.parentNode)};a&&d(a);return f},isNodeInLayout:function(a){return d.isChildOf(a,document.body,function(a){return!d.isHidden(a)&&
"none"!=e.get(a,"display")&&!h.contains(a,"dijitHidden")})},isNodeVisible:function(a){return d.isChildOf(a,document.body,function(a){return!h.contains(a,"dijitHidden")&&"hidden"!=e.get(a,"visibility")})},isNodeOnscreen:function(a){return d.isChildOf(a,document.body,function(a){return!h.contains(a,"esriGEOffscreen")})},enableContent:function(a,b,c){if(a){c=c||{};var f=a.children.length-1;if(!(0>f)){f=a.children[f];h.contains(f,"esriGEDisabledContent")||(f=null);if(b)f&&a.removeChild(f);else if(f=f||
g.create("div",{"class":"esriGEDisabledContent"+(c.overlayClass?" "+c.overlayClass:"")},a),c.textContent&&(f.textContent=c.textContent),!1!==c.fitParent&&(a=m[c.marginBox?"getMarginBox":"getContentBox"](a).h))a=a.toString()+"px",e.set(f,{height:a,marginTop:"-"+a});return f}}},enableContentAbsolute:function(a,b,c){if(a){c=c||{};var f=e.get(a,"position");"relative"!==f&&"absolute"!==f&&e.set(a,"position","relative");return d.enableContent(a,b,{overlayClass:"esriGEAbsoluteStretched "+(c.overlayClass||
"")+(c.isTransparent?" esriGEDisabledContentTransparent ":""),fitParent:!1,textContent:c.textContent})}}},l;d.hideNodeInBackground=function(a,b){if(a){if(a._hideNodeInBackgroundUndoController)return a._hideNodeInBackgroundUndoController;var c=g.create("div",null,a,"after"),f=g.create("div",{style:"position: absolute; left: 0px; top: 0px;"},t());g.place(a,f);b="DomUtil.hideNodeInBackground"+(b?"."+b:"");p.set(c,"_bg_memo_node",b);p.set(f,"_bg_temp_node",b);b={undo:function(){c&&(c.parentNode&&g.place(a,
c,"replace"),g.destroy(c),g.destroy(f),l.children.length||(g.destroy(l),l=null),c=null,delete a._hideNodeInBackgroundUndoController)},remove:function(){this.undo()}};return a._hideNodeInBackgroundUndoController=b}};d.showNodeFromBackground=function(a){a&&a._hideNodeInBackgroundUndoController&&a._hideNodeInBackgroundUndoController.undo()};d.noTransformPosition=function(a){function b(a){for(var b={x:0,y:0};a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent,b.x+=e.get(a,"borderLeftWidth"),
b.y+=e.get(a,"borderTopWidth");return b}function c(a){return e.get(a,"width")+e.get(a,"paddingLeft")+e.get(a,"paddingRight")+e.get(a,"borderLeftWidth")+e.get(a,"borderRightWidth")}function f(a){return e.get(a,"height")+e.get(a,"paddingTop")+e.get(a,"paddingBottom")+e.get(a,"borderTopWidth")+e.get(a,"borderBottomWidth")}if(a){var d;if(a instanceof SVGElement&&a.getBBox)return d=(d=a.ownerSVGElement&&a.ownerSVGElement.parentNode)&&b(d),a=a.getBBox(),{x:(a.x||0)+d.x,y:(a.y||0)+d.y,w:a.width||0,h:a.height||
0};d=b(a);return{x:d.x,y:d.y,w:c(a),h:f(a)}}};d.uniteNodeBoxes=function(a,b){var c=1E6,f=1E6,e=-1E6,g=-1E6;a.forEach(function(a){a=d.noTransformPosition(a);c=Math.min(c,a.x);f=Math.min(f,a.y);e=Math.max(e,a.x+a.w);g=Math.max(g,a.y+a.h)});a={x:c,y:f,w:e-c,h:g-f};b&&(b=d.noTransformPosition(b),a.x-=b.x,a.y-=b.y);return a};d.getNodesBox=function(a,b){if(!a||!a.length)return null;for(var c=1E6,f=-1E6,e=1E6,g=-1E6,h=0;h<a.length;h++)var k=a[h],k=b&&b.ignoreTranformation?d.noTransformPosition(k):m.position(k),
c=Math.min(c,k.x),e=Math.min(e,k.y),f=Math.max(f,k.x+k.w),g=Math.max(g,k.y+k.h);return{x:c,y:e,w:f-c,h:g-e}};d.traverseChildren=function(a,b){function c(a){if(a&&a.children)for(var d=0;d<a.children.length;d++){var f=a.children[d];if(b(f))break;c(f)}}c(a)};d.scrollToListNode=function(a,b,c){var d=b.offsetTop+b.clientHeight,e=d-(a.scrollTop+a.clientHeight);0<e&&(a.scrollTop+=e);c&&(d-=b.clientHeight-c.offsetTop,e=a.scrollTop-d,0<e&&(a.scrollTop-=e))};var n;d.getScrollbarSize=function(){if(!n){var a=
g.create("div",null,document.body);a.style.width="100px";a.style.height="100px";a.style.overflow="scroll";a.style.position="absolute";a.style.top="9999px";n={w:a.offsetWidth-a.clientWidth,h:a.offsetHeight-a.clientHeight};g.destroy(a)}return n};d.hasScrollbars=function(a){var b=e.getComputedStyle(a);return{w:"scroll"===b.overflowX||a.offsetWidth>a.clientWidth&&"auto"===b.overflowX,h:"scroll"===b.overflowY||a.offsetHeight>a.clientHeight&&"auto"===b.overflowY}};d.getMeasureContext=function(a){a=a||{};
a.style=a.style?a.style+" ":"";a.style+="display: inline-block; position: absolute; left: 0; top: 0;";return{div:g.create("div",a,document.body),measureText:function(a){this.div.innerHTML=a;a=m.getMarginBox(this.div);delete a.l;delete a.t;return a},destroy:function(){g.destroy(this.div)}}};d.getTextBox=function(a,b){b=d.getMeasureContext(b);a=b.measureText(a);b.destroy();return a};d.getNodeFontFamily=function(a){return(a=e.get(a,"fontFamily")||e.getComputedStyle(a)["font-family"])?a.replace(/'|"/g,
"").split(",")[0]:a};d.getNodeFontSize=function(a){return e.toPixelValue(a,e.get(a,"fontSize"))};d.stealFocus=function(){var a=new r;try{var b=g.create("input",{type:"text",style:"position: absolute; left: 0px; top: 0px;"});g.place(b,document.body);b.select();g.destroy(b)}catch(c){}setTimeout(a.resolve,0);return a.promise};d.getWindowBox=function(){for(var a=[],b=0,c=document.body.children.length;b<c;b++){var e=document.body.children[b];d.isHidden(e)||(d.hide(e),a.push(e))}b={w:document.body.clientWidth,
h:document.body.clientHeight};a.forEach(function(a){d.show(a)});return b};d.getBorder=function(a){return{t:e.toPixelValue(a,e.get(a,"borderTopWidth")),r:e.toPixelValue(a,e.get(a,"borderRightWidth")),b:e.toPixelValue(a,e.get(a,"borderBottomWidth")),l:e.toPixelValue(a,e.get(a,"borderLeftWidth"))}};return d});