// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/map/_LiveMapSupport","dojo/_base/declare dojo/aspect esri/dijit/geoenrichment/when dojo/dom-construct dojo/query esri/geometry/Extent ../supportClasses/map/legend/LegendController esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/WaitingUtil".split(" "),function(n,p,g,l,h,q,r,t,k){return n(null,{_isPlacingMapFlag:!1,_placeMapPromise:null,_currentMap:null,_locatorPointsControllers:null,_stdPolygonsControllers:null,_legendController:null,
getCurrentMap:function(){return this._currentMap},getRenderPromise:function(){return this._placeMapPromise},_placeMap:function(){return this._placeMapPromise=t.invoke(this,"_doPlaceMap")},_doPlaceMap:function(){function c(){a._currentMap&&a._currentMap.destroy();a._currentMap=null}function b(){k.removeProgress(a.content);a._finalizePlaceMap();a._showErrorMessage(!0);a.onMapLoadError()}var a=this;this._showErrorMessage(!1);this._isPlacingMapFlag&&this._finalizePlaceMap();l.empty(this.content);c();
k.showProgress(this.content);this.onContentLoadingStart();this._isPlacingMapFlag=!0;this._legendController=new r;this._legendController.addCallback(function(e){a.showMapLegend=e;a.onLegendVisibilityChanged()},"mapContainer");this.viewModel.dynamicReportInfo&&this.own(this.viewModel.registerLegendController(this._legendController,this._calculatorFieldName,this.currentFeatureIndex));this._additionalLayerInfos&&this.viewModel.dynamicReportInfo&&!this._locatorPointsControllers&&(this._locatorPointsControllers=
[],this._additionalLayerInfos.forEach(function(a,c){a.index=c;if(a.isLocatorLayer){var b=this.viewModel.getLocatorPointsController(a.calculatorInfo,this.currentFeatureIndex);a.layerName&&b.setLayerName(this._calculatorFieldName,a.layerName);b.setRendererJson(this._calculatorFieldName,a.rendererJson);b.setLayerIndex(this._calculatorFieldName,c);this.own(b);this._locatorPointsControllers.push(b)}},this),this._stdPolygonsControllers=[],this._additionalLayerInfos.forEach(function(b,c){b.index=c;if(b.isComparisonLayer){var e=
function(d){d=a.viewModel.getStdPolygonsController(b.calculatorName,d);d.setRendererJson(a._calculatorFieldName,b.rendererJson);b.labelRendererJson&&d.setLabelRendererJson(a._calculatorFieldName,b.labelRendererJson);d.setLayerIndex(a._calculatorFieldName,c);a.own(d);a._stdPolygonsControllers.push(d)};this.viewModel.dynamicReportInfo.isMultiFeature?this.viewModel.dynamicReportInfo.analysisAreas.forEach(function(a,b){e(b)}):e(this.currentFeatureIndex)}},this));return g(this._createMapFunc(this.content,
{areaIndex:this.currentFeatureIndex,defaultBasemapId:this._defaultBasemapId,webMapId:this._webMapId,additionalLayerInfos:this._additionalLayerInfos&&this._additionalLayerInfos.filter(function(a){return!!a.url}),locatorPointsControllers:this._locatorPointsControllers,stdPolygonsControllers:this._stdPolygonsControllers,thisAreasHighlightController:this.viewModel.getThisAreasHighlightController(),legendController:this._legendController,waitForLoad:!0,extent:this._mapExtentPending,pinSymbolJson:this._pinSymbolJson,
areaSymbolJsons:this._areaSymbolJsons,areaSymbolRamp:this._areaSymbolRamp,calculatorFieldName:this._calculatorFieldName}),function(e){a.showMapLegend&&a._legendController.setLegendVisible(!0);a._locatorPointsControllers&&a._locatorPointsControllers.forEach(function(b){b.setMapInfo(a._calculatorFieldName,e)});a._stdPolygonsControllers&&a._stdPolygonsControllers.forEach(function(b){b.setMapInfo(a._calculatorFieldName,e)});var f=e&&e.map;c();if(!a.domNode&&f)f.destroy();else{a._currentMap=f;a._syncWithPanelScale();
for(var m=h("svg",a.domNode),d=0;d<m.length;d++)m[d].style.willChange="auto";f?(a.own(f),k.removeProgress(a.content),a._finalizePlaceMap()):b()}},b)},_finalizePlaceMap:function(){this._isPlacingMapFlag&&(this._isPlacingMapFlag=!1,this.onContentLoadingEnd())},isLegendVisible:function(){return this.showMapLegend},setLegendVisible:function(c,b){this.showMapLegend=c;return this._legendController&&this._legendController.setLegendVisible(c,b)},_mapExtentPending:null,getVisualState:function(){return{type:"map",
mapExtent:this._currentMap&&this._currentMap.extent&&this._currentMap.extent.toJson(),showLegend:this.isLegendVisible()}},setVisualState:function(c){var b=this;this._mapExtentPending=null;if(c)return g(this.getRenderPromise(),function(){c.mapExtent&&(b._currentMap&&b._currentMap.setExtent?b._currentMap.setExtent(new q(c.mapExtent)):b._mapExtentPending=c.mapExtent);b._syncWithPanelScale();return g(b._currentMap&&b._currentMap._extentDfd&&b._currentMap._extentDfd.promise,function(){if(void 0!==c.showLegend)return b.setLegendVisible(c.showLegend)})})},
_panelScale:null,_toolbarCreateH:null,notifyPanelScaleChanged:function(c){this._panelScale=c;this._syncWithPanelScale()},_syncWithPanelScale:function(){if(this._currentMap){for(var c,b=this.parentWidget;b&&!b.isSection;)(b=b.parentWidget)&&b.isSection&&(c=b);var a=c&&h(".sectionDynamicSettings_toolbar",c.domNode)[0],e=a?1:1/this._panelScale,f=32*e+8;this._toolbarCreateH&&this._toolbarCreateH.remove();c&&!a&&(this._toolbarCreateH=p.after(c,"onDynamicSettingsButtonsCreated",this._syncWithPanelScale.bind(this)));
[".esriSimpleSliderTR",".HomeButton",".mapNavigationLockButton"].forEach(function(b){var d=h(b,c&&c.domNode||this.domNode)[0];d&&(a&&d.parentNode!==a&&l.place(d,a),".mapNavigationLockButton"===b&&50<this._currentMap.root.clientHeight-(f+d.clientHeight*e)&&(f+=20),a&&(d.style.right="0px"),d.style.top=f+"px",d.style.transformOrigin="100% 0%",d.style.transform="scale("+e+")",d.style["webkit-transform"]="scale("+e+")",f+=(d.clientHeight+(".esriSimpleSliderTR"===b?2:0))*e+5)},this)}},onLegendVisibilityChanged:function(){},
destroy:function(){this._finalizePlaceMap();this.inherited(arguments)}})});