// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/infographicPanels/OneVar","esri/declare dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/query dojo/string ../BaseWidget ../utils/ObjectUtil ../infographicUtils/dom ../infographicUtils/utils ../infographicUtils/formatVariable dojo/i18n!esri/nls/jsapi".split(" "),function(q,h,m,n,v,w,x,u,r,y,p,l){l=l.geoenrichment.dijit.OneVar;return q("esri.dijit.geoenrichment.OneVar",[x],{baseClass:"Infographics_OneVar",constructor:function(){this._state={sortBy:1,sortDesc:!0}},
createUIExpanded:function(d){this.inherited(arguments);if(this._canCreateValueBlock()){var f=d.addHeader("div",{"class":"OneVarMultiComparison_Value"}),f=n.create("table",{cellpadding:"0",cellspacing:"0"},f),a=f.insertRow(0),a=a.insertCell(-1);this.site=n.create("span",{"class":"OneVarMultiComparison_Expanded_Value_Site"},a);a=f.insertRow(-1);a=a.insertCell(-1);this.primary=n.create("span",{"class":"OneVarMultiComparison_Expanded_Value_Primary"},a);this.comp=n.create("span",{"class":"OneVarMultiComparison_Comparison"},
a)}this.table=d.addContent("table",{"class":"OneVarMultiComparison_Table"});r.createCols(this.table,[.5,.2,.15,.15]);a=this.table.insertRow(-1);this._appendSortHeader(a,l.areaCol,0,{"class":"OneVarMultiComparison_TextColumnHeader"});this._appendSortHeader(a,l.valueCol,1,{"class":"OneVarMultiComparison_ValueColumnHeader"});h.set(a.insertCell(-1),"class","OneVarMultiComparison_ChartColumnHeader_Lower");h.set(a.insertCell(-1),"class","OneVarMultiComparison_ChartColumnHeader_Upper");this.autoHeight&&
d.contentClass.push("OneVarMultiComparison_Expanded_ContentPane");d.addFooter("div")},createUICollapsed:function(d){this.inherited(arguments);if(this._canCreateValueBlock()){var f=d.addHeader("div",{"class":"OneVarMultiComparison_Value"}),f=n.create("table",{cellpadding:"0",cellspacing:"0"},f),a=f.insertRow(0),a=a.insertCell(-1);this.site=n.create("span",{"class":"OneVarMultiComparison_Expanded_Value_Site"},a);a=f.insertRow(-1);a=a.insertCell(-1);this.primary=n.create("span",{"class":"OneVarMultiComparison_Expanded_Value_Primary"},
a)}this.table=d.addContent("table",{"class":"OneVarMultiComparison_Table"});r.createCols(this.table,[.7,.3]);a=this.table.insertRow(-1);this._appendSortHeader(a,l.areaCol,0,{"class":"OneVarMultiComparison_TextColumnHeader"});this._appendSortHeader(a,l.valueCol,1,{"class":"OneVarMultiComparison_ValueColumnHeader"});h.set(a.insertCell(-1),"class","OneVarMultiComparison_ChartColumnHeader_Lower");h.set(a.insertCell(-1),"class","OneVarMultiComparison_ChartColumnHeader_Upper");this.autoHeight&&d.contentClass.push("OneVarMultiComparison_Expanded_ContentPane");
d.addFooter("div")},_canCreateValueBlock:function(){return!0},updateUIExpanded:function(){this.inherited(arguments);var d=this._calculate().firstCol,f=[],a;if(d){var g=[],e=this.data.features.length;for(a=0;a<e;a++){var c=[];f.length&&!this._isSiteRowFeature(this.data.features[a])||f.push(c);c.push(this.getFeatureTitle(a));c.push(this.getValueByName(a,d.name));g.push(c)}this.site&&(this.site.innerHTML=l.subtitleSite2);this._sortRows(g);var b=this.getValueByName(0,d.name);if(c=u.isNumber(b)){var k=
this.getValueByName(e-1,d.name);a=this.getFeatureTitle(e-1);e=1-k/b;.005>Math.abs(e)&&(e=0);e=0>e?this._getLessThanPattern():0<e?this._getMoreThanPattern():this._getSamePattern();this.comp&&(this.comp.innerHTML=w.substitute(e,{site:a}))}else this.comp&&(this.comp.innerHTML="");e=this.table;for(k=g.length+1;1<e.rows.length;)e.deleteRow(-1);b=e.rows[0];if(c)for(;4>b.cells.length;)b.insertCell(-1);else for(;2<b.cells.length;)n.destroy(b.cells[b.cells.length-1]);for(a=1;a<k;a++)b=e.insertRow(-1),0===
a%2&&0<a&&(b.className="AlternatingRow"),h.set(b.insertCell(-1),"class","OneVarMultiComparison_TextColumn"),h.set(b.insertCell(-1),"class","OneVarMultiComparison_ValueColumn"),c&&(b=h.set(b.insertCell(-1),"class","OneVarMultiComparison_ChartColumn"),h.set(b,"colspan","2"));k=Number.NEGATIVE_INFINITY;if(c){for(a=0;a<g.length;a++)g[a][1]>k&&(k=g[a][1]);k=y.getCeiling(k);e.rows[0].cells[2].innerHTML=p(d,0);e.rows[0].cells[3].innerHTML=p(d,k)}for(a=0;a<g.length;a++)if(b=e.rows[a+1],b.cells[0].innerHTML=
g[a][0],b.cells[1].innerHTML=p(d,g[a][1]),c){var t;-1!==f.indexOf(g[a])?(m.remove(b,"OneVarMultiComparison_Row"),m.add(b,"OneVarMultiComparison_CurrentRow"),t="OneVarMultiComparison_Expanded_CurrentBar"):(m.remove(b,"OneVarMultiComparison_CurrentRow"),m.add(b,"OneVarMultiComparison_Row"),t="OneVarMultiComparison_Expanded_Bar");var q=r.pct(g[a][1]/k);b.cells[2].innerHTML="\x3cdiv class\x3d'"+t+"' style\x3d'width:"+q+"' /\x3e";h.set(b.cells[0],"style","width:50%");h.set(b.cells[1],"style","width:20%")}else h.set(b.cells[0],
"style","width:50%"),h.set(b.cells[1],"style","width:50%")}},updateUICollapsed:function(){this.inherited(arguments);var d=this._calculate().firstCol,f=[],a;if(d){var g=[],e=this.data.features.length;for(a=0;a<e;a++){var c=[];f.length&&!this._isSiteRowFeature(this.data.features[a])||f.push(c);c.push(this.getFeatureTitle(a));c.push(this.getValueByName(a,d.name));g.push(c)}this._sortRows(g);var c=this.getValueByName(0,d.name),e=this.table,b=g.length+1;for(a=e.rows.length;a<b;a++){var k=e.insertRow(-1);
0===a%2&&(k.className="AlternatingRow");h.set(k.insertCell(-1),"class","OneVarMultiComparison_TextColumn");h.set(k.insertCell(-1),"class","OneVarMultiComparison_ValueColumn")}for(;e.rows.length>b;)e.deleteRow(-1);a=u.isNumber(c);c=v("col",this.table);a?(h.set(c[0],"style","width:70%"),h.set(c[1],"style","width:30%")):(h.set(c[0],"style","width:50%"),h.set(c[1],"style","width:50%"));for(a=0;a<g.length;a++)c=e.rows[a+1],c.cells[0].innerHTML=g[a][0],c.cells[1].innerHTML=p(d,g[a][1]),-1!==f.indexOf(g[a])?
(m.remove(c,"OneVarMultiComparison_Row"),m.add(c,"OneVarMultiComparison_CurrentRow")):(m.remove(c,"OneVarMultiComparison_CurrentRow"),m.add(c,"OneVarMultiComparison_Row"))}},_calculate:function(){var d=this.getDataFields(),f=this.getFieldByIndex(d[0]);this.primary&&(this.primary.innerHTML=this.formatByIndex(0,d[0])+" ");return{firstCol:f}},_getLessThanPattern:function(){return l.lessThan},_getMoreThanPattern:function(){return l.moreThan},_getSamePattern:function(){return l.same},_isSiteRowFeature:function(d){return!1}})});