// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/std/StdPolygonsController","dojo/_base/declare esri/dijit/geoenrichment/Deferred dojo/on esri/dijit/geoenrichment/promise/all dijit/Destroyable ../../MapEventUtil esri/dijit/geoenrichment/ReportPlayer/countryConfig".split(" "),function(f,g,h,k,l,m,n){return f(l,{_calculatorName:null,_hasRegisteredLayers:!1,_hasRegisteredInfographics:!1,constructor:function(a){this._calculatorName=a;this._layerIndexes={};this._rendererJsons=
{};this._labelRendererJsons={};this._mapInfos={};this._graphicLayerInfos={};this._pendingLayerInfos={}},getCalculatorName:function(){return this._calculatorName},_rendererJsons:null,_labelRendererJsons:null,getRendererJson:function(a){return this._rendererJsons[a]},getLabelRendererJson:function(a){return this._labelRendererJsons[a]},setRendererJson:function(a,b){this._rendererJsons[a]=b},setLabelRendererJson:function(a,b){this._labelRendererJsons[a]=b},_layerIndexes:null,getLayerIndex:function(a,
b){var c=n.getGeographiesModel().getLevels(),d=-1;c.some(function(a,c){if(a.id===b)return d=c,!0});return this._layerIndexes[a]+d/c.length},setLayerIndex:function(a,b){this._layerIndexes[a]=b},_mapInfos:null,getMapInfo:function(a){return this._mapInfos[a]},getMapInfos:function(){var a=[],b;for(b in this._mapInfos)a.push(this._mapInfos[b]);return a},setMapInfo:function(a,b){this._mapInfos[a]=b},_attributeFields:null,getAttributeFields:function(){return this._attributeFields},setAttributeFields:function(a){this._attributeFields=
a},_shownFeatureAttributes:null,_featuresChangedHandlers:null,getShownFeatureAttributes:function(){return this._shownFeatureAttributes},setShownFeaturesChangedListener:function(a){var b=this;this._featuresChangedHandlers=this._featuresChangedHandlers||[];this._featuresChangedHandlers.push(a);return{remove:function(){var c=b._featuresChangedHandlers;c&&c.splice(c.indexOf(a),1)}}},setShownFeatureAttributes:function(a){this._shownFeatureAttributes=a;this._featuresChangedHandlers&&this._featuresChangedHandlers.forEach(function(a){a()})},
_allFeatureAttributes:null,_loadAllFeaturesHandlers:null,getAllFeatureAttributes:function(){return this._allFeatureAttributes||[]},setAllFeatureAttributes:function(a){this._allFeatureAttributes=a},setLoadAllFeaturesListener:function(a){var b=this;this._loadAllFeaturesHandlers=this._loadAllFeaturesHandlers||[];this._loadAllFeaturesHandlers.push(a);return{remove:function(){var c=b._loadAllFeaturesHandlers;c&&c.splice(c.indexOf(a),1)}}},loadAllFeatures:function(){return this._loadAllFeaturesHandlers&&
k(this._loadAllFeaturesHandlers.map(function(a){return a()}))},_highlightInfographicForAttributesFunc:null,_registerInfographicDfd:null,registerInfographic:function(a){this._highlightInfographicForAttributesFunc=a.highlightInfographicForAttributes;this._registerInfographicDfd=new g;this._hasRegisteredLayers&&this._registerInfographicDfd.resolve();this._hasRegisteredInfographics||(this._hasRegisteredInfographics=!0,this._doRegisterLayers());return this._registerInfographicDfd.promise},_graphicLayerInfos:null,
_pendingLayerInfos:null,setStdPolygonsLayer:function(a,b,c,d){this._unSetInfo(a);this._pendingLayerInfos[a]={map:c,graphicsLayer:b,getGraphicForAttributesFunc:d.getGraphicForAttributesFunc,setGraphicHighlightedFunc:d.setGraphicHighlightedFunc,layerMouseOverHandle:null,layerMouseOutHandle:null,highlightedGraphic:null};this._hasRegisteredInfographics&&this._doRegisterLayers();this._hasRegisteredLayers||(this._hasRegisteredLayers=!0,this._registerInfographicDfd&&this._registerInfographicDfd.resolve())},
_doRegisterLayers:function(){for(var a in this._pendingLayerInfos){var b=this._pendingLayerInfos[a];this._graphicLayerInfos[a]=b;this._addLayerListeners(b)}this._pendingLayerInfos={}},_addLayerListeners:function(a){var b=this,c=a.graphicsLayer,d;a.layerMouseOverHandle=m.onLayerMouseOver(c,a.map,function(e){e.graphic&&e.graphic._graphicsLayer===c&&d!==e.graphic&&(a.layerMouseOutHandle&&a.layerMouseOutHandle.remove(),a.layerMouseOutHandle=null,d&&a.setGraphicHighlightedFunc(d,!1),d=e.graphic,b._highlightInfographicForAttributesFunc(d.attributes),
a.setGraphicHighlightedFunc(d,!0),a.layerMouseOutHandle=h.once(c,"mouse-out",function(c){b._highlightInfographicForAttributesFunc(null);d&&a.setGraphicHighlightedFunc(d,!1);d=null}))})},highlightGraphicForAttributes:function(a){for(var b in this._graphicLayerInfos){var c=this._graphicLayerInfos[b];c.highlightedGraphic&&(c.setGraphicHighlightedFunc(c.highlightedGraphic,!1),c.highlightedGraphic=null);if(a){var d=c.getGraphicForAttributesFunc(a);d&&(c.setGraphicHighlightedFunc(d,!0),c.highlightedGraphic=
d)}}},_unSetInfo:function(a){var b=this._graphicLayerInfos[a];delete this._graphicLayerInfos[a];b&&(b.layerMouseOverHandle&&b.layerMouseOverHandle.remove(),b.layerMouseOutHandle&&b.layerMouseOutHandle.remove())},_unSetLayers:function(){Object.keys(this._graphicLayerInfos).forEach(this._unSetInfo.bind(this));this._graphicLayerInfos={}},destroy:function(){this._unSetLayers()}})});