// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/round/_RoundChartSeriesCalculator","../../ThemeCalculator ../../ChartTypes ../../ChartSorting ../../ChartLineStyles ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../../../sections/dynamicSettings/supportClasses/FilterUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder esri/dijit/geoenrichment/utils/ColorUtil dojo/i18n!esri/nls/jsapi".split(" "),function(z,r,k,t,x,A,u,B,y,D){var C={calcLineStyle:function(a,
e){return{color:y.getColorWithAlpha(e.outlineColor||a,e.outlineOpacity),width:e.outlineThickness||0,style:t.toGFXValue(e.outlineStyle||t.SOLID)}}};return{calcSeries:function(a){var e=a.seriesItems,l=a.chartType,n=a.themeSettings,d=a.visualProperties,m=a.sorting;if(!e.length)return[];var p=e[0],f=[],q={name:"data",data:[]};f.push(q);if(!p.points.length)return f;var h=this._calcStats(a);p.points.forEach(function(a,b){if(!a.hidden){var g=h.values[b],f=g.value,m=f||0,c;r.isConditionalStylingSupported(l)&&
d.conditionalStyling&&(c=(c=x.getConditionalStyle(g.isBenchmarked?g.ownValue:m,d.conditionalStyling))&&c.backgroundColor);c=c||z.calcColorForPoint({point:a,seriesItem:p,pointIndex:b,seriesIndex:0,numSeries:e.length,chartType:l,themeSettings:n});var w=C.calcLineStyle(c,d);c=1>d.fillOpacity?y.getColorWithAlpha(c,d.fillOpacity):c;b={originalValue:f,x:1,y:r.supportsNegativeValues(l)?m:Math.max(1E-4,m),isUnavailableData:isNaN(f),valueProp:"y",unsortedIndex:b,name:a.label,point:a,fill:c,valuesSumsInSeries:h.absValuesSum,
seriesIndex:0,stroke:{color:w.color,width:w.width,style:w.style},isBenchmarked:g.isBenchmarked,unbenchmarkedValue:g.ownValue,unbenchmarkedValuesSumsInSeries:h.unbenchmarkedAbsValuesSum};a=B.getTooltipInfo({yValue:f,pointLabel:a.label,seriesLabel:null,minInSeriesValue:h.minValue,maxInSeriesValue:h.maxValue,sumInSeriesValue:h.valuesSum,absSumInSeriesValue:h.absValuesSum,avgInSeriesValue:h.avgValue,visualProperties:d,chartType:l,conditionalStyling:d.conditionalStyling,fieldInfo:a.fieldInfo,decimals:a.value&&
a.value.decimals,fill:b.fill,stroke:0<b.stroke.width?b.stroke.color:void 0,isBenchmarked:g.isBenchmarked,unbenchmarkedValue:g.ownValue});b.tooltip=a;q.data.push(b)}});r.isSortingSupported(l)&&m&&m!==k.NONE&&q.data.sort(function(a,d){return(a.y-d.y)*(m===k.DESC?-1:1)});return f},_calcStats:function(a){var e=a.seriesItems[0],l=a.chartType,n=a.viewModel,d=a.visualProperties,m=a.currentFeatureIndex,p=[],f=0,q=0,h=0,v=1E6,b=-1E6;a=e.points;var g;if(d.filter&&d.filter.ranges)g=u.getChartData({filterRangesStats:A.getRangeStatistics(d.filter.ranges),
numPoints:a.length});else if(r.isConditionalStylingSupported(l)&&d.conditionalStyling){var k=x.getStatistics(d.conditionalStyling);k&&e&&(g=u.getChartData({conditionalStats:k,numPoints:a.length}))}var t=0;a.forEach(function(a,e){var c=function(){if(a.hidden)return{value:void 0};var c=u.getPointValue({point:a,index:e,seriesIndex:0,maxValue:!1,chartType:l,visualProperties:d,viewModel:n,currentFeatureIndex:m,chartData:g}),b=n.getBenchmarkController&&n.getBenchmarkController();return r.isBenchmarkSupported(l)&&
b&&0<=b.getAreaIndex()&&b.getAreaIndex()!==m?(b=u.getPointValue({point:a,index:e,seriesIndex:0,maxValue:!1,chartType:l,visualProperties:d,viewModel:n,currentFeatureIndex:b.getAreaIndex(),chartData:g}),{value:c-b,isBenchmarked:!0,ownValue:c}):{value:c}}();p[e]=c;var k=c.value||0;a.hidden||(t++,f+=k,q+=Math.abs(k),h+=Math.abs(c.ownValue||0),v=Math.min(v,k),b=Math.max(b,k))});return{values:p,valuesSum:f,absValuesSum:q,unbenchmarkedAbsValuesSum:h,minValue:v,maxValue:b,avgValue:f/t}}}});