// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/WebMapsUtil","dojo/_base/lang dojo/_base/Deferred esri/dijit/geoenrichment/when esri/kernel esri/arcgis/utils esri/geometry/Extent esri/request esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(g,q,m,v,n,t,w,p){var f={};p.isPageRunOnWebService()||(v.id.getCredential=function(){var a=new q;a.reject(Error("Can't get credentials"));return a});var u={_itemsCache:{},_siCache:{},loadItem:function(a){this._itemsCache[a]||(this._itemsCache[a]=
n.getItem(a));return m(this._itemsCache[a],function(a){return a&&g.clone(a)})},loadServiceInfo:function(a,e){this._siCache[a]||(this._siCache[a]=e({url:a,content:{f:"json"}}));return this._siCache[a]}};f.getItem=function(a){return u.loadItem(a)};f.isWebMapType=function(a){return a&&"Web Map"===a.type};f.createMap=function(a,e,b){b=b||{};if(a&&a.item)return f.isWebMapType(a.item)&&b.additionalLayerInfos&&f._addAdditionalLayerInfosToOperationalLayers(a.itemData.operationalLayers,b.additionalLayerInfos),
m(!f.isWebMapType(a.item)&&f.createItemDataForNonWebMapItem(a,{defaultBasemapId:b.defaultBasemapId,additionalLayerInfos:b.additionalLayerInfos}),function(){return n.createMap(a,e,{usePopupManager:!0,mapOptions:b.mapOptions||{}})})};f.createItemDataForNonWebMapItem=function(a,e){function b(){d.url=function(c){["FeatureServer","MapServer","ImageServer"].some(function(a){if(-1!==c.indexOf(a))return c=c.substr(0,c.lastIndexOf(a)+a.length),!0});return c}(d.url);var c=e.requestFunc||w;p.registerCORS(d.url);
return u.loadServiceInfo(d.url,c).then(function(c){return m(function(c,a){c.extent||(a=a.initialExtent||a.fullExtent||a.extent,!a||a instanceof t||(a=new t(a)),c.extent=a)}(d,c),function(){return c})})}function h(c){a.itemData={baseMap:null,operationalLayers:c};e.additionalLayerInfos&&f._addAdditionalLayerInfosToOperationalLayers(c,e.additionalLayerInfos);return m(!1!==e.defaultBasemapId&&f.provideDefaultBaseMapForItemData(a.itemData,e),function(){return a})}function n(c,a){return-1!==c.indexOf(a)?
c.substr(c.lastIndexOf(a)+a.length,c.length):null}function r(c,a){var b=c.id;return{url:p.combine(d.url,b),capabilities:a.capabilities||"Query",id:a.idPrefix+b,visibility:a.visibility||c.defaultVisibility,mode:1,title:c.title,description:c.description}}e=e||{};var d=a.item,k=a.itemData;if("Feature Service"===d.type){var l=n(d.url,"FeatureServer/");return b().then(function(a){var c=[];if(l&&a.layers[l])c.push(r(a.layers[l],{capabilities:a.capabilities,idPrefix:"featureServiceLayer_",visibility:!0}));
else for(var b=0;b<a.layers.length;b++)c.unshift(r(a.layers[b],{capabilities:a.capabilities,idPrefix:"featureServiceLayer_"}));return h(c)})}if("Map Service"===d.type)return l=n(d.url,"MapServer/"),b().then(function(a){a=l&&a.layers[l]?r(a.layers[l],{capabilities:a.capabilities,idPrefix:"mapServiceLayer_",visibility:!0}):{url:d.url,id:"mapServiceLayer01",visibility:!0,title:a.title};a=[g.mixin(a,{opacity:1},k)];return h(a)});if("Image Service"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,
id:"imageServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("Vector Tile Service"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"vectorTileServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMSServer"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"wmsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMTS"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"wmtsLayer01",visibility:!0,opacity:1,
title:a.title},k)];return h(a)});if("WFS"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"wfsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("KML"===d.type){p.registerCORS(d.url);var q=[g.mixin({url:d.url,id:"kmlLayer01",visibility:!0,opacity:1,title:"KML Layer",type:"KML"},k)];return h(q)}};f.provideDefaultBaseMapForItemData=function(a,e){e=e||{};if(!a.baseMap)return m(function(){var a={title:"My basemap",baseMapLayers:[{id:"basemapLayer01",opacity:e.hideBasemap?
0:1,visibility:!e.hideBasemap,url:"http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer"}]};return e.defaultBasemapId?f.getItem(e.defaultBasemapId).then(function(b){return b&&b.itemData&&b.itemData.baseMap||a}):a}(),function(b){a.baseMap=b;return a})};f._addAdditionalLayerInfosToOperationalLayers=function(a,e){e.forEach(function(b,e){a.push({url:b.url,id:"additionalLayer"+e,visibility:!0,opacity:1})})};return f});