// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/tasks/EnrichAreasTask","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all esri/kernel esri/SpatialReference esri/tasks/FeatureSet ../GEUtil ../areas/AnalysisAreaUtil ./parsers/FeatureSetParser ../../../core/supportClasses/map/Projector esri/dijit/geoenrichment/utils/CoordinateUtil".split(" "),function(t,h,e,n,p,l,u,v,q,w,x,m){function r(a){return(a=a&&p.id.findCredential(a)||
p.id.credentials[0])&&a.token}return t(null,{enrichAreas:function(a){var b={};return e(this._analysisAreasToStudyAreas(a.analysisAreas,a.countryID,a.comparisonLevels),function(c){b.studyAreas=c;a.report?b.analysisVariables=[{itemid:a.report.reportID,url:a.report.portalUrl,token:r(a.portalUrl),outFields:["*"]}]:a.fields&&(b.analysisVariables=a.fields);return this._doRunTask(b,a,"enrich")}.bind(this)).then(this._handleFeatureSetsRequest.bind(this))},createReport:function(a){var b={f:"bin",format:"xml",
reportfields:{}};b.report={itemid:a.report.reportID,url:a.report.portalUrl,token:r(a.portalUrl)};return e(this._analysisAreasToStudyAreas(a.analysisAreas,a.countryID,null),function(c){b.studyAreas=c;return this._doRunTask(b,a,"createReport")}.bind(this))},_analysisAreasToStudyAreas:function(a,b,c){var k=this;c=c&&c.map(function(a){return{layer:a}});return n(a.map(function(a,g){var d;d=a.geographies&&a.geographies.length?k._studyAreaFromGeographies(a.geographies,b,!0):{attributes:h.mixin({},a.feature.attributes),
geometry:a.feature.geometry.toJson()};c&&(d.comparisonLevels=c);return e(k._getStorePointForArea(a),function(a){d.attributes=d.attributes||{};a&&(d.attributes.STORE_LAT=d.attributes.STORE_LAT||a.STORE_LAT,d.attributes.STORE_LONG=d.attributes.STORE_LONG||a.STORE_LONG);d.attributes.STORE_ID=g+"";w.ID_FIELDS.forEach(function(a){delete d.attributes[a]});return d})}))},_getStorePointForArea:function(a){if(a.location){var b=q.geometryToLatLong(a.location.geometry);return b?b:e(x.projectGeometries(a.location.geometry,
new l(m.WGS_84_WKID)),function(a){return q.geometryToLatLong(a)})}},createFeatureForGeographies:function(a,b){return this._createFeaturesForGeographies(a,b,!0).then(function(a){return a[0]})},createFeaturesForGeographies:function(a,b){return this._createFeaturesForGeographies(a,b,!1)},_createFeaturesForGeographies:function(a,b,c){a={returnGeometry:!0,outSR:b.outSR||new l(m.WEB_MERCATOR_WKID),studyAreas:c?[this._studyAreaFromGeographies(a,b.countryID,!0,b.generalizationLevel)]:a.map(function(a){return this._studyAreaFromGeographies([a],
b.countryID,!1,b.generalizationLevel)},this),dataCollections:["GlobalIntersect"]};return this._doRunTask(a,b,"enrich").then(this._handleFeatureSetsRequest.bind(this))},_studyAreaFromGeographies:function(a,b,c,k){var f={sourceCountry:b,layer:null,ids:null},g=null,d=[],e;a.forEach(function(a){if(!a||!a.id)throw Error("Wrong geography.");var b=a.levelId;if(b)if(!g)g=b;else if(c&&g!==b)throw Error("Geographies have different level IDs.");d.push(a.id);a.sourceCountry&&(f.sourceCountry=a.sourceCountry);
a.hierarchy&&(f.hierarchy=a.hierarchy);a.attributes&&(e=h.mixin(e||{},a.attributes))});f.layer=g;f.ids=c?[d.join(",")]:d;f.attributes=e;f.generalizationlevel=k;return f},createFeaturesForBuffer:function(a,b){b=b||{};var c={bufferUnits:a.units,bufferRadii:a.radii||[a.radius],areaType:a.areaType||"RingBuffer"};"NetworkServiceArea"===c.areaType&&(c.travelMode=a.travelMode,c.networkOptions=a.networkOptions);a=a.point||a.polyline;c={returnGeometry:!0,outSR:b.outSR||a.spatialReference||new l(m.WEB_MERCATOR_WKID),
dataCollections:["GlobalIntersect"],studyAreasOptions:c,studyAreas:[{geometry:a.toJson?a.toJson():a}]};return this._doRunTask(c,b,"enrich").then(this._handleFeatureSetsRequest.bind(this))},createFeaturesForBuffers:function(a,b){var c={},e=[];a.forEach(function(a){var b;b=a.point||a.polyline;b=JSON.stringify(b.toJson?b.toJson():b)+";"+a.units+";"+a.areaType+";"+a.travelMode+";"+JSON.stringify(a.networkOptions);var d=c[b];d||(d=c[b]=h.clone(a),delete d.radius,d.radii=[],e.push(d));a.radii?d.radii=d.radii.concat(a.radii):
d.radii.push(a.radius)});return n(e.map(function(a){return this.createFeaturesForBuffer(a,b)},this)).then(function(a){var b=[];a.forEach(function(a){b=b.concat(a)});return b})},_doRunTask:function(a,b,c){a=h.mixin({useData:{sourceCountry:b.countryID,hierarchy:b.hierarchy||"census"},forStorage:!1},a);return v[c](a)},_handleFeatureSetsRequest:function(a){return(new u(a[0])).features}})});