// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/dataDrilling/DataDrillingLibrary","dojo/_base/lang ./_FieldInfoBuilder ../../../supportClasses/tableJson/TableJsonUtil ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoNameUtil ../../../../dataProvider/supportClasses/dataCollections/DataCollectionsLoader ./_config ./EnrichUtil".split(" "),function(h,u,v,w,q,g,m){function r(a){return"string"===typeof a?a.split(",").map(function(a){return a+"/"}):a}var d={};
m.ddLibrary=d;d.getDrillingOptions=function(a,c,b){if(c){var f=function(){function f(a,c){return k&&-1!==k.indexOf(a)?!0:d&&d.some(function(b){return-1!==b.indexOf(a)||-1!==b.indexOf(c)})}if("string"===typeof c){var e=g.getById(a+"."+c);return e?[e]:null}var d=c.usedFields||b&&b(c),d=d&&d.map(function(a){return a.toUpperCase()});if(!c.variableID&&!d)return null;var k=c.variableID&&c.variableID.toUpperCase(),e=g.LIBRARY[a],n;for(n in e){var h=n.toUpperCase(),l=w.createFieldNameFromVariable(n).toUpperCase();
if(f(h,l))return e[n]}return null}();f&&f.forEach(function(a){d._provideStateData(a)});return f}};d.getDrillingOptionByStandardId=function(a,c){};d.getDrillingOptionInfo=function(a,c,b,f,x,e,g){a=(a=d.getDrillingOptions(a,c,g))&&a.filter(function(a){return a.name===b})[0];if(!a)return null;!e&&a.defaultState&&(e=a.defaultState);e=e&&e.charAt(0)||"n";var k;a.calcGroup&&(k=h.clone(a.calcGroup),k.value=e+"/");f=v.createSingleCellTable({fieldInfo:a.stateData[e].fieldInfo,width:f,height:x});return{calculationStatesGroup:k,
tableJson:h.clone(f),enrichInfos:m._getStandardEnrichInfosForTableInfo(a,!0)}};d._provideStateData=function(a){if(!a.stateData){var c=a.states?h.clone(a.fieldInfo):a.fieldInfo;a.stateData={n:{fieldInfo:a.fieldInfo}};a.fieldInfo.isChart&&d._updateChartJsonForState(a.fieldInfo.chartJson,"n",a.stateSettings&&a.stateSettings.n);a.states&&(a.states=r(a.states),a.states.forEach(function(b){b=b.charAt(0);if("n"!==b){var e=h.clone(c);a.stateData[b]={fieldInfo:e};e.isChart&&d._updateChartJsonForState(e.chartJson,
b,a.stateSettings&&a.stateSettings[b])}}),a.calcGroup=d.createCalculationStatesGroup(a.states));for(var b in a.stateData){var f=a.stateData[b];f.fieldInfo.isChart&&f.fieldInfo.chartJson.seriesItems.forEach(function(a){a.points.forEach(function(c){u.provideFieldInfoForChartPoint(c,a,1===f.fieldInfo.chartJson.seriesItems.length,b,f.fieldInfo.chartJson.comparisonInfo&&f.fieldInfo.chartJson.comparisonInfo.calculatorName)})})}delete a.states;delete a.stateSettings;delete a.fieldInfo}};d._updateChartJsonForState=
function(a,c,b){b&&b.title?a.visualProperties.title.text=b&&b.title:"n"!==c&&(a.visualProperties.title.text+=" ("+g.STATE_LOCALIZATION_MAP_SHORT[c]+")");a.visualProperties.yAxis&&(a.visualProperties.yAxis.title=b&&b.yAxisTitle||("n"===c?"":g.STATE_LOCALIZATION_MAP[c]),"i"===c&&(a.visualProperties.yAxis.baseLineValue=100));"n"!==c&&(a.visualProperties.dataLabelsDecimals="p"===c?1:0);"p"===c&&(a.visualProperties.dataLabelsShowValuePercentSymbol=!0,a.visualProperties.yAxis&&(a.visualProperties.yAxis.showPercentSymbol=
!0,a.visualProperties.yAxis.showSymbolForAllLabels=!0));b&&b.isCurrency&&(a.visualProperties.dataLabelsShowValueCurrencySymbol=!0,a.visualProperties.yAxis&&(a.visualProperties.yAxis.showCurrencySymbol=!0,a.visualProperties.yAxis.showSymbolForAllLabels=!0));h.mixin(a.visualProperties,b&&b.visualProps)};d.createCalculationStatesGroup=function(a){if(a)return a=r(a),{states:{ids:a,names:a.slice(),labels:a.map(function(a){return g.STATE_LOCALIZATION_MAP_SHORT[a.charAt(0)]})},value:a[0]}};var l,t,p;d.init=
function(a){if(a&&a.countryID){var c=a.countryID,b=c+";"+(a.hierarchy||"census");if(l&&t===b)return l;t=b;var b=p=p||g.collectSubstitutionVariables(),d={};if(b[c]){if(q.canLoad()){var h=b[c].fields,e=b[c].variables;return l=q.loadVariables({countryID:c,hierarchy:a.hierarchy||"census",outFields:h,forceLowerCase:!0}).then(function(a){var b={fields:h,variables:[]};e.forEach(function(c){var d=a.fullNameToVariableCache[c];d.fullName=c;b.variables.push(d)});d[c]=b}).then(function(){g.replaceSubstitutionVariables(d)})}if(a.variableProvider){var m=
{fields:b[c].fields,variables:[]};d[c]=m;b[c].variables.forEach(function(b){var c=a.variableProvider.getVariableVintage(b);m.variables.push({fullName:b,vintage:c||"N/A"})});g.replaceSubstitutionVariables(d)}}}l=!0};d.getSubstitutionVariables=function(a){return(a=(p=p||g.collectSubstitutionVariables())[a])&&a.variables};return d});