// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.30/esri/copyright.txt for details.
//>>built
define("esri/dijit/analysis/RasterAnalysisMixin","dojo/_base/declare dojo/_base/Deferred dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/store/Memory dojo/promise/all dojo/when dojo/string dojo/has dojo/dom-class dojo/dom-style dojo/dom-attr dojo/dom-construct dijit/Tooltip esri/layers/ArcGISImageServiceLayer ../../kernel ../../lang ../../request ../../symbols/SimpleFillSymbol ../../Color ../../renderers/ClassBreaksRenderer ../../tasks/AlgorithmicColorRamp ../../tasks/MultipartColorRamp ../RasterFunctionEditor/utils ./AnalysisBase ./_AnalysisOptions ./utils ./ItemTypes ./mixins/browselayers/BrowseLayerMixin ../../layers/RasterFunction ../../layers/ArcGISRenderingImageServiceLayer".split(" "),
function(n,w,d,k,u,g,x,y,z,p,A,B,m,C,l,D,E,F,G,q,H,r,I,J,K,L,M,N,h,v,O,t,P){n=n([N,M,O],{declaredClass:"esri.dijit.analysis.RasterAnalysisMixin",map:null,outputLayerName:null,resultParameter:"outputRaster",rasterGPToolName:"GenerateRaster",analysisType:"raster",i18n:null,returnProcessInfo:null,isPPTTool:!1,isDLTool:!1,unsupportedServiceNameCharacters:/[\s~`!#$%\^&*+=\-\[\]\\';,\/{}|\\":<>\?\.]/g,_geometryService:null,_findDeepestArgsForRerun:!1,constructor:function(a,c){this._pbConnects=[];a.containerNode&&
(this.container=a.containerNode)},destroy:function(){this.inherited(arguments);k.forEach(this._pbConnects,u.disconnect);delete this._pbConnects},postMixInProperties:function(){this.inherited(arguments);d.mixin(this.i18n,this.toolNlsName)},postCreate:function(){this.inherited(arguments);B.add(this._form.domNode,"esriSimpleForm");this._outputLayerInput.set("validator",d.hitch(this,this.validateServiceName));this._buildUI()},startup:function(){},validateServiceName:function(a){return h.validateServiceName(a,
{textInput:this._outputLayerInput})},_getJobParameters:function(){},_getRasterFunction:function(){},_getRasterArguments:function(){},_getRasterObject:function(a){a=a||this.get("inputLayer");return L.getRasterJsonFromLayer(a)},_getOutputRasterLayerName:function(){},_getOutputItemProperties:function(){},_setDefaultInputs:function(){},_resetUI:function(){},_getDefaultOutputItemProperties:function(a,c,b){c=this._getDefaultRenderingRule(c);var e=this._getDefaultRenderer(),f=this._getDefaultPopupInfo();
a={visibility:!0,opacity:a||1,interpolation:b||"RSP_NearestNeighbor",popupInfo:f};c&&(a.renderingRule=c);e&&(a.layerDefinition={},a.layerDefinition.drawingInfo={},a.layerDefinition.drawingInfo.renderer=e.toJson());return a},_getDefaultRenderingRule:function(a){var c=new t;c.functionName="Stretch";c.functionArguments={StretchType:5,DRA:!1,Gamma:[1],UseGamma:!0};c.outputPixelType="U8";var b=new t;b.functionName="Colormap";b.functionArguments={colorRamp:a||"Aspect",Raster:c};return b},_getDefaultRenderer:function(){if(this.colorValues&&
this.colorValues.length&&this.classMaxValues&&this.classMaxValues.length&&this.labels&&this.labels.length){var a=this.colorValues.length;if(a===this.classMaxValues.length&&a===this.labels.length){var c=new I({field:"Value",showInAscendingOrder:!0,classificationMethod:"natural-breaks"}),b=new K,e,f,d,g;b.colorRamps=[];for(d=0;d<a;d++)g=this.colorValues[d],e&&(f=new J,f.algorithm="hsv",f.fromColor=new r(e),f.toColor=new r(g),b.colorRamps.push(f)),e=g;b&&(c.authoringInfo={},c.authoringInfo.colorRamp=
b.toJson());b=[];e=-1;for(d=0;d<a;d++)f=this.colorValues[d],f=new H("solid",null,new r({r:f[0],g:f[1],b:f[2],a:f[3]})),b.push({minValue:e,maxValue:this.classMaxValues[d],label:this.labels[d],symbol:f}),e=this.classMaxValues[d];c.infos=b;c.attributeField="Value";return c}}},_getDefaultPopupInfo:function(){return{title:this.get("outputLayerName"),description:null,fieldInfos:[{fieldName:"Raster.ServicePixelValue",label:"Service Pixel Value",isEditable:!1,isEditableOnLayer:!1,visible:!1,format:{places:2,
digitSeparator:!0}},{fieldName:"Raster.ServicePixelValue.Raw",label:"Pixel Value",isEditable:!1,isEditableOnLayer:!1,visible:!0,format:{places:2,digitSeparator:!0}}],showAttachments:!1,layerOptions:{showNoDataRecords:!0,returnTopmostRaster:!0},mediaInfos:[]}},_getReRunRFxArgs:function(a,c){var b={};this._findFunction(a,c,b);return b&&b.rasterFunctionArguments},_findFunction:function(a,c,b){var e=a&&a.rasterFunction,d=this._getRasterFunction();if(e&&b&&"object"===typeof b){if(e===d&&(b.rasterFunction=
a.rasterFunction,b.rasterFunctionArguments=a.rasterFunctionArguments,!c))return;this._findFunction(a.rasterFunctionArguments&&a.rasterFunctionArguments.Raster,c,b)}},_getSelectedLayerIndexFromUI:function(a,c){if(!a||!c)return-1;var b=-1;k.forEach(a,function(a,d){a&&a.label.toLowerCase()===c.toLowerCase()&&(b=d)});return b},_setAnalysisGpServerAttr:function(a){a&&(this.analysisGpServer=a,this.set("toolServiceUrl",this.analysisGpServer+"/"+this.rasterGPToolName))},_setInputLayersAttr:function(a){this.inputLayers=
a},_setInputLayerAttr:function(a){this.inputLayer=a},_getInputLayerAttr:function(){return this.inputLayer},_getOutputLayerNameAttr:function(){this._outputLayerInput&&(this.outputLayerName=this._outputLayerInput.get("value"));return this.outputLayerName},_setOutputLayerNameAttr:function(a){this.outputLayerName=a},_setDisableRunAnalysisAttr:function(a){this._saveBtn.set("disabled",a)},_setDisableExtentAttr:function(a){this._useExtentCheck.set("checked",!a);this._useExtentCheck.set("disabled",a)},_getDisableExtentAttr:function(){this._useExtentCheck.get("disabled")},
_setMapAttr:function(a){this.map=a},_getMapAttr:function(){return this.map},_setModelsAttr:function(a){this.models=a},_handleModeCrumbClick:function(a){a.preventDefault();this._onClose(!0)},_onClose:function(a){this._removePointLayer();a&&(this._save(),this.emit("save",{save:!0}));this.removePreviewLayerFromMap();this.emit("close",{save:!a})},_removePointLayer:function(){this.drawnPointLayer&&(this._removeLayer(this.drawnPointLayer,this.inputLayers,this._analysisSelect),this._sourceDrawBtn.deactivate())},
_removeLayer:function(a,c,b){this.map.removeLayer(a);k.forEach(c,function(e,d){e===a&&(b.removeOption({value:d+1,label:c.name}),c.splice(d,1))},this)},_save:function(){},_handleShowCreditsClick:function(a){a.preventDefault();a={};this._form.validate()&&(a.inputLayer=g.toJson(h.constructAnalysisInputLyrObj(this.get("inputLayer"))),a[this.outputName]=g.toJson({serviceProperties:{name:this.get("outputLayerName")}}),this.secondaryOutputNames&&d.mixin(a,this.updateSecondaryOutputNames()),this.showChooseExtent&&
this._useExtentCheck.get("checked")&&(a.context=g.toJson({extent:this.map.extent._normalize(!0)})),this.getCreditsEstimate(this.toolName,a).then(d.hitch(this,function(a){this._usageForm.set("content",a);this._usageDialog.show()})))},updateSecondaryOutputNames:function(){var a={};k.forEach(this.secondaryOutputNames,d.hitch(this,function(c){this.get(c)&&(a[c]=g.toJson({serviceProperties:{name:this.get(c).replace(this.unsupportedServiceNameCharacters,"_")}}))}));return a},_validateRFT:function(a){if(a){var c=
!1,b=this.analysisGpServer.replace("RasterAnalysisTools/GPServer","RasterRendering/ImageServer/validate");a={renderingRule:a,f:"json"};this._previewBtnTooltip||(this._previewBtnTooltip=new D({connectId:[this.esriAnalysisPreviewError,this.esriAnalysisPreviewWarning],label:this.i18n.previewError}));return q({url:b,content:a,load:d.hitch(this,function(a){a&&a.renderingRule&&a.renderingRule.isValid&&(c=!0);return c})})}},onValidRFT:function(){this._previewBtnTooltip.label="";this._previewBtn.checked=
!0;this.removePreviewErrors()},onInvalidRFT:function(){this._previewBtnTooltip.label="\x3cdiv class\x3d'esriAnalysisPreviewErrorToolTip'\x3e"+this.i18n.previewError+"\x3c/div\x3e";this._previewBtn.checked=!1;this.esriAnalysisPreviewWarning.style.display="none";this.esriAnalysisPreviewError.style.display="block";this.onPreviewLoad()},handleExportImageFailure:function(){this._previewBtnTooltip.label="\x3cdiv class\x3d'esriAnalysisPreviewErrorToolTip'\x3e"+this.i18n.previewWarning+"\x3c/div\x3e";this.esriAnalysisPreviewError.style.display=
"none";this.esriAnalysisPreviewWarning.style.display="block";this.onPreviewLoad()},onPreviewLoad:function(){this.esriAnalysisPreviewLoading.style.display="none"},removePreviewErrors:function(){this.esriAnalysisPreviewError.style.display="none";this.esriAnalysisPreviewWarning.style.display="none"},_handlePreviewBtnClick:function(a){this._form.validate()&&(this._preview?(this._preview=!this._preview,this.onPreviewLoad(),this.removePreviewErrors(),this.removePreviewLayerFromMap()):(this.removePreviewErrors(),
this.esriAnalysisPreviewLoading.style.display="block",this._validateRFT(this._getRenderingRule()).then(d.hitch(this,function(a){if(this._preview=a)this.onValidRFT(),this._showPreview();else this.onInvalidRFT()}))))},updatePreview:function(){this._preview&&(this.removePreviewErrors(),this._showPreview())},_showPreview:function(){var a=this._getRenderingRule();this.esriAnalysisPreviewLoading.style.display="block";this._addPreviewLayerToMap(a)},_addPreviewLayerToMap:function(a){this.previewLayer&&this.removePreviewLayerFromMap();
var c=this.analysisGpServer.replace("RasterAnalysisTools/GPServer","RasterRendering/ImageServer"),b=new P(c,{raster:a,type:"rft"}),e=d.hitch(this,function(a){this.previewLayer=a;this.map.addLayer(this.previewLayer);this.onValidRFT()});b.loaded?e(b):(b.on("load",function(){e(b)}),b.on("error",d.hitch(this,function(){if(this.previewLayer)this.previewLayer.updating||this.handleExportImageFailure();else this.onInvalidRFT()})),b.on("update-end",d.hitch(this,function(){this.onPreviewLoad();this.onValidRFT()})),
b.on("update-start",d.hitch(this,function(){this.onValidRFT();this.esriAnalysisPreviewLoading.style.display="block"})))},removePreviewLayerFromMap:function(){this.previewLayer&&(this.map.removeLayer(this.previewLayer),this.previewLayer=void 0)},_getRenderingRule:function(){var a={},c={};this._useRFT?a=this._getRasterFunction():(a.rasterFunction=this._getRasterFunction(),a.rasterFunctionArguments=this._getRasterArguments());return c=g.toJson(a)},_handleSaveBtnClick:function(a){this._form.validate()&&
(a=this.secondaryOutputNames?this._validateSecondaryOutputNames():"done",z(a,d.hitch(this,function(){this._saveBtn.set("disabled",!0);var a=this._webLayerTypeSelect.get("value"),b={},e=this._getJobParameters();if(!G.isDefined(e)){e={};e.rasterFunction=this._getRenderingRule();var f=this._getRasterObject();f&&!this._useRFT&&(e.functionArguments=g.toJson({raster:f}))}e[this.outputName]=g.toJson({serviceProperties:{name:this.get("outputLayerName")}});this.secondaryOutputNames&&d.mixin(e,this.updateSecondaryOutputNames());
e.returnProcessInfo=this.returnProcessInfo;f={};this.showChooseExtent&&!this.get("disableExtent")&&this._useExtentCheck.get("checked")&&(f.extent=this.map.extent._normalize(!0));e.context=g.toJson(f);b.jobParams=e;if("permanentLayer"===a){b.itemParams={description:this.i18n.itemDescription,tags:p.substitute(this.i18n.itemTags,{layername:this.inputLayer&&this.inputLayer.name,fieldname:e.field||"",valuelayername:e.valuelayername||""}),snippet:this.i18n.itemSnippet};if(a=this._getOutputItemProperties())b.itemParams.text=
a;this.showSelectFolder&&(b.itemParams.folder=this.get("folderId"));b.analysisType=this.analysisType;this.execute(b)}else"dynamicLayer"===a&&this._handleSaveDynamicLayer(e)})))},_handleSaveDynamicLayer:function(a){this.get("inputLayer");this.analysisGpServer.replace("RasterAnalysisTools/GPServer","RasterRendering/ImageServer?viewId\x3d");g.fromJson(a[this.outputName]);a=new t;a.functionName=this._getRasterFunction();a.functionArguments=this._getRasterArguments()},_handleAnalysisLayerChange:function(a){if("browselayers"===
a||"browse"===a){this._isAnalysisSelect=!0;this.browseType&&(this.defaultItemTypes=[],this.set("allowedItemTypes",this.browseType));var c={geometryTypes:this.checkGeometries,tags:this.tags,customCheck:this.hasCustomCheck?{customCheckHandler:d.hitch(this,this.isValidInputLayer),customCheckFailureMessage:this.customCheckFailureMessage}:void 0};this._createBrowseItems(this.getOptionsForRasterBrowseItems(a),c,this._analysisSelect)}else this.inputLayer=this.inputLayers[a],this._updateAnalysisLayerUI(!0)},
addPointAnalysisLayer:function(){this._sourceDrawBtn&&(this._sourceDrawBtn.set("map",this.map),this._sourceDrawBtn.on("change",d.hitch(this,this._handleAnalysisPointSelectLayer)))},_handleAnalysisPointSelectLayer:function(a){this.inputLayers&&0!==this.inputLayers.length&&-1!==this.inputLayers.indexOf(a)||(this.drawnPointLayer=a,this.inputLayers.push(a),this.inputLayer=a,this._analysisSelect.removeOption(this._analysisSelect.getOptions()),h.populateAnalysisLayers(this,"inputLayer","inputLayers"),this._updateAnalysisLayerUI(!0))},
_updateAnalysisLayerUI:function(a){"ApplyRFxTemplate"===this.toolName&&(a&&(this.outputLayerName=this._getOutputRasterLayerName()),this._outputLayerInput.set("value",this.outputLayerName));this.inputLayer&&(this._interpolateToolDescription&&C.set(this._interpolateToolDescription,"innerHTML",p.substitute(this.i18n.toolDefine,{layername:this.inputLayer.name})),a&&(this.outputLayerName=this._getOutputRasterLayerName()||p.substitute(this.i18n.outputLayerName,{layername:this.inputLayer.name})),this._outputLayerInput.set("value",
this.outputLayerName));this._resetUI()},_handleBrowseItemsSelect:function(a,c){a&&a.selection&&h.addAnalysisReadyLayer({item:a.selection,layers:this.inputLayers,layersSelect:this._analysisSelect,browseDialog:this._browseLyrsdlg,widget:this},c).always(d.hitch(this,this._updateAnalysisLayerUI,!0))},_handleModelChange:function(a){this.model.itemId!==a&&(this.model.itemId=a,this._queryModelArguments(a))},_queryModelArguments:function(a){var c=this._toolServiceUrl;a={model:g.toJson({url:this.portalUrl+
"/sharing/content/items/"+a}),context:{f:"json"}};this.set("toolServiceUrl",this.analysisGpServer+"/QueryDeepLearningModelInfo");this._modelArguments.innerHTML="";m.set(this._queryModelArgsMsg,"display","table-row");this.gp.submitJob(a,d.hitch(this,function(a){this.gp.getResultData(a.jobId,"outModelInfo",d.hitch(this,function(a){this.set("toolServiceUrl",c);m.set(this._queryModelArgsMsg,"display","none");a&&a.value&&a.value.modelInfo&&(a=g.fromJson(a.value.modelInfo).ParameterInfo)&&0<a.length&&this._loadModelArguments(a)}))}))},
_loadModelArguments:function(a){var c=[],b=l.toDom("\x3ctr\x3e\x3ctd colspan\x3d'2' style\x3d'width:50%'\x3e\x3clabel\x3e"+this.i18n.nameLabel+"\x3c/label\x3e\x3c/td\x3e\x3ctd style\x3d'width:50%'\x3e\x3clabel\x3e"+this.i18n.valueLabel+"\x3c/td\x3e\x3c/tr\x3e");l.place(b,this._modelArguments);k.forEach(a,d.hitch(this,function(a){var b=a.name;0>["raster","model","device"].indexOf(b.toLowerCase())&&(a=l.toDom("\x3ctr\x3e\x3ctd colspan\x3d'2' style\x3d'width:50%'\x3e\x3clabel\x3e"+b+"\x3c/label\x3e\x3c/td\x3e\x3ctd style\x3d'width:50%'\x3e\x3cdiv\x3e\x3cinput type\x3d'text' data-dojo-type\x3d'dijit/form/NumberTextBox' data-dojo-props\x3d'intermediateChanges:true' style\x3d'width:100%;text-align:right' value\x3d'"+
a.value+"'\x3e\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e"),l.place(a,this._modelArguments),c.push(a))}));this.modelArgumentRows=c},_updateModelArguments:function(a){var c=[],b=l.toDom("\x3ctr\x3e\x3ctd colspan\x3d'2' style\x3d'width:50%'\x3e\x3clabel\x3e"+this.i18n.nameLabel+"\x3c/label\x3e\x3c/td\x3e\x3ctd style\x3d'width:50%'\x3e\x3clabel\x3e"+this.i18n.valueLabel+"\x3c/td\x3e\x3c/tr\x3e");l.place(b,this._modelArguments);for(var d in a)b=l.toDom("\x3ctr\x3e\x3ctd colspan\x3d'2' style\x3d'width:50%'\x3e\x3clabel\x3e"+
d+"\x3c/label\x3e\x3c/td\x3e\x3ctd style\x3d'width:50%'\x3e\x3cdiv\x3e\x3cinput type\x3d'text' data-dojo-type\x3d'dijit/form/NumberTextBox' data-dojo-props\x3d'intermediateChanges:true' style\x3d'width:100%;text-align:right' value\x3d'"+a[d]+"'\x3e\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e"),l.place(b,this._modelArguments),c.push(b);this.modelArgumentRows=c},_validateSecondaryOutputNames:function(a){var c=new w;this.getUserProfile().then(d.hitch(this,function(a){var b=[],f=!0,g=this.portalUrl+"/sharing/rest/portals/"+
a.orgId+"/isServiceNameAvailable";k.forEach(this.secondaryOutputNames,d.hitch(this,function(a){this.get(a)&&(a={name:this.get(a).replace(this.unsupportedServiceNameCharacters,"_"),type:"Image Service",f:"json"},b.push(q({url:g,content:a})))}));y(b).then(d.hitch(this,function(a){k.forEach(a,d.hitch(this,function(a,b){a.available||(f=!1,this.emit("job-fail",{message:this.i18n.servNameExists,type:"warning",messageCode:"AB_0002"}),c.reject())}));f&&c.resolve()}))}));return c.promise},_buildUI:function(){var a=
!0;this._loadConnections();this.isPPFTool=-1!=="ClassifyPixelsUsingDeepLearning DetectObjectsUsingDeepLearning CalculateSlope DeriveAspect MonitorVegetation ApplyRFxTemplate RemapValues ExtractRaster".split(" ").indexOf(this.toolName);this.isDLTool=-1!==["ClassifyPixelsUsingDeepLearning","DetectObjectsUsingDeepLearning"].indexOf(this.toolName);this.isDetectObjectTool="DetectObjectsUsingDeepLearning"==this.toolName;this.signInPromise.then(d.hitch(this,function(){h.initHelpLinks(this.domNode,this.showHelp,
{analysisGpServer:this.analysisGpServer,analysisMode:"raster"});if(this.isDLTool){var a=[],c;q({url:this.portalUrl+"/sharing/search",content:{f:"json",q:"Deep learning package"}},{usePost:!0}).then(d.hitch(this,function(b){b&&(b=b.results)&&0<b.length&&(k.forEach(b,d.hitch(this,function(b){b={value:b.id,label:b.title};a.push(b);this._modelSelect.addOption(b)})),this.models=a,this.model&&(c=this.model.itemId),this.model&&0<=a.findIndex(function(a){return a.value===c})?(this.modelArguments&&this._updateModelArguments(this.modelArguments),
this._modelSelect.set("value",this.model.itemId)):this.model={itemId:0})}))}}));if(this.rasterFunction){var c=this._getReRunRFxArgs(this.rasterFunction,this._findDeepestArgsForRerun);c&&d.mixin(this,c)}this.functionArguments&&this.functionArguments.Raster&&this.set("inputLayer",this.functionArguments.Raster);this.get("showSelectAnalysisLayer")&&(this.inputLayers&&this.inputLayer&&!h.isLayerInLayers(this.inputLayer,this.inputLayers)&&this.inputLayers.push(this.inputLayer),this.get("inputLayer")||!this.get("inputLayers")||
this.rerun||this.set("inputLayer",this.inputLayers[0]),h.populateAnalysisLayers(this,"inputLayer","inputLayers"));this.addAnalysisBrowseOption();this.outputLayerName&&(this._outputLayerInput.set("value",this.outputLayerName),a=!1);(this.inputLayer||"ApplyRFxTemplate"===this.toolName)&&this._updateAnalysisLayerUI(a);m.set(this._chooseFolderRow,"display",!0===this.showSelectFolder?"block":"none");this.showSelectFolder&&this.getFolderStore().then(d.hitch(this,function(a){this.folderStore=a;h.setupFoldersUI({folderStore:this.folderStore,
folderId:this.folderId,folderName:this.folderName,folderSelect:this._webMapFolderSelect,username:this.portalUser?this.portalUser.username:""})}));this._chooseLayerTypeRow&&(m.set(this._chooseLayerTypeRow,"display",!0===this.showSelectLayerType?"block":"none"),a=new x({data:[{name:this.i18n.permanentLayer,id:"permanentLayer"},{name:this.i18n.dynamicLayer,id:"dynamicLayer"}]}),this._webLayerTypeSelect.set("store",a),this._webLayerTypeSelect.set("value","permanentLayer"));m.set(this._chooseExtentDiv,
"display",!0===this.showChooseExtent?"inline-block":"none");m.set(this._showCreditsLink,"display",!0===this.showCredits?"block":"none");this.inputLayer&&this.inputLayer.drawnLayer&&this._sourceDrawBtn&&this._sourceDrawBtn.set("pointFeatureLayer",this.inputLayer);this._setDefaultInputs()},addAnalysisBrowseOption:function(){this.browseType&&1===this.browseType.length&&-1<this.browseType.indexOf(v.IS)?h.addReadyToUseLayerOption(this,[{select:this._analysisSelect,disableLAAL:!0}]):h.addReadyToUseLayerOption(this,
[this._analysisSelect]);this.addBrowseOption()},getOptionsForRasterBrowseItems:function(a){return-1<this.browseType.indexOf(v.FS)?{browseValue:a}:{browseValue:a,disableLAAL:!0,disableBoundary:!0}},addBrowseOption:function(){},isImageServiceLayer:function(a){return a&&(a instanceof E||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass)},_loadConnections:function(){this.on("start",d.hitch(this,"_onClose",!1));this._connect(this._closeBtn,"onclick",d.hitch(this,"_onClose",!0))},_connect:function(a,
c,b){this._pbConnects.push(u.connect(a,c,b))}});A("extend-esri")&&d.setObject("dijit.analysis.RasterAnalysisMixin",n,F);return n});